
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#define MAXPOOL_INT16_1_OUT_CH 2
#define MAXPOOL_INT16_1_IN_CH 2
#define MAXPOOL_INT16_1_INPUT_W 4
#define MAXPOOL_INT16_1_INPUT_H 5
#define MAXPOOL_INT16_1_DST_SIZE 20
#define MAXPOOL_INT16_1_INPUT_SIZE 40
#define MAXPOOL_INT16_1_OUT_ACTIVATION_MIN -30000
#define MAXPOOL_INT16_1_OUT_ACTIVATION_MAX 30000
#define MAXPOOL_INT16_1_INPUT_BATCHES 1
#define MAXPOOL_INT16_1_FILTER_X 3
#define MAXPOOL_INT16_1_FILTER_Y 3
#define MAXPOOL_INT16_1_STRIDE_X 2
#define MAXPOOL_INT16_1_STRIDE_Y 1
#define MAXPOOL_INT16_1_PAD_X 0
#define MAXPOOL_INT16_1_PAD_Y 1
#define MAXPOOL_INT16_1_OUTPUT_W 2
#define MAXPOOL_INT16_1_OUTPUT_H 5
