
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int16_t maxpool_int16_1_input[40] = {-26166, 30277,  11438,  20713,  15203, 659,    -13120, 14310,  -6746, -11050,
                                           -27477, -11078, -1542,  -876,   1321,  29953,  -6256,  -19500, 13480, -16407,
                                           22221,  20370,  -12144, -18899, -974,  -27310, 126,    -10634, 23432, -466,
                                           -24241, -5013,  -5155,  -1014,  24020, 26023,  4895,   32059,  -3012, 5604};
