
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t avgpooling_4_input[40] = {-49, 31, 94,  36,   -124, -57, -39, -54, 70,   -37, -127, -36, 43,   94,
                                       43,  13, -73, -14,  -16,  -48, 3,   -47, -109, -72, 43,   -53, -128, 118,
                                       -65, 60, 8,   -112, 87,   119, -95, 26,  95,   -74, 24,   10};
