// Copyright 2020-2025 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <driver/hal/hal_gpio_types.h>
#include <soc/soc.h>
#include "sdkconfig.h"

#define GPIO_DEV_MAP  \
{\
	{GPIO_0, {GPIO_DEV_UART2_TXD, GPIO_DEV_I2C1_SCL, GPIO_DEV_JTAG_TCK, GPIO_DEV_INVALID, GPIO_DEV_ADC12, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_1, {GPIO_DEV_UART2_RXD, GPIO_DEV_I2C1_SDA, GPIO_DEV_JTAG_TMS, GPIO_DEV_INVALID, GPIO_DEV_ADC13, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_2, {GPIO_DEV_SPI1_SCK, GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_INVALID, GPIO_DEV_TAMP_RX_I, GPIO_DEV_PWM6, GPIO_DEV_DEBUG0, GPIO_DEV_QSPI0_CLK, GPIO_DEV_INVALID}},\
	{GPIO_3, {GPIO_DEV_SPI1_CSN, GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_INVALID, GPIO_DEV_TAMP_TX_O, GPIO_DEV_PWM7, GPIO_DEV_DEBUG1, GPIO_DEV_QSPI0_CSN, GPIO_DEV_INVALID}},\
	{GPIO_4, {GPIO_DEV_SPI1_MOSI, GPIO_DEV_SDIO_HOST_DATA0, GPIO_DEV_INVALID, GPIO_DEV_I2C1_SCL, GPIO_DEV_PWM8, GPIO_DEV_DEBUG2, GPIO_DEV_QSPI0_IO0, GPIO_DEV_INVALID}},\
	{GPIO_5, {GPIO_DEV_SPI1_MISO, GPIO_DEV_SDIO_HOST_DATA1, GPIO_DEV_TAMP_TX_O, GPIO_DEV_I2C1_SDA, GPIO_DEV_PWM9, GPIO_DEV_DEBUG3, GPIO_DEV_QSPI0_IO1, GPIO_DEV_INVALID}},\
	{GPIO_6, {GPIO_DEV_CLK_XTAL_DIV, GPIO_DEV_PWM0, GPIO_DEV_I2S1_CLK, GPIO_DEV_TAMP_TX_O, GPIO_DEV_INVALID, GPIO_DEV_DEBUG4, GPIO_DEV_QSPI0_IO2, GPIO_DEV_INVALID}},\
	{GPIO_7, {GPIO_DEV_WIFI_ACTIVE, GPIO_DEV_PWM1, GPIO_DEV_I2S1_SYNC, GPIO_DEV_FEM_LNA_EN, GPIO_DEV_INVALID, GPIO_DEV_DEBUG5, GPIO_DEV_QSPI0_IO3, GPIO_DEV_INVALID}},\
	{GPIO_8, {GPIO_DEV_BT_ACTIVE, GPIO_DEV_PWM2, GPIO_DEV_I2S1_DIN, GPIO_DEV_WIFI_TX_EN, GPIO_DEV_ADC10, GPIO_DEV_DEBUG6, GPIO_DEV_TAMP_RX_I, GPIO_DEV_INVALID}},\
	{GPIO_9, {GPIO_DEV_BT_PRIORITY, GPIO_DEV_PWM3, GPIO_DEV_I2S1_DOUT, GPIO_DEV_WIFI_RX_EN, GPIO_DEV_ADC11, GPIO_DEV_DEBUG7, GPIO_DEV_TAMP_TX_O, GPIO_DEV_INVALID}},\
	{GPIO_10,{GPIO_DEV_UART1_RXD, GPIO_DEV_SDIO_HOST_DATA2, GPIO_DEV_CLK_AUXS, GPIO_DEV_SW_CLK, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_11, {GPIO_DEV_UART1_TXD, GPIO_DEV_SDIO_HOST_DATA3, GPIO_DEV_INVALID, GPIO_DEV_SWD_IO, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_12, {GPIO_DEV_UART1_RTS, GPIO_DEV_PWM10, GPIO_DEV_I2S1_MCLK, GPIO_DEV_I2C0_SCL, GPIO_DEV_ADC14, GPIO_DEV_DEBUG8, GPIO_DEV_UART4_RTS, GPIO_DEV_TAMP_RX_I}},\
	{GPIO_13, {GPIO_DEV_UART1_CTS, GPIO_DEV_PWM11, GPIO_DEV_INVALID, GPIO_DEV_I2C0_SDA, GPIO_DEV_ADC15, GPIO_DEV_DEBUG9, GPIO_DEV_UART4_CTS, GPIO_DEV_TAMP_TX_O}},\
	{GPIO_14, {GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_SPI0_SCK, GPIO_DEV_BT_ANT0, GPIO_DEV_I2C1_SCL, GPIO_DEV_INVALID, GPIO_DEV_DEBUG10, GPIO_DEV_UART4_TXD, GPIO_DEV_INVALID}},\
	{GPIO_15, {GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_SPI0_CSN, GPIO_DEV_BT_ANT1, GPIO_DEV_I2C1_SDA, GPIO_DEV_INVALID, GPIO_DEV_DEBUG11, GPIO_DEV_UART4_RXD, GPIO_DEV_INVALID}},\
	{GPIO_16, {GPIO_DEV_SDIO_HOST_DATA0, GPIO_DEV_SPI0_MOSI, GPIO_DEV_BT_ANT2, GPIO_DEV_UART2_TXD, GPIO_DEV_INVALID, GPIO_DEV_DEBUG12, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_17, {GPIO_DEV_SDIO_HOST_DATA1, GPIO_DEV_SPI0_MISO, GPIO_DEV_BT_ANT3, GPIO_DEV_UART2_RXD, GPIO_DEV_INVALID, GPIO_DEV_DEBUG13, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_18, {GPIO_DEV_SDIO_HOST_DATA2, GPIO_DEV_PWM4, GPIO_DEV_LEDC, GPIO_DEV_INVALID, GPIO_DEV_TAMP_RX_I, GPIO_DEV_DEBUG14, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_19, {GPIO_DEV_SDIO_HOST_DATA3, GPIO_DEV_PWM5, GPIO_DEV_INVALID, GPIO_DEV_FEM_LNA_EN, GPIO_DEV_TAMP_TX_O, GPIO_DEV_DEBUG15, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_20, {GPIO_DEV_I2C0_SCL, GPIO_DEV_JTAG_TCK, GPIO_DEV_INVALID, GPIO_DEV_UART3_TXD, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_21, {GPIO_DEV_I2C0_SDA, GPIO_DEV_JTAG_TMS, GPIO_DEV_ADC6,  GPIO_DEV_UART3_RXD, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_22, {GPIO_DEV_CLK_XTAL, GPIO_DEV_PWM2, GPIO_DEV_ADC5, GPIO_DEV_WIFI_TX_EN, GPIO_DEV_TAMP_TX_O, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_23, {GPIO_DEV_LPO_CLK, GPIO_DEV_PWM3, GPIO_DEV_ADC3, GPIO_DEV_WIFI_RX_EN, GPIO_DEV_TAMP_RX_I, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
}

#if defined(CONFIG_GPIO_DEFAULT_SET_SUPPORT)

#if defined(CONFIG_SPE) && (CONFIG_SPE == 1)
#define GPIO_0_DEFAULT_MAP {GPIO_0,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART2_TXD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3},
#define GPIO_1_DEFAULT_MAP {GPIO_1,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART2_RXD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3},
#else
#define GPIO_0_DEFAULT_MAP
#define GPIO_1_DEFAULT_MAP
#endif

#define GPIO_DEFAULT_DEV_CONFIG  \
{\
	GPIO_0_DEFAULT_MAP \
	GPIO_1_DEFAULT_MAP \
	{GPIO_2,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_CLK, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3},\
	{GPIO_3,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_CMD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3},\
	{GPIO_4,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_DATA0, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3},\
	{GPIO_5,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_6,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_I2S1_CLK, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_7,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_I2S1_SYNC, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_8,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_KEEP_INPUT_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_9,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_I2S1_DOUT, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_KEEP_INPUT_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_10, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART1_RXD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_11, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART1_TXD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_12, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_PWM10, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_13, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_PWM11, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_14, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SPI0_SCK, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_15, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SPI0_CSN, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_16, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SPI0_MOSI, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_17, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SPI0_MISO, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_18, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LEDC, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_19, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_FEM_LNA_EN, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_20, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART2_TXD, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_21, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART2_RXD, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_22, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_TAMP_TX_O, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_23, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_TAMP_RX_I, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
}
#endif

#if defined(CONFIG_GPIO_CLOCK_PIN_SUPPORT)
/**
 * GPIO CLK PIN TABLE
 *
 * | CLK_SRC | CLK_PORT | FREQ            | PIN          |
 * | ------- | -------- | --------------- | ------------ |
 * | ROSC    | ANA      | -               | GPIO13       |
 * | ROSC    | DIG      | -               | GPIO23       |
 * | XTAL-L  | ANA      | 32.768K         | GPIO13       |
 * | XTAL-L  | DIG      | 32.768K         | GPIO23       |
 * | XTAL-H  | DIG      | 32K/40M         | GPIO23/GPIO22|
 * | XTAL-HD | DIG      | DIV1-4          | GPIO6        |
 * | DPLL    | ANA      | 10M             | GPIO13       |
 * | DPLL    | DIG      | DIV1-16         | GPIO13       |
 *
*/

#define GPIO_CLK_PIN_MAP \
{\
	{GPIO_CLK_PIN_SRC_ROSC,     {GPIO_13,      CLK_PIN_ANA_ROSC   }, {GPIO_6,       GPIO_DEV_LPO_CLK,  CLK_PIN_DIG_LPO_CLK_ROSC     }},\
	{GPIO_CLK_PIN_SRC_XTALL,    {GPIO_13,      CLK_PIN_ANA_XTAL   }, {GPIO_6,       GPIO_DEV_LPO_CLK,  CLK_PIN_DIG_LPO_CLK_XTALL    }},\
	{GPIO_CLK_PIN_SRC_XTALH,    {GPIO_NUM_MAX, CLK_PIN_ANA_INVALID}, {GPIO_22,      GPIO_DEV_CLK_XTAL, CLK_PIN_DIG_XTAL             }},\
	{GPIO_CLK_PIN_SRC_XTALHD,   {GPIO_NUM_MAX, CLK_PIN_ANA_INVALID}, {GPIO_22,      GPIO_DEV_CLK_XTAL_DIV, CLK_PIN_DIG_XTAL_DIV     }},\
	{GPIO_CLK_PIN_SRC_XTALH32K, {GPIO_NUM_MAX, CLK_PIN_ANA_INVALID}, {GPIO_6,       GPIO_DEV_LPO_CLK,  CLK_PIN_DIG_LPO_CLK_XTALH    }},\
	{GPIO_CLK_PIN_SRC_DCO,      {GPIO_NUM_MAX, CLK_PIN_ANA_INVALID}, {GPIO_NUM_MAX, GPIO_DEV_INVALID,  CLK_PIN_DIG_INVALID          }},\
	{GPIO_CLK_PIN_SRC_DPLL,     {GPIO_13,      CLK_PIN_ANA_DPLL   }, {GPIO_13,      GPIO_DEV_CLK_AUXS, CLK_PIN_DIG_CLK_AUXS_CLK_480M}},\
	{GPIO_CLK_PIN_SRC_APLL,     {GPIO_NUM_MAX, CLK_PIN_ANA_INVALID}, {GPIO_NUM_MAX, GPIO_DEV_INVALID,  CLK_PIN_DIG_INVALID          }},\
}
#endif

#if defined(CONFIG_BEKEN_EVB)
/* uart gpio pin map */
#define UART0_TX_PIN  GPIO_11
#define UART0_RX_PIN  GPIO_10
#define UART0_CTS_PIN GPIO_12
#define UART0_RTS_PIN GPIO_13

#define UART1_TX_PIN  GPIO_14
#define UART1_RX_PIN  GPIO_15

#define UART2_TX_PIN  GPIO_20
#define UART2_RX_PIN  GPIO_21

#define UART3_TX_PIN  GPIO_0
#define UART3_RX_PIN  GPIO_1
#else

#define UART0_TX_PIN  GPIO_11
#define UART0_RX_PIN  GPIO_10
#define UART0_CTS_PIN GPIO_12
#define UART0_RTS_PIN GPIO_13

#define UART1_TX_PIN  GPIO_14
#define UART1_RX_PIN  GPIO_15

#define UART2_TX_PIN  GPIO_20
#define UART2_RX_PIN  GPIO_21

#define UART3_TX_PIN  GPIO_16
#define UART3_RX_PIN  GPIO_17

#endif
/* sdio host */
#if defined(CONFIG_SDCARD_BUSWIDTH_4LINE)
#define SDIO_HOST_GPIO_PIN_NUMBER    6
#else
#define SDIO_HOST_GPIO_PIN_NUMBER    3
#endif

#define SDIO_HOST_GPIO_CLK_INDEX     0
#define SDIO_HOST_GPIO_CMD_INDEX     1
#define SDIO_HOST_GPIO_DATA0_INDEX   2
#define SDIO_HOST_GPIO_DATA1_INDEX   3

#define SDIO_GPIO_MAP \
{\
	{GPIO_14, GPIO_DEV_SDIO_HOST_CLK},\
	{GPIO_15, GPIO_DEV_SDIO_HOST_CMD},\
	{GPIO_16, GPIO_DEV_SDIO_HOST_DATA0},\
	{GPIO_17, GPIO_DEV_SDIO_HOST_DATA1},\
	{GPIO_18, GPIO_DEV_SDIO_HOST_DATA2},\
	{GPIO_19, GPIO_DEV_SDIO_HOST_DATA3},\
}

#define GPIO_PWM_MAP_TABLE \
{ \
	{GPIO_6, GPIO_DEV_PWM0},\
	{GPIO_7, GPIO_DEV_PWM1},\
	{GPIO_8, GPIO_DEV_PWM2},\
	{GPIO_9, GPIO_DEV_PWM3},\
	{GPIO_18, GPIO_DEV_PWM4},\
	{GPIO_19, GPIO_DEV_PWM5},\
	{GPIO_20, GPIO_DEV_PWM6},\
	{GPIO_21, GPIO_DEV_PWM7},\
	{GPIO_22, GPIO_DEV_PWM8},\
	{GPIO_5, GPIO_DEV_PWM9},\
	{GPIO_12, GPIO_DEV_PWM10},\
	{GPIO_13, GPIO_DEV_PWM11},\
}

#define GPIO_MAP_TABLE(DEV_NUM, MODE_NUM, table) \
struct {\
	uint64_t gpio_bits;\
	gpio_dev_t devs[DEV_NUM];\
} table[MODE_NUM]

#define GPIO_I2C1_MAP_TABLE \
{\
	{BIT(0)|BIT(1), {GPIO_DEV_I2C1_SCL, GPIO_DEV_I2C1_SDA}},\
	{BIT64(42)|BIT64(43), {GPIO_DEV_I2C1_SCL, GPIO_DEV_I2C1_SDA}},\
}
#define GPIO_I2C1_USED_GPIO_NUM 2

#define GPIO_I2S_MAP_TABLE \
{\
	{BIT(6)|BIT(7)|BIT(8)|BIT(9), {GPIO_DEV_I2S1_CLK, GPIO_DEV_I2S1_SYNC, GPIO_DEV_I2S1_DIN, GPIO_DEV_I2S1_DOUT}},\
	{BIT64(40)|BIT64(41)|BIT64(42)|BIT64(43), {GPIO_DEV_I2S1_CLK, GPIO_DEV_I2S1_SYNC, GPIO_DEV_I2S1_DIN, GPIO_DEV_I2S1_DOUT}},\
}
#define GPIO_I2S_USED_GPIO_NUM 4

#define GPIO_SPI0_MAP_TABLE \
{\
	{BIT(14)|BIT(15)|BIT64(16)|BIT64(17), {GPIO_DEV_SPI0_SCK, GPIO_DEV_SPI0_CSN, GPIO_DEV_SPI0_MOSI, GPIO_DEV_SPI0_MISO}},\
	{BIT64(44)|BIT64(45)|BIT64(46)|BIT64(47), {GPIO_DEV_SPI0_CSN, GPIO_DEV_SPI0_SCK, GPIO_DEV_SPI0_MOSI, GPIO_DEV_SPI0_MISO}},\
}
#define GPIO_SPI0_USED_GPIO_NUM 4

#define GPIO_SDIO_ONE_LINE_MAP_TABLE \
{\
	{BIT(2)|BIT(3)|BIT(4), {GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_SDIO_HOST_DATA0}},\
	{BIT(14)|BIT(15)|BIT(16), {GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_SDIO_HOST_DATA0}},\
}
#define GPIO_SDIO_ONE_LINE_USED_GPIO_NUM 3

#define GPIO_SDIO_MAP_TABLE \
{\
	{BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(10)|BIT(11), {GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_SDIO_HOST_DATA0,GPIO_DEV_SDIO_HOST_DATA1,GPIO_DEV_SDIO_HOST_DATA2,GPIO_DEV_SDIO_HOST_DATA3}},\
	{BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19), {GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_SDIO_HOST_DATA0,GPIO_DEV_SDIO_HOST_DATA1,GPIO_DEV_SDIO_HOST_DATA2,GPIO_DEV_SDIO_HOST_DATA3}},\
}
#define GPIO_SDIO_USED_GPIO_NUM 6

#define GPIO_CTRL_LDO_OUTPUT_HIGH_MAP  \
{\
	/* GPIO_2, */\
	/* GPIO_28, */\
}

#define GPIO_CTRL_LDO_OUTPUT_LOW_MAP  \
{\
	/* GPIO_4, */\
	/* GPIO_26, */\
}
/*---multi modules use one gpio to control different ldo---*/
#define GPIO_CTRL_LDO_MAP  \
{\
	{GPIO_13,  GPIO_OUTPUT_STATE_LOW},\
	{GPIO_28,  GPIO_OUTPUT_STATE_LOW},\
}
/*
 * Camera DVP GPIO MAP
 */
#define CAMERA_DVP_MCLK_PIN             (GPIO_27)
#define CAMERA_DVP_PCLK_PIN             (GPIO_29)
#define CAMERA_DVP_HSYNC_PIN            (GPIO_30)
#define CAMERA_DVP_VSYNC_PIN            (GPIO_31)
#define CAMERA_DVP_PXDATA0_PIN          (GPIO_32)
#define CAMERA_DVP_PXDATA1_PIN          (GPIO_33)
#define CAMERA_DVP_PXDATA2_PIN          (GPIO_34)
#define CAMERA_DVP_PXDATA3_PIN          (GPIO_35)
#define CAMERA_DVP_PXDATA4_PIN          (GPIO_36)
#define CAMERA_DVP_PXDATA5_PIN          (GPIO_37)
#define CAMERA_DVP_PXDATA6_PIN          (GPIO_38)
#define CAMERA_DVP_PXDATA7_PIN          (GPIO_39)

#define CAMERA_DVP_MCLK_FUNC            (GPIO_DEV_JPEG_MCLK)
#define CAMERA_DVP_AUXS_FUNC            (GPIO_DEV_CLK_AUXS)
#define CAMERA_DVP_PCLK_FUNC            (GPIO_DEV_JPEG_PCLK)
#define CAMERA_DVP_HSYNC_FUNC           (GPIO_DEV_JPEG_HSYNC)
#define CAMERA_DVP_VSYNC_FUNC           (GPIO_DEV_JPEG_VSYNC)
#define CAMERA_DVP_PXDATA0_FUNC         (GPIO_DEV_JPEG_PXDATA0)
#define CAMERA_DVP_PXDATA1_FUNC         (GPIO_DEV_JPEG_PXDATA1)
#define CAMERA_DVP_PXDATA2_FUNC         (GPIO_DEV_JPEG_PXDATA2)
#define CAMERA_DVP_PXDATA3_FUNC         (GPIO_DEV_JPEG_PXDATA3)
#define CAMERA_DVP_PXDATA4_FUNC         (GPIO_DEV_JPEG_PXDATA4)
#define CAMERA_DVP_PXDATA5_FUNC         (GPIO_DEV_JPEG_PXDATA5)
#define CAMERA_DVP_PXDATA6_FUNC         (GPIO_DEV_JPEG_PXDATA6)
#define CAMERA_DVP_PXDATA7_FUNC         (GPIO_DEV_JPEG_PXDATA7)

#define CAMERA_DVP_I2C_ID               (CONFIG_DVP_CAMERA_I2C_ID)
#define CAMERA_DVP_I2C_BAUD_RATE        (I2C_BAUD_RATE_100KHZ)
#define CAMERA_DVP_I2C_MODE             (I2C_ADDR_MODE_7BIT)

#define SDCARD_LDO_CTRL_GPIO               (GPIO_13)
#define SDCARD_LDO_CTRL_ACTIVE_LEVEL       (1)

#if defined(CONFIG_GPIO_WAKEUP_SUPPORT)
#define GPIO_STATIC_WAKEUP_SOURCE_MAP  \
	{\
		/*{GPIO_6, GPIO_INT_TYPE_LOW_LEVEL},*/ \
		{GPIO_10, GPIO_INT_TYPE_FALLING_EDGE},\
		/*{GPIO_40, GPIO_INT_LEVEL_LOW},*/ \
	}
#endif

#define IRDA_PIN    (GPIO_25)

#ifdef __cplusplus
}
#endif
