// Copyright 2022-2025 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This is a generated file, if you need to modify it, use the script to
// generate and modify all the struct.h, ll.h, reg.h, debug_dump.c files!

#pragma once


#ifdef __cplusplus
extern "C" {
#endif


#define SYS_ANA_ANA_REG0_ADDR (SOC_SYS_ANA_REG_BASE + (0x40 << 2))

#define SYS_ANA_ANA_REG0_VCTRL_TESTEN_POS (0)
#define SYS_ANA_ANA_REG0_VCTRL_TESTEN_MASK (0x1)

#define SYS_ANA_ANA_REG0_VCTRLSEL_POS (1)
#define SYS_ANA_ANA_REG0_VCTRLSEL_MASK (0x3)

#define SYS_ANA_ANA_REG0_CP_IOFF_POS (3)
#define SYS_ANA_ANA_REG0_CP_IOFF_MASK (0x3)

#define SYS_ANA_ANA_REG0_SPISEL_UNLOCKL_POS (5)
#define SYS_ANA_ANA_REG0_SPISEL_UNLOCKL_MASK (0x1)

#define SYS_ANA_ANA_REG0_SPISEL_UNLOCKH_POS (6)
#define SYS_ANA_ANA_REG0_SPISEL_UNLOCKH_MASK (0x1)

#define SYS_ANA_ANA_REG0_CP_POS (7)
#define SYS_ANA_ANA_REG0_CP_MASK (0x7)

#define SYS_ANA_ANA_REG0_SPIDETEN_POS (10)
#define SYS_ANA_ANA_REG0_SPIDETEN_MASK (0x1)

#define SYS_ANA_ANA_REG0_CBEN_POS (11)
#define SYS_ANA_ANA_REG0_CBEN_MASK (0x1)

#define SYS_ANA_ANA_REG0_HVREF_POS (12)
#define SYS_ANA_ANA_REG0_HVREF_MASK (0x3)

#define SYS_ANA_ANA_REG0_LVREF_POS (14)
#define SYS_ANA_ANA_REG0_LVREF_MASK (0x3)

#define SYS_ANA_ANA_REG0_RZCTRL26M_POS (16)
#define SYS_ANA_ANA_REG0_RZCTRL26M_MASK (0x1)

#define SYS_ANA_ANA_REG0_LPF_RZ_POS (17)
#define SYS_ANA_ANA_REG0_LPF_RZ_MASK (0xf)

#define SYS_ANA_ANA_REG0_RPC_POS (21)
#define SYS_ANA_ANA_REG0_RPC_MASK (0x3)

#define SYS_ANA_ANA_REG0_DPLL_TSTEN_POS (23)
#define SYS_ANA_ANA_REG0_DPLL_TSTEN_MASK (0x1)

#define SYS_ANA_ANA_REG0_DIVSEL_POS (24)
#define SYS_ANA_ANA_REG0_DIVSEL_MASK (0x3)

#define SYS_ANA_ANA_REG0_KCTRL_POS (26)
#define SYS_ANA_ANA_REG0_KCTRL_MASK (0x3)

#define SYS_ANA_ANA_REG0_VSEL_LDO_POS (28)
#define SYS_ANA_ANA_REG0_VSEL_LDO_MASK (0x3)

#define SYS_ANA_ANA_REG0_BP_CALDONE_POS (30)
#define SYS_ANA_ANA_REG0_BP_CALDONE_MASK (0x1)

#define SYS_ANA_ANA_REG0_SPI_RST_UNLOCK_POS (31)
#define SYS_ANA_ANA_REG0_SPI_RST_UNLOCK_MASK (0x1)

#define SYS_ANA_ANA_REG1_ADDR (SOC_SYS_ANA_REG_BASE + (0x41 << 2))

#define SYS_ANA_ANA_REG1_NC_0_0_POS (0)
#define SYS_ANA_ANA_REG1_NC_0_0_MASK (0x1)

#define SYS_ANA_ANA_REG1_BANDMANUAL_POS (1)
#define SYS_ANA_ANA_REG1_BANDMANUAL_MASK (0x1ff)

#define SYS_ANA_ANA_REG1_MANUAL_ICTRL_POS (10)
#define SYS_ANA_ANA_REG1_MANUAL_ICTRL_MASK (0x1)

#define SYS_ANA_ANA_REG1_ENCLK_POS (11)
#define SYS_ANA_ANA_REG1_ENCLK_MASK (0x1)

#define SYS_ANA_ANA_REG1_CLOSELOOP_EN_POS (12)
#define SYS_ANA_ANA_REG1_CLOSELOOP_EN_MASK (0x1)

#define SYS_ANA_ANA_REG1_NC_13_13_POS (13)
#define SYS_ANA_ANA_REG1_NC_13_13_MASK (0x1)

#define SYS_ANA_ANA_REG1_SPI_RSTN_POS (14)
#define SYS_ANA_ANA_REG1_SPI_RSTN_MASK (0x1)

#define SYS_ANA_ANA_REG1_OSCCAL_TRIG_POS (15)
#define SYS_ANA_ANA_REG1_OSCCAL_TRIG_MASK (0x1)

#define SYS_ANA_ANA_REG1_MANUAL_POS (16)
#define SYS_ANA_ANA_REG1_MANUAL_MASK (0x1)

#define SYS_ANA_ANA_REG1_DIFFL_POS (17)
#define SYS_ANA_ANA_REG1_DIFFL_MASK (0x7)

#define SYS_ANA_ANA_REG1_ICTRL_POS (20)
#define SYS_ANA_ANA_REG1_ICTRL_MASK (0x7)

#define SYS_ANA_ANA_REG1_CNTI_POS (23)
#define SYS_ANA_ANA_REG1_CNTI_MASK (0x1ff)

#define SYS_ANA_ANA_REG2_ADDR (SOC_SYS_ANA_REG_BASE + (0x42 << 2))

#define SYS_ANA_ANA_REG2_XTALH_CTUNE_POS (0)
#define SYS_ANA_ANA_REG2_XTALH_CTUNE_MASK (0xff)

#define SYS_ANA_ANA_REG2_GADC_INBUFSEL_POS (8)
#define SYS_ANA_ANA_REG2_GADC_INBUFSEL_MASK (0x3)

#define SYS_ANA_ANA_REG2_BUFICTRL_POS (10)
#define SYS_ANA_ANA_REG2_BUFICTRL_MASK (0x1)

#define SYS_ANA_ANA_REG2_GADC_COMPISEL_POS (11)
#define SYS_ANA_ANA_REG2_GADC_COMPISEL_MASK (0x7)

#define SYS_ANA_ANA_REG2_GADC_BSCALSAW_POS (14)
#define SYS_ANA_ANA_REG2_GADC_BSCALSAW_MASK (0x7)

#define SYS_ANA_ANA_REG2_GADC_VNCALSAW_POS (17)
#define SYS_ANA_ANA_REG2_GADC_VNCALSAW_MASK (0x7)

#define SYS_ANA_ANA_REG2_GADC_VPCALSAW_POS (20)
#define SYS_ANA_ANA_REG2_GADC_VPCALSAW_MASK (0x7)

#define SYS_ANA_ANA_REG2_GADC_VBG_SEL_POS (23)
#define SYS_ANA_ANA_REG2_GADC_VBG_SEL_MASK (0x1)

#define SYS_ANA_ANA_REG2_GADC_CLK_RLTEN_POS (24)
#define SYS_ANA_ANA_REG2_GADC_CLK_RLTEN_MASK (0x1)

#define SYS_ANA_ANA_REG2_GADC_CALINTSAW_EN_POS (25)
#define SYS_ANA_ANA_REG2_GADC_CALINTSAW_EN_MASK (0x1)

#define SYS_ANA_ANA_REG2_GADC_CLK_SEL_POS (26)
#define SYS_ANA_ANA_REG2_GADC_CLK_SEL_MASK (0x1)

#define SYS_ANA_ANA_REG2_GADC_CLK_INV_POS (27)
#define SYS_ANA_ANA_REG2_GADC_CLK_INV_MASK (0x1)

#define SYS_ANA_ANA_REG2_GADC_CALCAP_CH_POS (28)
#define SYS_ANA_ANA_REG2_GADC_CALCAP_CH_MASK (0x3)

#define SYS_ANA_ANA_REG2_INBUFEN_POS (30)
#define SYS_ANA_ANA_REG2_INBUFEN_MASK (0x1)

#define SYS_ANA_ANA_REG2_SAR_ENSPI_POS (31)
#define SYS_ANA_ANA_REG2_SAR_ENSPI_MASK (0x1)

#define SYS_ANA_ANA_REG3_ADDR (SOC_SYS_ANA_REG_BASE + (0x43 << 2))

#define SYS_ANA_ANA_REG3_RESERVED_BIT_0_0_POS (0)
#define SYS_ANA_ANA_REG3_RESERVED_BIT_0_0_MASK (0x1)

#define SYS_ANA_ANA_REG3_PREAMP_ISEL_POS (1)
#define SYS_ANA_ANA_REG3_PREAMP_ISEL_MASK (0x3)

#define SYS_ANA_ANA_REG3_REFBUFF_ISEL_POS (3)
#define SYS_ANA_ANA_REG3_REFBUFF_ISEL_MASK (0x7)

#define SYS_ANA_ANA_REG3_VREF_SEL_POS (6)
#define SYS_ANA_ANA_REG3_VREF_SEL_MASK (0x1)

#define SYS_ANA_ANA_REG3_OFFSET_EN_POS (7)
#define SYS_ANA_ANA_REG3_OFFSET_EN_MASK (0x1)

#define SYS_ANA_ANA_REG3_HPSSREN_POS (8)
#define SYS_ANA_ANA_REG3_HPSSREN_MASK (0x1)

#define SYS_ANA_ANA_REG3_CK_SEL_POS (9)
#define SYS_ANA_ANA_REG3_CK_SEL_MASK (0x1)

#define SYS_ANA_ANA_REG3_LPPLLVDDSEL_POS (10)
#define SYS_ANA_ANA_REG3_LPPLLVDDSEL_MASK (0x1)

#define SYS_ANA_ANA_REG3_PWD_XTALLDO_SPI_POS (11)
#define SYS_ANA_ANA_REG3_PWD_XTALLDO_SPI_MASK (0x1)

#define SYS_ANA_ANA_REG3_IAMP_POS (12)
#define SYS_ANA_ANA_REG3_IAMP_MASK (0x1)

#define SYS_ANA_ANA_REG3_VDDREN_POS (13)
#define SYS_ANA_ANA_REG3_VDDREN_MASK (0x1)

#define SYS_ANA_ANA_REG3_XAMP_POS (14)
#define SYS_ANA_ANA_REG3_XAMP_MASK (0x3f)

#define SYS_ANA_ANA_REG3_VOSEL_POS (20)
#define SYS_ANA_ANA_REG3_VOSEL_MASK (0x1f)

#define SYS_ANA_ANA_REG3_EN_XTALH_SLEEP_POS (25)
#define SYS_ANA_ANA_REG3_EN_XTALH_SLEEP_MASK (0x1)

#define SYS_ANA_ANA_REG3_DIGBUFB_HPEN_POS (26)
#define SYS_ANA_ANA_REG3_DIGBUFB_HPEN_MASK (0x1)

#define SYS_ANA_ANA_REG3_BUFICTRL_POS (27)
#define SYS_ANA_ANA_REG3_BUFICTRL_MASK (0x1)

#define SYS_ANA_ANA_REG3_IBIAS_CTRL_POS (28)
#define SYS_ANA_ANA_REG3_IBIAS_CTRL_MASK (0x3)

#define SYS_ANA_ANA_REG3_ICORE_CTRL_POS (30)
#define SYS_ANA_ANA_REG3_ICORE_CTRL_MASK (0x3)

#define SYS_ANA_ANA_REG4_ADDR (SOC_SYS_ANA_REG_BASE + (0x44 << 2))

#define SYS_ANA_ANA_REG4_TEMP_GSEL_POS (0)
#define SYS_ANA_ANA_REG4_TEMP_GSEL_MASK (0x1)

#define SYS_ANA_ANA_REG4_VBG_0V9SEL_POS (1)
#define SYS_ANA_ANA_REG4_VBG_0V9SEL_MASK (0x1)

#define SYS_ANA_ANA_REG4_NC_2_15_POS (2)
#define SYS_ANA_ANA_REG4_NC_2_15_MASK (0x3fff)

#define SYS_ANA_ANA_REG4_CK2XSEL_POS (16)
#define SYS_ANA_ANA_REG4_CK2XSEL_MASK (0x1)

#define SYS_ANA_ANA_REG4_NC_17_21_POS (17)
#define SYS_ANA_ANA_REG4_NC_17_21_MASK (0x1f)

#define SYS_ANA_ANA_REG4_DPLL_VCTRL_TSTEN_POS (22)
#define SYS_ANA_ANA_REG4_DPLL_VCTRL_TSTEN_MASK (0x1)

#define SYS_ANA_ANA_REG4_SPILATCHB_RC32K_POS (23)
#define SYS_ANA_ANA_REG4_SPILATCHB_RC32K_MASK (0x1)

#define SYS_ANA_ANA_REG4_RC32K_REFCLK_EN_POS (24)
#define SYS_ANA_ANA_REG4_RC32K_REFCLK_EN_MASK (0x1)

#define SYS_ANA_ANA_REG4_EN_VDDFLASHTEST_POS (25)
#define SYS_ANA_ANA_REG4_EN_VDDFLASHTEST_MASK (0x1)

#define SYS_ANA_ANA_REG4_VDDGPIO_SEL_POS (26)
#define SYS_ANA_ANA_REG4_VDDGPIO_SEL_MASK (0x1)

#define SYS_ANA_ANA_REG4_CK_TST_EN_POS (27)
#define SYS_ANA_ANA_REG4_CK_TST_EN_MASK (0x1)

#define SYS_ANA_ANA_REG4_VPSRAMSEL_POS (28)
#define SYS_ANA_ANA_REG4_VPSRAMSEL_MASK (0x3)

#define SYS_ANA_ANA_REG4_SWB_POS (30)
#define SYS_ANA_ANA_REG4_SWB_MASK (0x1)

#define SYS_ANA_ANA_REG4_EN_PSRAMLDO_POS (31)
#define SYS_ANA_ANA_REG4_EN_PSRAMLDO_MASK (0x1)

#define SYS_ANA_ANA_REG5_ADDR (SOC_SYS_ANA_REG_BASE + (0x45 << 2))

#define SYS_ANA_ANA_REG5_PWD_ROSC_SPI_POS (0)
#define SYS_ANA_ANA_REG5_PWD_ROSC_SPI_MASK (0x1)

#define SYS_ANA_ANA_REG5_EN_XTALL_POS (1)
#define SYS_ANA_ANA_REG5_EN_XTALL_MASK (0x1)

#define SYS_ANA_ANA_REG5_CKTST_SEL_POS (2)
#define SYS_ANA_ANA_REG5_CKTST_SEL_MASK (0x3)

#define SYS_ANA_ANA_REG5_EN_TEMP_POS (4)
#define SYS_ANA_ANA_REG5_EN_TEMP_MASK (0x1)

#define SYS_ANA_ANA_REG5_EN_DPLL_POS (5)
#define SYS_ANA_ANA_REG5_EN_DPLL_MASK (0x1)

#define SYS_ANA_ANA_REG5_EN_CB_POS (6)
#define SYS_ANA_ANA_REG5_EN_CB_MASK (0x1)

#define SYS_ANA_ANA_REG5_PMU_TEST_POS (7)
#define SYS_ANA_ANA_REG5_PMU_TEST_MASK (0x1)

#define SYS_ANA_ANA_REG5_ANABUFSEL_RX0_POS (8)
#define SYS_ANA_ANA_REG5_ANABUFSEL_RX0_MASK (0x1)

#define SYS_ANA_ANA_REG5_ANABUFSEL_TX0_POS (9)
#define SYS_ANA_ANA_REG5_ANABUFSEL_TX0_MASK (0x1)

#define SYS_ANA_ANA_REG5_ANABUFSEL_RX1_POS (10)
#define SYS_ANA_ANA_REG5_ANABUFSEL_RX1_MASK (0x1)

#define SYS_ANA_ANA_REG5_ANABUFSEL_TX1_POS (11)
#define SYS_ANA_ANA_REG5_ANABUFSEL_TX1_MASK (0x1)

#define SYS_ANA_ANA_REG5_ROSC_DISABLE_POS (12)
#define SYS_ANA_ANA_REG5_ROSC_DISABLE_MASK (0x1)

#define SYS_ANA_ANA_REG5_LDO2XVSEL_POS (13)
#define SYS_ANA_ANA_REG5_LDO2XVSEL_MASK (0x7)

#define SYS_ANA_ANA_REG5_ITUNE_XTALL_POS (16)
#define SYS_ANA_ANA_REG5_ITUNE_XTALL_MASK (0xf)

#define SYS_ANA_ANA_REG5_XTALL_TEN_POS (20)
#define SYS_ANA_ANA_REG5_XTALL_TEN_MASK (0x1)

#define SYS_ANA_ANA_REG5_ROSC_TSTEN_POS (21)
#define SYS_ANA_ANA_REG5_ROSC_TSTEN_MASK (0x1)

#define SYS_ANA_ANA_REG5_BCAL_START_POS (22)
#define SYS_ANA_ANA_REG5_BCAL_START_MASK (0x1)

#define SYS_ANA_ANA_REG5_BCAL_EN_POS (23)
#define SYS_ANA_ANA_REG5_BCAL_EN_MASK (0x1)

#define SYS_ANA_ANA_REG5_BCAL_SEL_POS (24)
#define SYS_ANA_ANA_REG5_BCAL_SEL_MASK (0x7)

#define SYS_ANA_ANA_REG5_VBIAS_POS (27)
#define SYS_ANA_ANA_REG5_VBIAS_MASK (0x1f)

#define SYS_ANA_ANA_REG6_ADDR (SOC_SYS_ANA_REG_BASE + (0x46 << 2))

#define SYS_ANA_ANA_REG6_CALIB_INTERVAL_POS (0)
#define SYS_ANA_ANA_REG6_CALIB_INTERVAL_MASK (0x3ff)

#define SYS_ANA_ANA_REG6_MODIFY_INTERVAL_POS (10)
#define SYS_ANA_ANA_REG6_MODIFY_INTERVAL_MASK (0x3f)

#define SYS_ANA_ANA_REG6_XTAL_WAKEUP_TIME_POS (16)
#define SYS_ANA_ANA_REG6_XTAL_WAKEUP_TIME_MASK (0xf)

#define SYS_ANA_ANA_REG6_SPI_TRIG_POS (20)
#define SYS_ANA_ANA_REG6_SPI_TRIG_MASK (0x1)

#define SYS_ANA_ANA_REG6_MODIFI_AUTO_POS (21)
#define SYS_ANA_ANA_REG6_MODIFI_AUTO_MASK (0x1)

#define SYS_ANA_ANA_REG6_CALIB_AUTO_POS (22)
#define SYS_ANA_ANA_REG6_CALIB_AUTO_MASK (0x1)

#define SYS_ANA_ANA_REG6_CAL_MODE_POS (23)
#define SYS_ANA_ANA_REG6_CAL_MODE_MASK (0x1)

#define SYS_ANA_ANA_REG6_MANU_ENA_POS (24)
#define SYS_ANA_ANA_REG6_MANU_ENA_MASK (0x1)

#define SYS_ANA_ANA_REG6_MANU_CIN_POS (25)
#define SYS_ANA_ANA_REG6_MANU_CIN_MASK (0x7f)

#define SYS_ANA_ANA_REG7_ADDR (SOC_SYS_ANA_REG_BASE + (0x47 << 2))

#define SYS_ANA_ANA_REG7_CLK_SEL_POS (0)
#define SYS_ANA_ANA_REG7_CLK_SEL_MASK (0x1)

#define SYS_ANA_ANA_REG7_TIMER_WKRSTN_POS (1)
#define SYS_ANA_ANA_REG7_TIMER_WKRSTN_MASK (0x1)

#define SYS_ANA_ANA_REG7_DLDOHP_POS (2)
#define SYS_ANA_ANA_REG7_DLDOHP_MASK (0x1)

#define SYS_ANA_ANA_REG7_VPORSEL_POS (3)
#define SYS_ANA_ANA_REG7_VPORSEL_MASK (0x1)

#define SYS_ANA_ANA_REG7_VBSPBUF_LP_POS (4)
#define SYS_ANA_ANA_REG7_VBSPBUF_LP_MASK (0x1)

#define SYS_ANA_ANA_REG7_IOCURLIM_POS (5)
#define SYS_ANA_ANA_REG7_IOCURLIM_MASK (0x1)

#define SYS_ANA_ANA_REG7_VANALDOSEL_POS (6)
#define SYS_ANA_ANA_REG7_VANALDOSEL_MASK (0xf)

#define SYS_ANA_ANA_REG7_ALDOHP_POS (10)
#define SYS_ANA_ANA_REG7_ALDOHP_MASK (0x1)

#define SYS_ANA_ANA_REG7_ANACURLIM_POS (11)
#define SYS_ANA_ANA_REG7_ANACURLIM_MASK (0x1)

#define SYS_ANA_ANA_REG7_ENVREFH1V_POS (12)
#define SYS_ANA_ANA_REG7_ENVREFH1V_MASK (0x1)

#define SYS_ANA_ANA_REG7_VIOLDOSEL_POS (13)
#define SYS_ANA_ANA_REG7_VIOLDOSEL_MASK (0x7)

#define SYS_ANA_ANA_REG7_VBATDETSEL_POS (16)
#define SYS_ANA_ANA_REG7_VBATDETSEL_MASK (0x3)

#define SYS_ANA_ANA_REG7_EN_COMPE_POS (18)
#define SYS_ANA_ANA_REG7_EN_COMPE_MASK (0x1)

#define SYS_ANA_ANA_REG7_SPI_PWD_REGPOW_POS (19)
#define SYS_ANA_ANA_REG7_SPI_PWD_REGPOW_MASK (0x1)

#define SYS_ANA_ANA_REG7_BYPASSEN_POS (20)
#define SYS_ANA_ANA_REG7_BYPASSEN_MASK (0x1)

#define SYS_ANA_ANA_REG7_IOLDOLP_POS (21)
#define SYS_ANA_ANA_REG7_IOLDOLP_MASK (0x1)

#define SYS_ANA_ANA_REG7_BGCAL_POS (22)
#define SYS_ANA_ANA_REG7_BGCAL_MASK (0x3f)

#define SYS_ANA_ANA_REG7_VBGCALMODE_POS (28)
#define SYS_ANA_ANA_REG7_VBGCALMODE_MASK (0x1)

#define SYS_ANA_ANA_REG7_VBGCALSTART_POS (29)
#define SYS_ANA_ANA_REG7_VBGCALSTART_MASK (0x1)

#define SYS_ANA_ANA_REG7_PWD_BGCAL_POS (30)
#define SYS_ANA_ANA_REG7_PWD_BGCAL_MASK (0x1)

#define SYS_ANA_ANA_REG7_SPI_ENVBG_POS (31)
#define SYS_ANA_ANA_REG7_SPI_ENVBG_MASK (0x1)

#define SYS_ANA_ANA_REG8_ADDR (SOC_SYS_ANA_REG_BASE + (0x48 << 2))

#define SYS_ANA_ANA_REG8_ASOFT_STC_POS (0)
#define SYS_ANA_ANA_REG8_ASOFT_STC_MASK (0xf)

#define SYS_ANA_ANA_REG8_RST_TIMERWKS1V_POS (4)
#define SYS_ANA_ANA_REG8_RST_TIMERWKS1V_MASK (0x1)

#define SYS_ANA_ANA_REG8_DLDO_CZSEL_POS (5)
#define SYS_ANA_ANA_REG8_DLDO_CZSEL_MASK (0x7)

#define SYS_ANA_ANA_REG8_DIGCURLIM_POS (8)
#define SYS_ANA_ANA_REG8_DIGCURLIM_MASK (0x1)

#define SYS_ANA_ANA_REG8_SPI_LATCH1V_POS (9)
#define SYS_ANA_ANA_REG8_SPI_LATCH1V_MASK (0x1)

#define SYS_ANA_ANA_REG8_DLDO_RZSEL_POS (10)
#define SYS_ANA_ANA_REG8_DLDO_RZSEL_MASK (0x3)

#define SYS_ANA_ANA_REG8_LVSLEEP_WKRSTN_POS (12)
#define SYS_ANA_ANA_REG8_LVSLEEP_WKRSTN_MASK (0x1)

#define SYS_ANA_ANA_REG8_GPIOWK_RSTN_POS (13)
#define SYS_ANA_ANA_REG8_GPIOWK_RSTN_MASK (0x1)

#define SYS_ANA_ANA_REG8_RTCWK_RSTN_POS (14)
#define SYS_ANA_ANA_REG8_RTCWK_RSTN_MASK (0x1)

#define SYS_ANA_ANA_REG8_ENSFSDD_POS (15)
#define SYS_ANA_ANA_REG8_ENSFSDD_MASK (0x1)

#define SYS_ANA_ANA_REG8_VCOREHSEL_POS (16)
#define SYS_ANA_ANA_REG8_VCOREHSEL_MASK (0xf)

#define SYS_ANA_ANA_REG8_VCORELSEL_POS (20)
#define SYS_ANA_ANA_REG8_VCORELSEL_MASK (0x7)

#define SYS_ANA_ANA_REG8_VLDEN_POS (23)
#define SYS_ANA_ANA_REG8_VLDEN_MASK (0x1)

#define SYS_ANA_ANA_REG8_RST_GPIOWKS_POS (24)
#define SYS_ANA_ANA_REG8_RST_GPIOWKS_MASK (0x1)

#define SYS_ANA_ANA_REG8_ALDO_RZSEL_POS (25)
#define SYS_ANA_ANA_REG8_ALDO_RZSEL_MASK (0x3)

#define SYS_ANA_ANA_REG8_ALDO_CZSEL_POS (27)
#define SYS_ANA_ANA_REG8_ALDO_CZSEL_MASK (0x7)

#define SYS_ANA_ANA_REG8_VTRXSPISEL_POS (30)
#define SYS_ANA_ANA_REG8_VTRXSPISEL_MASK (0x3)

#define SYS_ANA_ANA_REG9_ADDR (SOC_SYS_ANA_REG_BASE + (0x49 << 2))

#define SYS_ANA_ANA_REG9_AZCD_MANU_POS (0)
#define SYS_ANA_ANA_REG9_AZCD_MANU_MASK (0x3f)

#define SYS_ANA_ANA_REG9_ZCDSWVS_POS (6)
#define SYS_ANA_ANA_REG9_ZCDSWVS_MASK (0x7)

#define SYS_ANA_ANA_REG9_ZCDSREFSEL_POS (9)
#define SYS_ANA_ANA_REG9_ZCDSREFSEL_MASK (0x7)

#define SYS_ANA_ANA_REG9_ENZCDCALIB_POS (12)
#define SYS_ANA_ANA_REG9_ENZCDCALIB_MASK (0x1)

#define SYS_ANA_ANA_REG9_ENZCDDY_POS (13)
#define SYS_ANA_ANA_REG9_ENZCDDY_MASK (0x1)

#define SYS_ANA_ANA_REG9_ZCDMSEL_POS (14)
#define SYS_ANA_ANA_REG9_ZCDMSEL_MASK (0x1)

#define SYS_ANA_ANA_REG9_SPI_TIMERWKEN_POS (15)
#define SYS_ANA_ANA_REG9_SPI_TIMERWKEN_MASK (0x1)

#define SYS_ANA_ANA_REG9_SPI_BYP32PWD_POS (16)
#define SYS_ANA_ANA_REG9_SPI_BYP32PWD_MASK (0x1)

#define SYS_ANA_ANA_REG9_SD_POS (17)
#define SYS_ANA_ANA_REG9_SD_MASK (0x1)

#define SYS_ANA_ANA_REG9_IBURSTSEL_POS (18)
#define SYS_ANA_ANA_REG9_IBURSTSEL_MASK (0x3)

#define SYS_ANA_ANA_REG9_CKFS_POS (20)
#define SYS_ANA_ANA_REG9_CKFS_MASK (0x3)

#define SYS_ANA_ANA_REG9_CKINTSEL_POS (22)
#define SYS_ANA_ANA_REG9_CKINTSEL_MASK (0x1)

#define SYS_ANA_ANA_REG9_OSCCALTRIG_POS (23)
#define SYS_ANA_ANA_REG9_OSCCALTRIG_MASK (0x1)

#define SYS_ANA_ANA_REG9_MROSCSEL_POS (24)
#define SYS_ANA_ANA_REG9_MROSCSEL_MASK (0x1)

#define SYS_ANA_ANA_REG9_MROSCI_CAL_POS (25)
#define SYS_ANA_ANA_REG9_MROSCI_CAL_MASK (0x7)

#define SYS_ANA_ANA_REG9_MROSCCAP_CAL_POS (28)
#define SYS_ANA_ANA_REG9_MROSCCAP_CAL_MASK (0xf)

#define SYS_ANA_ANA_REG10_ADDR (SOC_SYS_ANA_REG_BASE + (0x4a << 2))

#define SYS_ANA_ANA_REG10_SFSR_POS (0)
#define SYS_ANA_ANA_REG10_SFSR_MASK (0xf)

#define SYS_ANA_ANA_REG10_ENSFSAA_POS (4)
#define SYS_ANA_ANA_REG10_ENSFSAA_MASK (0x1)

#define SYS_ANA_ANA_REG10_APFMS_POS (5)
#define SYS_ANA_ANA_REG10_APFMS_MASK (0x1f)

#define SYS_ANA_ANA_REG10_ATMPO_SEL_POS (10)
#define SYS_ANA_ANA_REG10_ATMPO_SEL_MASK (0x3)

#define SYS_ANA_ANA_REG10_AMPOEN_POS (12)
#define SYS_ANA_ANA_REG10_AMPOEN_MASK (0x1)

#define SYS_ANA_ANA_REG10_VBG_RSTRTC_EN_POS (13)
#define SYS_ANA_ANA_REG10_VBG_RSTRTC_EN_MASK (0x1)

#define SYS_ANA_ANA_REG10_AVEA_SEL_POS (14)
#define SYS_ANA_ANA_REG10_AVEA_SEL_MASK (0x3)

#define SYS_ANA_ANA_REG10_AFORCEPFM_POS (16)
#define SYS_ANA_ANA_REG10_AFORCEPFM_MASK (0x1)

#define SYS_ANA_ANA_REG10_ACLS_POS (17)
#define SYS_ANA_ANA_REG10_ACLS_MASK (0x7)

#define SYS_ANA_ANA_REG10_ASWRSTEN_POS (20)
#define SYS_ANA_ANA_REG10_ASWRSTEN_MASK (0x1)

#define SYS_ANA_ANA_REG10_ARIPC_POS (21)
#define SYS_ANA_ANA_REG10_ARIPC_MASK (0x7)

#define SYS_ANA_ANA_REG10_ARAMPC_POS (24)
#define SYS_ANA_ANA_REG10_ARAMPC_MASK (0xf)

#define SYS_ANA_ANA_REG10_ARAMPCEN_POS (28)
#define SYS_ANA_ANA_REG10_ARAMPCEN_MASK (0x1)

#define SYS_ANA_ANA_REG10_AENBURST_POS (29)
#define SYS_ANA_ANA_REG10_AENBURST_MASK (0x1)

#define SYS_ANA_ANA_REG10_APFMEN_POS (30)
#define SYS_ANA_ANA_REG10_APFMEN_MASK (0x1)

#define SYS_ANA_ANA_REG10_ALDOSEL_POS (31)
#define SYS_ANA_ANA_REG10_ALDOSEL_MASK (0x1)

#define SYS_ANA_ANA_REG11_ADDR (SOC_SYS_ANA_REG_BASE + (0x4b << 2))

#define SYS_ANA_ANA_REG11_GPIOWK_POS (0)
#define SYS_ANA_ANA_REG11_GPIOWK_MASK (0xffffff)

#define SYS_ANA_ANA_REG11_RTCSEL_POS (24)
#define SYS_ANA_ANA_REG11_RTCSEL_MASK (0xf)

#define SYS_ANA_ANA_REG11_TIMERSEL_POS (28)
#define SYS_ANA_ANA_REG11_TIMERSEL_MASK (0xf)

#define SYS_ANA_ANA_REG12_ADDR (SOC_SYS_ANA_REG_BASE + (0x4c << 2))

#define SYS_ANA_ANA_REG12_TIMERSEL_POS (0)
#define SYS_ANA_ANA_REG12_TIMERSEL_MASK (0xffffffff)

#define SYS_ANA_ANA_REG13_ADDR (SOC_SYS_ANA_REG_BASE + (0x4d << 2))

#define SYS_ANA_ANA_REG13_RTCSEL_POS (0)
#define SYS_ANA_ANA_REG13_RTCSEL_MASK (0xffffffff)

#ifdef __cplusplus
}
#endif
