
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t maxpooling_6_input[85] = {
    67,   103, -18, -15,  91, 47,  -41,  -79, -80, 49,   -92, -71, 18,  -110, 54,  -95, 60,  72,   10,  85, -43, 16,
    96,   -64, -49, -10,  49, 46,  80,   63,  -52, 117,  -24, -5,  39,  -76,  30,  -55, -85, 63,   -54, 85, 80,  111,
    -107, 43,  115, -58,  28, -14, -113, 75,  -41, 65,   -90, -94, -89, 71,   -90, -18, -59, -124, 12,  51, -68, 47,
    118,  29,  55,  -117, 29, 23,  41,   94,  76,  -118, 43,  108, 36,  2,    -27, 123, 125, 17,   -45};
