
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const q15_t dw_int16xint8_fast_spill_output_ref[120] = {
    -5888, 8750,  2895,   -9994,  -470,   -2580, 17078, 6822,   -10498, -11922, 17669, 26281,  1846,   19513,  11949,
    18214, 15376, 13969,  22518,  6960,   28825, 29772, -12730, -7248,  -28380, 20189, 4576,   3856,   -20204, 834,
    6690,  12891, -2490,  -6287,  -23380, 15013, 285,   -202,   -9748,  -23718, 6175,  -11713, 10610,  -191,   -2242,
    5700,  8904,  4077,   -19634, -26428, 6195,  -8093, -14671, 853,    2665,   7506,  21840,  -11050, -14074, -3101,
    22643, 10804, 9045,   -2169,  -19386, 12893, 18828, 23020,  7640,   -8641,  4511,  2052,   7052,   -286,   758,
    18775, 7717,  -12786, -4000,  6207,   -1655, 3785,  8302,   6441,   12601,  5587,  1522,   -3667,  -7813,  -30000,
    -3990, 16831, -10719, -24311, -6336,  6501,  -1578, 1116,   -12341, -11714, 11839, 10377,  16259,  -7221,  -15023,
    18275, 4305,  12295,  -13360, 4947,   17410, 6421,  -5500,  -15376, 13305,  12160, 4451,   610,    -7825,  -19970};
