
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#define DW_INT16XINT8_FAST_STRIDE_OUT_CH 8
#define DW_INT16XINT8_FAST_STRIDE_IN_CH 8
#define DW_INT16XINT8_FAST_STRIDE_INPUT_W 4
#define DW_INT16XINT8_FAST_STRIDE_INPUT_H 4
#define DW_INT16XINT8_FAST_STRIDE_DST_SIZE 64
#define DW_INT16XINT8_FAST_STRIDE_INPUT_SIZE 128
#define DW_INT16XINT8_FAST_STRIDE_OUT_ACTIVATION_MIN -32768
#define DW_INT16XINT8_FAST_STRIDE_OUT_ACTIVATION_MAX 16000
#define DW_INT16XINT8_FAST_STRIDE_INPUT_BATCHES 2
#define DW_INT16XINT8_FAST_STRIDE_FILTER_X 2
#define DW_INT16XINT8_FAST_STRIDE_FILTER_Y 2
#define DW_INT16XINT8_FAST_STRIDE_STRIDE_X 2
#define DW_INT16XINT8_FAST_STRIDE_STRIDE_Y 2
#define DW_INT16XINT8_FAST_STRIDE_PAD_X 0
#define DW_INT16XINT8_FAST_STRIDE_PAD_Y 0
#define DW_INT16XINT8_FAST_STRIDE_OUTPUT_W 2
#define DW_INT16XINT8_FAST_STRIDE_OUTPUT_H 2
#define DW_INT16XINT8_FAST_STRIDE_CH_MULT 1
#define DW_INT16XINT8_FAST_STRIDE_INPUT_OFFSET 0
#define DW_INT16XINT8_FAST_STRIDE_OUTPUT_OFFSET 0
#define DW_INT16XINT8_FAST_STRIDE_DILATION_X 1
#define DW_INT16XINT8_FAST_STRIDE_DILATION_Y 1
