
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.8.0 as reference.
#pragma once
#include <stdint.h>

const int16_t avgpooling_int16_1_input[18] = {23269,
                                              -14726,
                                              15968,
                                              -32485,
                                              14383,
                                              26655,
                                              -5510,
                                              9514,
                                              15927,
                                              9348,
                                              9806,
                                              -11972,
                                              4272,
                                              -17618,
                                              21518,
                                              -1399,
                                              -5680,
                                              -16677};
