
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const q15_t dw_int16xint8_fast_test_bias_input[128] = {
    26211,  4731,   -22859, 11697,  10585,  11943,  -14100, 26914,  12318,  25865,  21309,  -30278, 16859,
    -22419, -22520, 23316,  -12644, -21341, 12932,  27271,  -29459, 17002,  647,    30644,  15139,  24653,
    -10887, 642,    -23018, 3393,   22354,  32020,  29579,  11325,  18381,  -20003, 31111,  12606,  19290,
    2790,   10494,  -1174,  -11692, 24562,  -25732, 21589,  -30063, 19020,  1608,   -6749,  -17825, 10124,
    23526,  7341,   -6651,  -1250,  -4309,  16248,  9321,   23417,  18692,  -4153,  13447,  27760,  -32343,
    75,     -1304,  -18492, -24433, -25032, 21082,  -6482,  7326,   23924,  -15933, -2659,  16010,  23379,
    20839,  -20544, -18458, -9760,  -12286, -19623, -22278, 830,    201,    -1896,  -10303, 2078,   30440,
    -32037, 30788,  -3003,  -27929, 9405,   11778,  -18353, -21242, -29960, -12386, -29785, -17179, -4808,
    11624,  -15088, 4166,   28562,  -27870, 27660,  17064,  -10298, 12385,  8103,   7981,   -20447, -11094,
    11437,  14070,  17755,  -24940, -31608, 31029,  11698,  -27766, 30068,  -11221, -29017};
