
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const q15_t dw_int16xint8_fast_test_bias_output_ref[72] = {
    -8682,  -15863, 1159,  -11937, 10286,  -9621,  -15424, -7734,  -9691, -17000, 1962,   -2115,  -11569, -4403,  4200,
    -10421, 1505,   -3791, 5922,   -7826,  888,    -17000, 17309,  -7826, 13275,  -13579, 5015,   -1902,  -12121, -7118,
    -76,    -1351,  -4281, -17000, 19135,  -2607,  18618,  -17000, 1027,  899,    3107,   -7082,  2951,   285,    -7891,
    -13555, -1065,  -4924, -4919,  -7022,  13589,  -8487,  18954,  8497,  18572,  -782,   -11946, -13100, 7578,   -5467,
    -551,   -17000, 8205,  -1650,  -10352, -12264, -10706, -10431, 20654, -4597,  -10298, -6300};
