/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <Test1RPCBaseDS.h>

bool_t
xdr_TEST1_VOID(XDR *xdrs, TEST1_VOID *objp)
{
	if (!xdr_long(xdrs, objp)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_TEST1_RPC_AFE_INIT_CONFIG(XDR *xdrs, TEST1_RPC_AFE_INIT_CONFIG *objp)
{
	if (!xdr_int(xdrs, &objp->rate)) {
		return FALSE;
	}
	if (!xdr_int(xdrs, &objp->frame_length)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_TEST1_RPC_AFE_PROCESS_BUFS(XDR *xdrs, TEST1_RPC_AFE_PROCESS_BUFS *objp)
{
	if (!xdr_long(xdrs, &objp->mic_1)) {
		return FALSE;
	}
	if (!xdr_long(xdrs, &objp->mic_2)) {
		return FALSE;
	}
	if (!xdr_long(xdrs, &objp->ref)) {
		return FALSE;
	}
	if (!xdr_long(xdrs, &objp->mic_out)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_TEST1_RPC_ERROR(XDR *xdrs, TEST1_RPC_ERROR *objp)
{
	if (!xdr_long(xdrs, &objp->instance_id)) {
		return FALSE;
	}
	if (!xdr_long(xdrs, &objp->TEST1_error)) {
		return FALSE;
	}
	return TRUE;
}
