/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST2RPCBASEDS_DATA_H_RPCGEN
#define _TEST2RPCBASEDS_DATA_H_RPCGEN

#include <RPCBaseDS.h>

struct TEST2_RPC_INSTANCE {
	long streaming_ins;
	long recognizer_ins;
};
typedef struct TEST2_RPC_INSTANCE TEST2_RPC_INSTANCE;

struct TEST2_RPCRES_INIT {
	HRESULT rpc_result;
	TEST2_RPC_INSTANCE instance;
};
typedef struct TEST2_RPCRES_INIT TEST2_RPCRES_INIT;

struct TEST2_RPC_MIC_DATA {
	uint32_t data_addr;
	long length;
};
typedef struct TEST2_RPC_MIC_DATA TEST2_RPC_MIC_DATA;

struct TEST2_RPC_STREAMING_RESULT {
	long uv_ret;
	uint32_t out_data_addr;
	long vad_flag;
};
typedef struct TEST2_RPC_STREAMING_RESULT TEST2_RPC_STREAMING_RESULT;

struct TEST2_RPCRES_STREAMING_PROCESS {
	HRESULT rpc_result;
	TEST2_RPC_STREAMING_RESULT streaming_ret;
};
typedef struct TEST2_RPCRES_STREAMING_PROCESS TEST2_RPCRES_STREAMING_PROCESS;

struct TEST2_RPC_RECOGNIZER_INSTANCE {
	long instance_id;
};
typedef struct TEST2_RPC_RECOGNIZER_INSTANCE TEST2_RPC_RECOGNIZER_INSTANCE;

struct TEST2_RPC_RECOGNIZER_RESULT {
	long uv_ret;
	long word_id;
	float confidence;
};
typedef struct TEST2_RPC_RECOGNIZER_RESULT TEST2_RPC_RECOGNIZER_RESULT;

struct TEST2_RPCRES_RECOGNIZER_PROCESS {
	HRESULT rpc_result;
	TEST2_RPC_RECOGNIZER_RESULT recognizer_ret;
};
typedef struct TEST2_RPCRES_RECOGNIZER_PROCESS TEST2_RPCRES_RECOGNIZER_PROCESS;

struct TEST2_RPC_ERROR_STATE {
	long type;
	long state;
};
typedef struct TEST2_RPC_ERROR_STATE TEST2_RPC_ERROR_STATE;

#endif /* !_TEST2RPCBASEDS_DATA_H_RPCGEN */
