
.insert <RPCBaseDS.h>

struct TEST2_RPC_INSTANCE
{
	long streaming_ins;
	long recognizer_ins;
};

struct TEST2_RPCRES_INIT
{
	HRESULT rpc_result;
	TEST2_RPC_INSTANCE instance;
};

struct TEST2_RPC_MIC_DATA
{
	uint32_t data_addr;
	long length;
};

struct TEST2_RPC_STREAMING_RESULT
{
	long uv_ret;
	uint32_t out_data_addr;
	long vad_flag;
};

struct TEST2_RPCRES_STREAMING_PROCESS
{
	HRESULT rpc_result;
	TEST2_RPC_STREAMING_RESULT streaming_ret;
};

struct TEST2_RPC_RECOGNIZER_INSTANCE
{
	long instance_id;
};

struct TEST2_RPC_RECOGNIZER_RESULT
{
	long uv_ret;
	long word_id;
	float confidence;
};

struct TEST2_RPCRES_RECOGNIZER_PROCESS
{
	HRESULT rpc_result;
	TEST2_RPC_RECOGNIZER_RESULT recognizer_ret;
};

struct TEST2_RPC_ERROR_STATE
{
	long type;
	long state;
};