/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST1RPC_AGENT_H_RPCGEN
#define _TEST1RPC_AGENT_H_RPCGEN

#include "rpc_struct.h"

#include "Test1RPC_Agent_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <RPCBaseDS.h>
#include <Test1RPCBaseDS.h>

#define TEST1_AGENT 2012
#define VERSION 0

struct REG_STRUCT *TEST1_AGENT_0_register(struct REG_STRUCT *rnode);
#define TEST1_RPC_ToSystem_ErrorStatus 1
extern  HRESULT *TEST1_RPC_ToSystem_ErrorStatus_0(TEST1_RPC_ERROR *, CLNT_STRUCT *);
extern  HRESULT *TEST1_RPC_ToSystem_ErrorStatus_0_svc(TEST1_RPC_ERROR *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_TEST1_RPC_ToSystem_ErrorStatus_0_svc)(TEST1_RPC_ERROR *, RPC_STRUCT *, HRESULT *);

#ifdef __cplusplus
}
#endif

#endif /* !_TEST1RPC_AGENT_H_RPCGEN */
