/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST1RPC_SYSTEM_DATA_H_RPCGEN
#define _TEST1RPC_SYSTEM_DATA_H_RPCGEN

#include <RPCBaseDS.h>
#include <Test1RPCBaseDS.h>

#endif /* !_TEST1RPC_SYSTEM_DATA_H_RPCGEN */
