.insert <RPCBaseDS.h>
.insert <Test1RPCBaseDS.h>

program TEST1_SYSTEM {
	version VERSION {
		HRESULT TEST1_RPC_ToAgent_AFE_Init(TEST1_RPC_AFE_INIT_CONFIG) = 1;
		HRESULT TEST1_RPC_ToAgent_AFE_Process(TEST1_RPC_AFE_PROCESS_BUFS bufs) = 2;
        TEST1_VOID TEST1_RPC_ToAgent_AFE_Destroy(TEST1_VOID) = 3;
	} = 0;
} = 2011;

