/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST2RPC_AGENT_H_RPCGEN
#define _TEST2RPC_AGENT_H_RPCGEN

#include "rpc_struct.h"

#include "Test2RPC_Agent_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <RPCBaseDS.h>
#include <Test2RPCBaseDS.h>

#define TEST2_AGENT 3002
#define VERSION 0

struct REG_STRUCT *TEST2_AGENT_0_register(struct REG_STRUCT *rnode);
#define TEST2_RPC_ToSystem_Streaming_Callback 1
extern  HRESULT *TEST2_RPC_ToSystem_Streaming_Callback_0(TEST2_RPC_STREAMING_RESULT *, CLNT_STRUCT *);
extern  HRESULT *TEST2_RPC_ToSystem_Streaming_Callback_0_svc(TEST2_RPC_STREAMING_RESULT *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_TEST2_RPC_ToSystem_Streaming_Callback_0_svc)(TEST2_RPC_STREAMING_RESULT *, RPC_STRUCT *, HRESULT *);
#define TEST2_RPC_ToSystem_Recognizer_Callback 2
extern  HRESULT *TEST2_RPC_ToSystem_Recognizer_Callback_0(TEST2_RPC_RECOGNIZER_RESULT *, CLNT_STRUCT *);
extern  HRESULT *TEST2_RPC_ToSystem_Recognizer_Callback_0_svc(TEST2_RPC_RECOGNIZER_RESULT *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_TEST2_RPC_ToSystem_Recognizer_Callback_0_svc)(TEST2_RPC_RECOGNIZER_RESULT *, RPC_STRUCT *, HRESULT *);
#define TEST2_RPC_ToSystem_Error 3
extern  HRESULT *TEST2_RPC_ToSystem_Error_0(TEST2_RPC_ERROR_STATE *, CLNT_STRUCT *);
extern  HRESULT *TEST2_RPC_ToSystem_Error_0_svc(TEST2_RPC_ERROR_STATE *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_TEST2_RPC_ToSystem_Error_0_svc)(TEST2_RPC_ERROR_STATE *, RPC_STRUCT *, HRESULT *);

#ifdef __cplusplus
}
#endif

#endif /* !_TEST2RPC_AGENT_H_RPCGEN */
