/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST1RPCBASEDS_DATA_H_RPCGEN
#define _TEST1RPCBASEDS_DATA_H_RPCGEN


typedef long TEST1_VOID;

struct TEST1_RPC_AFE_INIT_CONFIG {
	int rate;
	int frame_length;
};
typedef struct TEST1_RPC_AFE_INIT_CONFIG TEST1_RPC_AFE_INIT_CONFIG;

struct TEST1_RPC_AFE_PROCESS_BUFS {
	long mic_1;
	long mic_2;
	long ref;
	long mic_out;
};
typedef struct TEST1_RPC_AFE_PROCESS_BUFS TEST1_RPC_AFE_PROCESS_BUFS;

struct TEST1_RPC_ERROR {
	long instance_id;
	long TEST1_error;
};
typedef struct TEST1_RPC_ERROR TEST1_RPC_ERROR;

#endif /* !_TEST1RPCBASEDS_DATA_H_RPCGEN */
