.insert <RPCBaseDS.h>
.insert <Test1RPCBaseDS.h>

program TEST1_AGENT {
  version VERSION {

 /** General **/
  	HRESULT		TEST1_RPC_ToSystem_ErrorStatus(TEST1_RPC_ERROR) = 1;
  }=0;
}=2012;

