/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST2RPC_SYSTEM_DATA_H_RPCGEN
#define _TEST2RPC_SYSTEM_DATA_H_RPCGEN

#include <RPCBaseDS.h>
#include <Test2RPCBaseDS.h>

#endif /* !_TEST2RPC_SYSTEM_DATA_H_RPCGEN */
