
/*.insert <rpc_api.h>*/

typedef long TEST1_VOID;

struct TEST1_RPC_AFE_INIT_CONFIG {
	int	rate;
	int frame_length;
};

struct TEST1_RPC_AFE_PROCESS_BUFS {
	long mic_1;
	long mic_2;
	long ref;
	long mic_out;
};

struct TEST1_RPC_ERROR
{
	long instance_id;
	long TEST1_error;
};
