
.insert <RPCBaseDS.h>
.insert <Test2RPCBaseDS.h>

program TEST2_AGENT {
	version VERSION {
		/** General **/
		HRESULT TEST2_RPC_ToSystem_Streaming_Callback(TEST2_RPC_STREAMING_RESULT) = 1;
		HRESULT TEST2_RPC_ToSystem_Recognizer_Callback(TEST2_RPC_RECOGNIZER_RESULT) = 2;
		HRESULT TEST2_RPC_ToSystem_Error(TEST2_RPC_ERROR_STATE) = 3;
	}=0;

}=3002;

