/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST1RPC_SYSTEM_H_RPCGEN
#define _TEST1RPC_SYSTEM_H_RPCGEN

#include "rpc_struct.h"

#include "Test1RPC_System_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <RPCBaseDS.h>
#include <Test1RPCBaseDS.h>

#define TEST1_SYSTEM 2011
#define VERSION 0

struct REG_STRUCT *TEST1_SYSTEM_0_register(struct REG_STRUCT *rnode);
#define TEST1_RPC_ToAgent_AFE_Init 1
extern  HRESULT *TEST1_RPC_ToAgent_AFE_Init_0(TEST1_RPC_AFE_INIT_CONFIG *, CLNT_STRUCT *);
extern  HRESULT *TEST1_RPC_ToAgent_AFE_Init_0_svc(TEST1_RPC_AFE_INIT_CONFIG *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_TEST1_RPC_ToAgent_AFE_Init_0_svc)(TEST1_RPC_AFE_INIT_CONFIG *, RPC_STRUCT *, HRESULT *);
#define TEST1_RPC_ToAgent_AFE_Process 2
extern  HRESULT *TEST1_RPC_ToAgent_AFE_Process_0(TEST1_RPC_AFE_PROCESS_BUFS *, CLNT_STRUCT *);
extern  HRESULT *TEST1_RPC_ToAgent_AFE_Process_0_svc(TEST1_RPC_AFE_PROCESS_BUFS *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_TEST1_RPC_ToAgent_AFE_Process_0_svc)(TEST1_RPC_AFE_PROCESS_BUFS *, RPC_STRUCT *, HRESULT *);
#define TEST1_RPC_ToAgent_AFE_Destroy 3
extern  TEST1_VOID *TEST1_RPC_ToAgent_AFE_Destroy_0(TEST1_VOID *, CLNT_STRUCT *);
extern  TEST1_VOID *TEST1_RPC_ToAgent_AFE_Destroy_0_svc(TEST1_VOID *, RPC_STRUCT *, TEST1_VOID *);
extern  TEST1_VOID *(*p_TEST1_RPC_ToAgent_AFE_Destroy_0_svc)(TEST1_VOID *, RPC_STRUCT *, TEST1_VOID *);

#ifdef __cplusplus
}
#endif

#endif /* !_TEST1RPC_SYSTEM_H_RPCGEN */
