
.insert <RPCBaseDS.h>
.insert <Test2RPCBaseDS.h>

program TEST2_SYSTEM {
	version VERSION {
		TEST2_RPCRES_INIT TEST2_RPC_ToAgent_Init(TEST2_RPC_MIC_DATA) = 1;
		HRESULT TEST2_RPC_ToAgent_Release(TEST2_RPC_INSTANCE) = 2;

		HRESULT TEST2_RPC_ToAgent_Streaming_Process(TEST2_RPC_INSTANCE) = 3;
		HRESULT TEST2_RPC_ToAgent_Recognizer_Process(TEST2_RPC_INSTANCE) = 4;

		HRESULT TEST2_RPC_ToAgent_Sync_Mic_Data(TEST2_RPC_MIC_DATA) = 5;
	} = 0;

} = 3001;

