
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const q7_t kernel1x1_input[105] = {
    -124, -107, -35, 87,  -25, 72,   47,  -104, 36,   87,  -114, -23, -69, -66,  86,  22, -14, -94, -5,  -114, 18,
    100,  1,    90,  -7,  -76, -43,  75,  -53,  -112, 92,  74,   121, 37,  43,   -11, 95, 80,  -72, -4,  14,   -119,
    3,    -68,  79,  29,  63,  -105, 43,  49,   -5,   107, -68,  115, -33, 55,   75,  52, 116, -94, -31, 70,   98,
    10,   49,   -50, 104, -95, 24,   102, -106, -40,  57,  -101, 66,  62,  73,   -10, 88, 56,  -71, -85, 126,  -50,
    -72,  -77,  -22, 108, -13, -80,  -84, -25,  104,  -16, -32,  31,  70,  -101, 78,  0,  -55, -98, -2,  60,   77};
