/****************************************************************************
 *
 * Copyright 2021 Samsung Electronics All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 *
 ****************************************************************************/
 
SECLINK_RES_MAP_TABLE(SECLINK_OK, HAL_SUCCESS)
SECLINK_RES_MAP_TABLE(SECLINK_ERROR, HAL_FAIL)
SECLINK_RES_MAP_TABLE(SECLINK_INVALID_ARGS, HAL_INVALID_ARGS)
SECLINK_RES_MAP_TABLE(SECLINK_INVALID_REQUEST, HAL_INVALID_REQUEST)
SECLINK_RES_MAP_TABLE(SECLINK_INVALID_SLOT_RANGE, HAL_INVALID_SLOT_RANGE)
SECLINK_RES_MAP_TABLE(SECLINK_INVALID_SLOT_TYPE, HAL_INVALID_SLOT_TYPE)
SECLINK_RES_MAP_TABLE(SECLINK_EMPTY_SLOT, HAL_EMPTY_SLOT)
SECLINK_RES_MAP_TABLE(SECLINK_BAD_KEY, HAL_BAD_KEY)
SECLINK_RES_MAP_TABLE(SECLINK_BAD_KEY_PAIR, HAL_BAD_KEY_PAIR)
SECLINK_RES_MAP_TABLE(SECLINK_BAD_CERT, HAL_BAD_CERT)
SECLINK_RES_MAP_TABLE(SECLINK_BAD_CERTKEY_PAIR, HAL_BAD_CERTKEY_PAIR)
SECLINK_RES_MAP_TABLE(SECLINK_NOT_ENOUGH_MEMORY, HAL_NOT_ENOUGH_MEMORY)
SECLINK_RES_MAP_TABLE(SECLINK_ALLOC_FAIL, HAL_ALLOC_FAIL)
SECLINK_RES_MAP_TABLE(SECLINK_KEY_IN_USE, HAL_KEY_IN_USE)
SECLINK_RES_MAP_TABLE(SECLINK_CERT_IN_USE, HAL_CERT_IN_USE)
SECLINK_RES_MAP_TABLE(SECLINK_DATA_IN_USE, HAL_DATA_IN_USE)
SECLINK_RES_MAP_TABLE(SECLINK_NOT_SUPPORTED, HAL_NOT_SUPPORTED)
SECLINK_RES_MAP_TABLE(SECLINK_NOT_IMPLEMENTED, HAL_NOT_IMPLEMENTED)
SECLINK_RES_MAP_TABLE(SECLINK_BUSY, HAL_BUSY)
SECLINK_RES_MAP_TABLE(SECLINK_NOT_INITIALIZED, HAL_NOT_INITIALIZED)
