
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t dw_int16xint8_mult4_input[40] = {
    -17485, 21819, -26312, -14446, 32326,  26482,  -4390, -18621, -32186, 15037,  -7461,  30312,  -18990, 15605,
    -20064, 3712,  -25567, -22216, -7666,  4861,   30918, -1954,  14950,  6892,   -21628, -10369, 10901,  31979,
    -24233, 14297, 15444,  -30175, -32061, -29227, 28826, -9789,  5445,   -32022, 19913,  9312};
