
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t dw_int16xint8_mult4_weights[96] = {
    -87, 4,   50,  43,   8,   -33, -86, 75,   -15, -119, -56, 116, 82,   -39, -127, 47,   81,   0,    -104, -8,
    9,   -27, -7,  127,  -72, -95, -23, -41,  127, 57,   11,  75,  -40,  13,  -69,  -102, -121, -110, 4,    92,
    29,  25,  -42, -100, 18,  127, 127, 62,   -46, -127, -28, 118, 33,   -66, 27,   55,   79,   4,    127,  -38,
    -81, 86,  -17, 47,   127, -29, 31,  -127, 13,  -20,  13,  7,   116,  13,  70,   104,  -78,  -72,  -122, -9,
    118, -43, 26,  -127, -48, -63, -65, 85,   110, 113,  -5,  40,  -115, 34,  23,   -20};
