
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_1_x_n_3_output_ref[36] = {87,  -76, -75, 25,  19,  -78, 11,  -88, -88, -20, 28,  -88,
                                          107, -15, -1,  29,  -88, -88, -18, -51, -88, 45,  -64, -88,
                                          -16, -88, -88, 114, -88, -74, 38,  -30, -88, 21,  29,  -76};
