
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_1_x_n_2_weights[80] = {
    48,  -104, -93, -32,  127,  -30, 68,  -42, -106, -104, 43,   -51,  115,  38,  104,  0,   -52,  5,   118, 127,
    43,  -14,  -85, -119, 18,   -58, -94, 34,  80,   115,  5,    61,   17,   127, -107, 20,  34,   -16, -89, 11,
    -34, -39,  -55, 122,  -121, 11,  26,  101, 97,   25,   3,    -23,  -127, -35, 66,   -57, -100, 37,  -78, 55,
    7,   65,   -86, -47,  8,    120, 80,  0,   -29,  -124, -109, -102, -85,  115, -127, -71, -54,  -73, -10, -89};
