
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t maxpooling_1_input[135] = {
    78,   64,  103,  10,   4,    -53, 75,   11,   108,  122, -73, -83,  -121, 70,   -7,   -47,  -9,  -100, 18,   4,
    -124, 4,   -6,   -11,  -54,  -75, -102, 60,   -119, 34,  -78, 74,   -41,  -117, -40,  11,   -74, -23,  32,   -79,
    -66,  70,  -122, 83,   60,   65,  -73,  -106, -83,  11,  -82, -75,  18,   100,  81,   -38,  20,  -40,  102,  4,
    121,  44,  -26,  -120, 126,  120, -107, 54,   16,   -97, 30,  -59,  -97,  4,    -121, 76,   -22, -21,  -124, -109,
    73,   15,  -60,  74,   111,  121, -88,  -86,  65,   117, 22,  -38,  -94,  -86,  29,   -115, -29, -101, -34,  -80,
    -44,  -74, 110,  98,   -124, 109, -16,  -108, 94,   -93, 106, -57,  -123, -102, 87,   29,   -26, 89,   -8,   114,
    -72,  -7,  56,   0,    -48,  -41, -33,  -28,  26,   89,  121, -103, 9,    98,   58};
