
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_2x2_dilation_5x5_input_input[50] = {
    -102, -14, 21,   -74,  -119, 89,  39,   55,  -84,  -51,  -44, -33, -92, 2,   85,  -8,  -11,
    56,   -58, -122, 68,   91,   -65, -77,  -79, 52,   124,  82,  19,  22,  -58, -54, -96, 87,
    49,   -84, -99,  -108, 15,   25,  -103, 36,  -119, -128, 107, -69, -72, -52, 55,  -120};
