// Copyright 2022-2024 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//This is a generated file, don't modify it!

#pragma once


#define GEN_SECURITY_DEV_AON_IS_SECURE    0
#define GEN_SECURITY_DEV_AON_IS_PRIVILEGE    0
#define GEN_SECURITY_DEV_APB_WDT_IS_SECURE    0
#define GEN_SECURITY_DEV_APB_WDT_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_BTDM_IS_SECURE    0
#define GEN_SECURITY_DEV_BTDM_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_BTDM_M_IS_SECURE    0
#define GEN_SECURITY_DEV_BTDM_M_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_CKMN_IS_SECURE    0
#define GEN_SECURITY_DEV_CKMN_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_DMA0_IS_SECURE    0
#define GEN_SECURITY_DEV_DMA0_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_FLASH_IS_SECURE    0
#define GEN_SECURITY_DEV_FLASH_IS_PRIVILEGE    0
#define GEN_SECURITY_DEV_HSU_M_IS_SECURE    0
#define GEN_SECURITY_DEV_HSU_M_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_I2C0_IS_SECURE    0
#define GEN_SECURITY_DEV_I2C0_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_I2C1_IS_SECURE    0
#define GEN_SECURITY_DEV_I2C1_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_I2S_IS_SECURE    0
#define GEN_SECURITY_DEV_I2S_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_I2S0_IS_SECURE    0
#define GEN_SECURITY_DEV_I2S0_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_I2S1_IS_SECURE    0
#define GEN_SECURITY_DEV_I2S1_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_I2S2_IS_SECURE    0
#define GEN_SECURITY_DEV_I2S2_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_LA_IS_SECURE    0
#define GEN_SECURITY_DEV_LA_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_LA_M_IS_SECURE    0
#define GEN_SECURITY_DEV_LA_M_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_LED_IS_SECURE    0
#define GEN_SECURITY_DEV_LED_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_MAC_IS_SECURE    0
#define GEN_SECURITY_DEV_MAC_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_MAC_M_IS_SECURE    0
#define GEN_SECURITY_DEV_MAC_M_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_THREAD_AHB_IS_SECURE    0
#define GEN_SECURITY_DEV_THREAD_AHB_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_RFCTRL_APB_CHK_IS_SECURE    0
#define GEN_SECURITY_DEV_RFCTRL_APB_CHK_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_RFCTRL_AHB_RCBEKEN_IS_SECURE    0
#define GEN_SECURITY_DEV_RFCTRL_AHB_RCBEKEN_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_MCHECK_IS_SECURE    0
#define GEN_SECURITY_DEV_MCHECK_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_MOD_IS_SECURE    0
#define GEN_SECURITY_DEV_MOD_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_PPRO_MPC_IS_SECURE    0
#define GEN_SECURITY_DEV_PPRO_MPC_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_PRAM_IS_SECURE    0
#define GEN_SECURITY_DEV_PRAM_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_PWM0_IS_SECURE    0
#define GEN_SECURITY_DEV_PWM0_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_PWM1_IS_SECURE    0
#define GEN_SECURITY_DEV_PWM1_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_QSPI1_IS_SECURE    0
#define GEN_SECURITY_DEV_QSPI1_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_REG_IS_SECURE    0
#define GEN_SECURITY_DEV_REG_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_SADC_IS_SECURE    0
#define GEN_SECURITY_DEV_SADC_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_SCAL1_IS_SECURE    0
#define GEN_SECURITY_DEV_SCAL1_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_SDIO_IS_SECURE    0
#define GEN_SECURITY_DEV_SDIO_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_SPI0_IS_SECURE    0
#define GEN_SECURITY_DEV_SPI0_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_SPI1_IS_SECURE    0
#define GEN_SECURITY_DEV_SPI1_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_SYS_IS_SECURE    0
#define GEN_SECURITY_DEV_SYS_IS_PRIVILEGE    0
#define GEN_SECURITY_DEV_TIMER0_IS_SECURE    0
#define GEN_SECURITY_DEV_TIMER0_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_TIMER1_IS_SECURE    0
#define GEN_SECURITY_DEV_TIMER1_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_TRNG_IS_SECURE    0
#define GEN_SECURITY_DEV_TRNG_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_TRXCHK_M_IS_SECURE    0
#define GEN_SECURITY_DEV_TRXCHK_M_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_UART0_IS_SECURE    0
#define GEN_SECURITY_DEV_UART0_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_UART1_IS_SECURE    0
#define GEN_SECURITY_DEV_UART1_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_UART2_IS_SECURE    0
#define GEN_SECURITY_DEV_UART2_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_UART3_IS_SECURE    0
#define GEN_SECURITY_DEV_UART3_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_USB_IS_SECURE    0
#define GEN_SECURITY_DEV_USB_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_XVR_IS_SECURE    0
#define GEN_SECURITY_DEV_XVR_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_RFCTRL_AHB_CHK_IS_SECURE    0
#define GEN_SECURITY_DEV_RFCTRL_AHB_CHK_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO0_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO0_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO1_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO1_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO2_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO2_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO3_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO3_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO4_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO4_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO5_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO5_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO6_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO6_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO7_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO7_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO8_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO8_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO9_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO9_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO10_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO10_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO11_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO11_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO12_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO12_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO13_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO13_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO14_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO14_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO15_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO15_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO16_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO16_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO17_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO17_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO18_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO18_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO19_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO19_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO20_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO20_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO21_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO21_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO22_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO22_IS_PRIVILEGE    1
#define GEN_SECURITY_DEV_GPIO23_IS_SECURE    0
#define GEN_SECURITY_DEV_GPIO23_IS_PRIVILEGE    1

#define DEV_IS_SECURE(dev)    GEN_SECURITY_DEV_##dev##_IS_SECURE
#define DEV_ID_IS_SECURE(dev,id)    GEN_SECURITY_DEV_##dev##id##_IS_SECURE
#define DEV_IS_PRIVILEGE(dev)    GEN_SECURITY_DEV_##dev##_IS_PRIVILEGE
#define DEV_ID_IS_PRIVILEGE(dev, id)    GEN_SECURITY_DEV_##dev##id##_IS_PRIVILEGE
