// Copyright 2022-2024 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//This is a generated file, don't modify it!

#pragma once


#include "security.h"
#define KB(size)                                      ((size) << 10)
#define MB(size)                                      ((size) << 20)

#define CONFIG_TFM_S_JUMP_TO_TFM_NS                   0
#define CONFIG_TFM_S_JUMP_TO_CPU0_APP                 1
#define CPU_VECTOR_ALIGN_SZ                           512
#define CONFIG_BL1_CONTROL_PHY_PARTITION_OFFSET       0x0
#define CONFIG_BL1_CONTROL_PHY_PARTITION_SIZE         0x1000

#define CONFIG_BOOT_FLAG_PHY_PARTITION_OFFSET         0x1000
#define CONFIG_BOOT_FLAG_PHY_PARTITION_SIZE           0x1000

#define CONFIG_PARTITION_PHY_PARTITION_OFFSET         0x2000
#define CONFIG_PARTITION_PHY_PARTITION_SIZE           0x1000

#define CONFIG_PRIMARY_MANIFEST_PHY_PARTITION_OFFSET  0x3000
#define CONFIG_PRIMARY_MANIFEST_PHY_PARTITION_SIZE    0x1000

#define CONFIG_BL2_PHY_PARTITION_OFFSET               0x4000
#define CONFIG_BL2_PHY_PARTITION_SIZE                 0x13000
#define CONFIG_BL2_PHY_CODE_START                     0x4000
#define CONFIG_BL2_VIRTUAL_PARTITION_SIZE             0x13000
#define CONFIG_BL2_VIRTUAL_CODE_START                 0x4000
#define CONFIG_BL2_VIRTUAL_CODE_SIZE                  0x13000

#define CONFIG_SYS_ITS_PHY_PARTITION_OFFSET           0x17000
#define CONFIG_SYS_ITS_PHY_PARTITION_SIZE             0x2000

#define CONFIG_SYS_PS_PHY_PARTITION_OFFSET            0x19000
#define CONFIG_SYS_PS_PHY_PARTITION_SIZE              0x2000

#define CONFIG_SS_PHY_PARTITION_OFFSET                0x1b000
#define CONFIG_SS_PHY_PARTITION_SIZE                  0x85000

#define CONFIG_PRIMARY_TFM_S_PHY_PARTITION_OFFSET     0xa0000
#define CONFIG_PRIMARY_TFM_S_PHY_PARTITION_SIZE       0x30000
#define CONFIG_PRIMARY_TFM_S_PHY_CODE_START           0xa1000
#define CONFIG_PRIMARY_TFM_S_PHY_HDR_SIZE             0x1000
#define CONFIG_PRIMARY_TFM_S_PHY_TAIL_SIZE            0x1000
#define CONFIG_PRIMARY_TFM_S_VIRTUAL_PARTITION_SIZE   0x30000
#define CONFIG_PRIMARY_TFM_S_VIRTUAL_CODE_START       0xa1000
#define CONFIG_PRIMARY_TFM_S_VIRTUAL_CODE_SIZE        0x2f000

#define CONFIG_PRIMARY_CPU0_APP_PHY_PARTITION_OFFSET  0xd0000
#define CONFIG_PRIMARY_CPU0_APP_PHY_PARTITION_SIZE    0x166000
#define CONFIG_PRIMARY_CPU0_APP_PHY_CODE_START        0xd0000
#define CONFIG_PRIMARY_CPU0_APP_PHY_HDR_SIZE          0x1000
#define CONFIG_PRIMARY_CPU0_APP_PHY_TAIL_SIZE         0x1000
#define CONFIG_PRIMARY_CPU0_APP_VIRTUAL_PARTITION_SIZE 0x166000
#define CONFIG_PRIMARY_CPU0_APP_VIRTUAL_CODE_START    0xd0000
#define CONFIG_PRIMARY_CPU0_APP_VIRTUAL_CODE_SIZE     0x166000

#define CONFIG_PRIMARY_ALL_PHY_PARTITION_OFFSET       0xa0000
#define CONFIG_PRIMARY_ALL_PHY_PARTITION_SIZE         0x196000
#define CONFIG_PRIMARY_ALL_PHY_CODE_START             0xa1000
#define CONFIG_PRIMARY_ALL_PHY_HDR_SIZE               0x1000
#define CONFIG_PRIMARY_ALL_PHY_TAIL_SIZE              0x1000
#define CONFIG_PRIMARY_ALL_VIRTUAL_PARTITION_SIZE     0x196000
#define CONFIG_PRIMARY_ALL_VIRTUAL_CODE_START         0xa1000
#define CONFIG_PRIMARY_ALL_VIRTUAL_CODE_SIZE          0x193000

#define CONFIG_COMMON_PHY_PARTITION_OFFSET            0x236000
#define CONFIG_COMMON_PHY_PARTITION_SIZE              0x100000

#define CONFIG_APP1_PHY_PARTITION_OFFSET              0x336000
#define CONFIG_APP1_PHY_PARTITION_SIZE                0x60000

#define CONFIG_APP2_PHY_PARTITION_OFFSET              0x396000
#define CONFIG_APP2_PHY_PARTITION_SIZE                0x20000

#define CONFIG_SECONDARY_TFM_S_PHY_PARTITION_OFFSET   0x3b6000
#define CONFIG_SECONDARY_TFM_S_PHY_PARTITION_SIZE     0x30000
#define CONFIG_SECONDARY_TFM_S_PHY_CODE_START         0x3b7000
#define CONFIG_SECONDARY_TFM_S_PHY_HDR_SIZE           0x1000
#define CONFIG_SECONDARY_TFM_S_PHY_TAIL_SIZE          0x1000
#define CONFIG_SECONDARY_TFM_S_VIRTUAL_PARTITION_SIZE 0x30000
#define CONFIG_SECONDARY_TFM_S_VIRTUAL_CODE_START     0x3b7000
#define CONFIG_SECONDARY_TFM_S_VIRTUAL_CODE_SIZE      0x2f000

#define CONFIG_SECONDARY_CPU0_APP_PHY_PARTITION_OFFSET 0x3e6000
#define CONFIG_SECONDARY_CPU0_APP_PHY_PARTITION_SIZE  0x166000
#define CONFIG_SECONDARY_CPU0_APP_PHY_CODE_START      0x3e6000
#define CONFIG_SECONDARY_CPU0_APP_PHY_HDR_SIZE        0x1000
#define CONFIG_SECONDARY_CPU0_APP_PHY_TAIL_SIZE       0x1000
#define CONFIG_SECONDARY_CPU0_APP_VIRTUAL_PARTITION_SIZE 0x166000
#define CONFIG_SECONDARY_CPU0_APP_VIRTUAL_CODE_START  0x3e6000
#define CONFIG_SECONDARY_CPU0_APP_VIRTUAL_CODE_SIZE   0x166000

#define CONFIG_SECONDARY_ALL_PHY_PARTITION_OFFSET     0x3b6000
#define CONFIG_SECONDARY_ALL_PHY_PARTITION_SIZE       0x196000
#define CONFIG_SECONDARY_ALL_PHY_CODE_START           0x3b7000
#define CONFIG_SECONDARY_ALL_PHY_HDR_SIZE             0x1000
#define CONFIG_SECONDARY_ALL_PHY_TAIL_SIZE            0x1000
#define CONFIG_SECONDARY_ALL_VIRTUAL_PARTITION_SIZE   0x30000
#define CONFIG_SECONDARY_ALL_VIRTUAL_CODE_START       0x3b7000
#define CONFIG_SECONDARY_ALL_VIRTUAL_CODE_SIZE        0x193000

#define CONFIG_COMMON_B_PHY_PARTITION_OFFSET          0x54c000
#define CONFIG_COMMON_B_PHY_PARTITION_SIZE            0x100000

#define CONFIG_APP1_B_PHY_PARTITION_OFFSET            0x64c000
#define CONFIG_APP1_B_PHY_PARTITION_SIZE              0x60000

#define CONFIG_APP2_B_PHY_PARTITION_OFFSET            0x6ac000
#define CONFIG_APP2_B_PHY_PARTITION_SIZE              0x20000

#define CONFIG_USERFS_PHY_PARTITION_OFFSET            0x6cc000
#define CONFIG_USERFS_PHY_PARTITION_SIZE              0x80000

#define CONFIG_USRCONFIG_PHY_PARTITION_OFFSET         0x74c000
#define CONFIG_USRCONFIG_PHY_PARTITION_SIZE           0x19000

#define CONFIG_SYSTEM_DATA_PHY_PARTITION_OFFSET       0x765000
#define CONFIG_SYSTEM_DATA_PHY_PARTITION_SIZE         0x2000

#define CONFIG_RESERVED_PHY_PARTITION_OFFSET          0x767000
#define CONFIG_RESERVED_PHY_PARTITION_SIZE            0x88f000

#define CONFIG_RF_PHY_PARTITION_OFFSET                0xff6000
#define CONFIG_RF_PHY_PARTITION_SIZE                  0x1000

#define CONFIG_NET_PHY_PARTITION_OFFSET               0xff7000
#define CONFIG_NET_PHY_PARTITION_SIZE                 0x1000

#define CONFIG_EASYFLASH_PHY_PARTITION_OFFSET         0xff8000
#define CONFIG_EASYFLASH_PHY_PARTITION_SIZE           0x6000

#define CONFIG_BOOTPARAM_PHY_PARTITION_OFFSET         0xffe000
#define CONFIG_BOOTPARAM_PHY_PARTITION_SIZE           0x2000

#define PARTITION_MAP { \
    {"bl1_control", CONFIG_BL1_CONTROL_PHY_PARTITION_OFFSET, CONFIG_BL1_CONTROL_PHY_PARTITION_SIZE}, \
    {"boot_flag", CONFIG_BOOT_FLAG_PHY_PARTITION_OFFSET, CONFIG_BOOT_FLAG_PHY_PARTITION_SIZE}, \
    {"partition", CONFIG_PARTITION_PHY_PARTITION_OFFSET, CONFIG_PARTITION_PHY_PARTITION_SIZE}, \
    {"primary_manifest", CONFIG_PRIMARY_MANIFEST_PHY_PARTITION_OFFSET, CONFIG_PRIMARY_MANIFEST_PHY_PARTITION_SIZE}, \
    {"bl2", CONFIG_BL2_PHY_PARTITION_OFFSET, CONFIG_BL2_PHY_PARTITION_SIZE}, \
    {"sys_its", CONFIG_SYS_ITS_PHY_PARTITION_OFFSET, CONFIG_SYS_ITS_PHY_PARTITION_SIZE}, \
    {"sys_ps", CONFIG_SYS_PS_PHY_PARTITION_OFFSET, CONFIG_SYS_PS_PHY_PARTITION_SIZE}, \
    {"ss", CONFIG_SS_PHY_PARTITION_OFFSET, CONFIG_SS_PHY_PARTITION_SIZE}, \
    {"primary_tfm_s", CONFIG_PRIMARY_TFM_S_PHY_PARTITION_OFFSET, CONFIG_PRIMARY_TFM_S_PHY_PARTITION_SIZE}, \
    {"primary_cpu0_app", CONFIG_PRIMARY_CPU0_APP_PHY_PARTITION_OFFSET, CONFIG_PRIMARY_CPU0_APP_PHY_PARTITION_SIZE}, \
    {"primary_all", CONFIG_PRIMARY_ALL_PHY_PARTITION_OFFSET, CONFIG_PRIMARY_ALL_PHY_PARTITION_SIZE}, \
    {"common", CONFIG_COMMON_PHY_PARTITION_OFFSET, CONFIG_COMMON_PHY_PARTITION_SIZE}, \
    {"app1", CONFIG_APP1_PHY_PARTITION_OFFSET, CONFIG_APP1_PHY_PARTITION_SIZE}, \
    {"app2", CONFIG_APP2_PHY_PARTITION_OFFSET, CONFIG_APP2_PHY_PARTITION_SIZE}, \
    {"secondary_tfm_s", CONFIG_SECONDARY_TFM_S_PHY_PARTITION_OFFSET, CONFIG_SECONDARY_TFM_S_PHY_PARTITION_SIZE}, \
    {"secondary_cpu0_app", CONFIG_SECONDARY_CPU0_APP_PHY_PARTITION_OFFSET, CONFIG_SECONDARY_CPU0_APP_PHY_PARTITION_SIZE}, \
    {"secondary_all", CONFIG_SECONDARY_ALL_PHY_PARTITION_OFFSET, CONFIG_SECONDARY_ALL_PHY_PARTITION_SIZE}, \
    {"common_B", CONFIG_COMMON_B_PHY_PARTITION_OFFSET, CONFIG_COMMON_B_PHY_PARTITION_SIZE}, \
    {"app1_B", CONFIG_APP1_B_PHY_PARTITION_OFFSET, CONFIG_APP1_B_PHY_PARTITION_SIZE}, \
    {"app2_B", CONFIG_APP2_B_PHY_PARTITION_OFFSET, CONFIG_APP2_B_PHY_PARTITION_SIZE}, \
    {"userfs", CONFIG_USERFS_PHY_PARTITION_OFFSET, CONFIG_USERFS_PHY_PARTITION_SIZE}, \
    {"usrconfig", CONFIG_USRCONFIG_PHY_PARTITION_OFFSET, CONFIG_USRCONFIG_PHY_PARTITION_SIZE}, \
    {"system_data", CONFIG_SYSTEM_DATA_PHY_PARTITION_OFFSET, CONFIG_SYSTEM_DATA_PHY_PARTITION_SIZE}, \
    {"reserved", CONFIG_RESERVED_PHY_PARTITION_OFFSET, CONFIG_RESERVED_PHY_PARTITION_SIZE}, \
    {"rf", CONFIG_RF_PHY_PARTITION_OFFSET, CONFIG_RF_PHY_PARTITION_SIZE}, \
    {"net", CONFIG_NET_PHY_PARTITION_OFFSET, CONFIG_NET_PHY_PARTITION_SIZE}, \
    {"easyflash", CONFIG_EASYFLASH_PHY_PARTITION_OFFSET, CONFIG_EASYFLASH_PHY_PARTITION_SIZE}, \
    {"bootparam", CONFIG_BOOTPARAM_PHY_PARTITION_OFFSET, CONFIG_BOOTPARAM_PHY_PARTITION_SIZE}, \
}
