#define CONFIG_TFM_HEAP_SIZE 0x5800
#define CONFIG_TFM_RAM_SIZE 0x1C000
#define CONFIG_BL2_WDT_PERIOD 0x1F40
#define CONFIG_TFM_LOG_LEVEL  0
#define CONFIG_NUM_APPS  2
#define CONFIG_BINARY_SIGNING 0
#define CONFIG_XIP_KERNEL 0


