
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t maxpooling_output_ref[72] = {126, 75,  113, 122, 101, 122, 105, 120, 125, 107, 121, 123, 122, 115, 117,
                                          124, 125, 122, 119, 116, 114, 115, 118, 119, 124, 118, 121, 121, 119, 126,
                                          105, 113, 121, 123, 125, 110, 119, 115, 120, 117, 126, 124, 112, 120, 103,
                                          88,  125, 125, 103, 98,  126, 124, 121, 119, 118, 110, 110, 124, 94,  123,
                                          100, 125, 126, 124, 101, 106, 108, 114, 103, 99,  122, 123};
