
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const q15_t dw_int16xint8_fast_stride_null_bias_output_ref[64] = {
    6851,   -8524, 1587,  -3803, -556,   10373,  -633,   6595,  11642,  -4598,  -253,  -2753, -12639,
    -18827, -388,  4217,  -9823, -311,   16000,  -13879, -6339, -4188,  -12402, 4556,  1479,  410,
    10538,  9838,  -9279, 8021,  -4391,  9789,   3323,   -3344, -15337, -4658,  -8062, -7318, 16000,
    9947,   13069, 2319,  -1845, -12946, -13451, -10140, 2482,  5172,   -11978, 4807,  -606,  1530,
    1551,   2971,  6140,  3655,  1978,   -2175,  -2535,  16000, -13683, 4954,   4712,  -3521};
