
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t maxpooling_4_input[40] = {-117, -127, -44, 5,   13,  5,   26,   -115, -33,  -102, 91,   45, 68,  52,
                                       60,   93,   96,  -73, -29, -46, -128, 62,   -108, 20,   67,   84, 109, -67,
                                       -70,  -99,  -10, -60, -55, -9,  56,   -60,  -74,  -52,  -126, 14};
