
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t int16xint8_dilation_3_weights[96] = {
    82,  70,   -127, -60,  81,  37,   -123, -5,   71,  -80, 37,  86,  31,  18,  -70,  -37,  -44,  -41,  -15,  -14,
    124, 4,    -21,  -43,  95,  2,    -23,  32,   0,   -36, 15,  101, -43, -11, 51,   -40,  -127, -116, -64,  82,
    -59, 43,   99,   -104, -51, -119, 118,  -105, 40,  88,  71,  94,  127, -91, -95,  -36,  -65,  123,  -115, -91,
    -60, 124,  106,  52,   101, -51,  114,  38,   78,  -44, -91, -76, 88,  44,  3,    -104, 87,   -59,  87,   -61,
    59,  -127, -46,  -26,  58,  -87,  -48,  127,  -82, -10, 127, -34, -16, -50, -126, -26};
