
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#define DW_INT16XINT8_DILATION_OUT_CH 8
#define DW_INT16XINT8_DILATION_IN_CH 4
#define DW_INT16XINT8_DILATION_INPUT_W 9
#define DW_INT16XINT8_DILATION_INPUT_H 5
#define DW_INT16XINT8_DILATION_DST_SIZE 360
#define DW_INT16XINT8_DILATION_INPUT_SIZE 180
#define DW_INT16XINT8_DILATION_OUT_ACTIVATION_MIN -32700
#define DW_INT16XINT8_DILATION_OUT_ACTIVATION_MAX 32767
#define DW_INT16XINT8_DILATION_INPUT_BATCHES 1
#define DW_INT16XINT8_DILATION_FILTER_X 4
#define DW_INT16XINT8_DILATION_FILTER_Y 4
#define DW_INT16XINT8_DILATION_STRIDE_X 1
#define DW_INT16XINT8_DILATION_STRIDE_Y 1
#define DW_INT16XINT8_DILATION_PAD_X 4
#define DW_INT16XINT8_DILATION_PAD_Y 3
#define DW_INT16XINT8_DILATION_OUTPUT_W 9
#define DW_INT16XINT8_DILATION_OUTPUT_H 5
#define DW_INT16XINT8_DILATION_CH_MULT 2
#define DW_INT16XINT8_DILATION_INPUT_OFFSET 0
#define DW_INT16XINT8_DILATION_OUTPUT_OFFSET 0
#define DW_INT16XINT8_DILATION_DILATION_X 3
#define DW_INT16XINT8_DILATION_DILATION_Y 2
