
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t dw_int16xint8_dilation_weights[128] = {
    67,   91,  -111, -53,  118,  69,  -23,  11,   -124, 40,  -91, 12,   -92, -112, 95,   45,   67,   28,  -127,
    -120, 95,  80,   -13,  -33,  15,  80,   -116, -56,  -79, -46, 97,   66,  63,   6,    -45,  125,  -57, 18,
    95,   -29, -57,  -68,  -13,  49,  -127, 127,  -3,   78,  35,  -115, 65,  -58,  -106, 108,  10,   113, 41,
    -37,  120, 127,  -18,  -50,  81,  39,   122,  -92,  127, 85,  109,  -21, -42,  68,   -109, -115, 122, 31,
    101,  48,  -99,  -86,  118,  -47, 83,   0,    -66,  39,  127, -80,  -83, -96,  -106, -115, 11,   99,  71,
    15,   19,  35,   -127, -118, 72,  101,  -78,  -108, 58,  -43, -92,  58,  96,   -32,  49,   14,   96,  -114,
    81,   86,  -110, -86,  -109, 118, -127, -127, 31,   76,  11,  -81,  -87, -127};
