
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t avgpooling_2_input[60] = {-82, -104, 10,  -28, -52, -51, -66, 52,  124, -74, -21,  4,  37,   -7,  -33,
                                       102, 110,  24,  52,  121, 13,  -55, -79, -92, -35, -103, 86, 95,   46,  32,
                                       -24, -123, 120, 29,  -77, -97, -69, -68, 58,  38,  3,    3,  79,   -47, 112,
                                       -52, -113, -46, 107, 68,  83,  -70, 91,  14,  113, 74,   73, -103, -98, 25};
