
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t avgpooling_2_output_ref[60] = {-67, -85, 31, 48,  -63, -51, -55, 33,  30, -53, 10,  16,  38,  56,  5,
                                            31,  20,  -6, -16, 18,  4,   47,  13,  2,  39,  -38, -31, 45,  -6,  -27,
                                            -75, -35, 49, 44,  -2,  -39, -63, 44,  13, 24,  -49, -60, -12, 39,  73,
                                            11,  -60, 41, 25,  98,  35,  -37, -19, 8,  69,  79,  2,   -6,  -42, 69};
