
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#define ADD_S16_SPILL_DST_SIZE 105
#define ADD_S16_SPILL_OUT_ACTIVATION_MIN -2000
#define ADD_S16_SPILL_OUT_ACTIVATION_MAX 32767
#define ADD_S16_SPILL_INPUT1_OFFSET 0
#define ADD_S16_SPILL_INPUT2_OFFSET 0
#define ADD_S16_SPILL_OUTPUT_MULT 1073741824
#define ADD_S16_SPILL_OUTPUT_SHIFT -14
#define ADD_S16_SPILL_OUTPUT_OFFSET 0
#define ADD_S16_SPILL_LEFT_SHIFT 15
#define ADD_S16_SPILL_INPUT1_SHIFT 0
#define ADD_S16_SPILL_INPUT2_SHIFT 0
#define ADD_S16_SPILL_INPUT1_MULT 1073741824
#define ADD_S16_SPILL_INPUT2_MULT 1073741824
