
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_1_x_n_1_input[96] = {
    -117, 43,   -16, 74,   -35, 18,  17,   84,  28,  79,   119, 54,   83,   51,   35, -76, -95,  -66, 126, -10,
    116,  -17,  -17, -78,  -45, 122, 2,    16,  -41, -119, -26, -108, -8,   120,  5,  -42, 98,   81,  -59, 78,
    -17,  14,   38,  91,   74,  123, -116, 10,  -53, 69,   107, 117,  -34,  -96,  46, 121, 107,  49,  -10, -6,
    -105, -100, 24,  8,    81,  68,  96,   -17, 53,  71,   -68, -28,  -113, 60,   3,  -91, -101, 39,  -14, -105,
    -106, 55,   -34, -120, 0,   40,  124,  -4,  24,  -40,  81,  113,  -31,  -114, 56, 23};
