
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.7.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_1_x_n_1_output_ref[48] = {-62, -35, -127, -96, 43,  -63,  -39,  26, -50, -82, 47, -31,
                                          -12, -43, -91,  -79, -38, -100, -27,  32, -72, -49, 28, -127,
                                          -58, -31, -124, -73, 47,  -83,  -127, -4, -82, -64, 29, -81,
                                          -68, -9,  -113, -22, -77, -77,  -100, 23, -64, -59, 60, -5};
