/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCBASEDS_H_RPCGEN
#define _RPCBASEDS_H_RPCGEN

#include "rpc_struct.h"

#include "RPCBaseDS_data.h"

#ifdef __cplusplus
extern "C" {
#endif


/* the xdr functions */
extern  bool_t xdr_HRESULT(XDR *, HRESULT *);
extern  bool_t xdr_RPCRES_LONG(XDR *, RPCRES_LONG *);

#ifdef __cplusplus
}
#endif

#endif /* !_RPCBASEDS_H_RPCGEN */
