/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCBASEDS_DATA_H_RPCGEN
#define _RPCBASEDS_DATA_H_RPCGEN


typedef long HRESULT;

struct RPCRES_LONG {
	HRESULT result;
	long data;
};
typedef struct RPCRES_LONG RPCRES_LONG;

#endif /* !_RPCBASEDS_DATA_H_RPCGEN */
