/**
 * @file      tizenrt_ble_defs.h
 * @author    roy_zhu@realsil.com.cn
 * @brief     Bluetooth common type definition
 * @copyright Copyright (c) 2022. Realtek Semiconductor Corporation. All rights reserved.
 */
#ifndef __BLE_TIZENRT_DEFS_H__
#define __BLE_TIZENRT_DEFS_H__

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @typedef   rtk_bt_err_t
 * @brief     Bluetooth API return value definition.
 */
typedef enum
{
    BT_TIZENRT_OK = 0,                      /*!< 0, means success */
    BT_TIZENRT_FAIL,                       /*!< 1, means fail */
} bt_tizenrt_err_t;

typedef enum {
    BLE_TIZENRT_EVT_CONNECTED,         
	BLE_TIZENRT_EVT_PROFILE,
	BLE_TIZENRT_EVT_CONN,
	BLE_TIZENRT_EVT_SCAN_STATE,
	BLE_TIZENRT_EVT_SCANNED_DEVICE,
	BLE_TIZENRT_EVT_DISCONNECTED,
	BLE_TIZENRT_EVT_NOTIFICATION,
} ble_tizenrt_evt_code_t;

/**
 * @brief     BLE IPC TIZENRT message
 */
typedef enum {
	BLE_TIZENRT_ACT_SERVER_INIT = 1,
	BLE_TIZENRT_ACT_SERVER_DEINIT,
	BLE_TIZENRT_ACT_SERVER_GET_MAC_ADDRESS,
	BLE_TIZENRT_ACT_SERVER_SET_DATA_PTR,
	BLE_TIZENRT_ACT_SERVER_SET_LENGTH,
	BLE_TIZENRT_ACT_SERVER_GET_DATA_PTR,
	BLE_TIZENRT_ACT_SERVER_GET_LENGTH,
	BLE_TIZENRT_ACT_SERVER_CHARACT_NOTIFY,
	BLE_TIZENRT_ACT_SERVER_SERVER_REJECT,
	BLE_TIZENRT_ACT_SERVER_GET_MAC_ADDRESS_BY_CONN_HANDLE,
	BLE_TIZENRT_ACT_SERVER_GET_CONN_HANDLE_BY_ADDRESS,
	BLE_TIZENRT_ACT_SERVER_ADV_INTO_IDLE,
	BLE_TIZENRT_ACT_SERVER_SET_ADV_DATA,
	BLE_TIZENRT_ACT_SERVER_SET_ADV_NAME,
	BLE_TIZENRT_ACT_SERVER_CONN_IS_ACTIVE,
	BLE_TIZENRT_ACT_SERVER_CONN_IS_ANY_ACTIVE,
	BLE_TIZENRT_ACT_SERVER_DISCONNECT,
	BLE_TIZENRT_ACT_SERVER_START_ADV,
	BLE_TIZENRT_ACT_SERVER_STOP_ADV,
	BLE_TIZENRT_ACT_SERVER_GET_BONDED_DEVICE,
	BLE_TIZENRT_ACT_SERVER_DELETE_BONDED_DEVICE,
	BLE_TIZENRT_ACT_SERVER_DELETE_BONDED_DEVICE_ALL,
	BLE_TIZENRT_ACT_SERVER_SET_ADV_INTERVAL,
	BLE_TIZENRT_ACT_SERVER_SET_ADV_TYPE,
	BLE_TIZENRT_ACT_CLIENT_INIT,
	BLE_TIZENRT_ACT_CLIENT_SCAN_WHITELIST_ADD,
	BLE_TIZENRT_ACT_CLIENT_SCAN_WHITELIST_DELETE,
	BLE_TIZENRT_ACT_CLIENT_SCAN_WHITELIST_CLEAR_ALL,
	BLE_TIZENRT_ACT_CLIENT_START_SCAN,
	BLE_TIZENRT_ACT_CLIENT_START_SCAN_WITH_FILTER,
	BLE_TIZENRT_ACT_CLIENT_STOP_SCAN,
	BLE_TIZENRT_ACT_CLIENT_CONNECT,
	BLE_TIZENRT_ACT_CLIENT_READ_CONNECTED_DEVICE_LIST,
	BLE_TIZENRT_ACT_CLIENT_READ_CONNECTED_INFO,
	BLE_TIZENRT_ACT_CLIENT_DELETE_BOND,
	BLE_TIZENRT_ACT_CLIENT_DELETE_BOND_ALL,
	BLE_TIZENRT_ACT_CLIENT_DISCONNECTED,
	BLE_TIZENRT_ACT_CLIENT_DISCONNECTED_ALL,
	BLE_TIZENRT_ACT_CLIENT_OPERATION_READ,
	BLE_TIZENRT_ACT_CLIENT_OPERATION_WRITE,
	BLE_TIZENRT_ACT_CLIENT_OPERATION_WRITE_NO_RESPONSE,
	BLE_TIZENRT_ACT_CLIENT_OPERATION_ENABLE_NOTIFICATION,
	BLE_TIZENRT_ACT_CLIENT_DEINIT,
	BLE_TIZENRT_ACT_COMBO_INIT,
	BLE_TIZENRT_ACT_COMBO_DEINIT,
} ble_tizenrt_act_t;

#ifdef __cplusplus
}
#endif

#endif /* __BLE_TIZENRT_DEFS_H__ */
