/*
 * Copyright (c) 2018, Realsil Semiconductor Corporation. All rights reserved.
 */

#ifndef _BLE_AUDIO_FLAGS_H_
#define _BLE_AUDIO_FLAGS_H_

#ifdef  __cplusplus
extern "C" {
#endif      /* __cplusplus */

#define LE_AUDIO_PACS_SUPPORT 1
#define LE_AUDIO_ASCS_SUPPORT 1
#define LE_AUDIO_BASS_SUPPORT 1

#define LE_AUDIO_VCS_SUPPORT 1
#define LE_AUDIO_VOCS_SUPPORT 1
#define LE_AUDIO_AICS_SUPPORT 1
#define LE_AUDIO_MICS_SUPPORT 1

#define LE_AUDIO_CSIS_SUPPORT 1
#define LE_AUDIO_CAS_SUPPORT 1

#define LE_AUDIO_MCP_SERVER_SUPPORT  1

#define LE_AUDIO_CCP_SERVER_SUPPORT  1

#define LE_AUDIO_TMAS_SUPPORT 1
#define LE_AUDIO_HAS_SUPPORT  1

#define LE_AUDIO_CAP_SUPPORT 1
#define LE_AUDIO_BAP_SUPPORT 1

#define LE_AUDIO_PACS_CLIENT_SUPPORT 1
#define LE_AUDIO_ASCS_CLIENT_SUPPORT 1
#define LE_AUDIO_BASS_CLIENT_SUPPORT 1

#define LE_AUDIO_VCS_CLIENT_SUPPORT 1
#define LE_AUDIO_VOCS_CLIENT_SUPPORT 1
#define LE_AUDIO_AICS_CLIENT_SUPPORT 1
#define LE_AUDIO_MICS_CLIENT_SUPPORT 1

#define LE_AUDIO_MCP_CLIENT_SUPPORT  1

#define LE_AUDIO_CCP_CLIENT_SUPPORT  1

#define LE_AUDIO_CSIS_CLIENT_SUPPORT 1
#define LE_AUDIO_TMAS_CLIENT_SUPPORT 1
#define LE_AUDIO_HAS_CLIENT_SUPPORT  1

#define LE_AUDIO_BROADCAST_SOURCE_ROLE    1
#define LE_AUDIO_BROADCAST_SINK_ROLE      1
#define LE_AUDIO_SCAN_DELEGATOR_ROLE      1
#define LE_AUDIO_BROADCAST_ASSISTANT_ROLE 1

#define LE_AUDIO_BASE_DATA_GENERATE (LE_AUDIO_BROADCAST_SOURCE_ROLE)
#define LE_AUDIO_BASE_DATA_PARSE    (LE_AUDIO_BROADCAST_SINK_ROLE || LE_AUDIO_BROADCAST_ASSISTANT_ROLE)

#ifdef  __cplusplus
}
#endif      /*  __cplusplus */

#endif
