/****************************************************************************
 *
 * Copyright 2020 Samsung Electronics All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 *
 ****************************************************************************/
/****************************************************************************
 * os/arch/arm/src/common/go_os_start.c
 *
 *   Copyright (C) 2018 Gregory Nutt. All rights reserved.
 *   Author: Gregory Nutt <gnutt@nuttx.org>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name NuttX nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <tinyara/config.h>

#include "init/init.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/****************************************************************************
 * Public data
 ****************************************************************************/

/****************************************************************************
 * Private Function prototypes
 ****************************************************************************/

/****************************************************************************
 * Private Functions
 ****************************************************************************/

/****************************************************************************
 * Public Functions
 ****************************************************************************/

/****************************************************************************
 * Name: go_os_start
 *
 * Description:
 *   Set the IDLE stack to the stack coloration value then jump to os_start().
 *
 ****************************************************************************/

#ifdef CONFIG_STACK_COLORATION
void go_os_start(void *pv, unsigned int nbytes)
{
	/* Set the IDLE stack to the stack coloration value then jump to
	 * os_start().  We take extreme care here because were currently
	 * executing on this stack.
	 *
	 * We want to avoid sneak stack access generated by the compiler.
	 */

	__asm__ __volatile__("\tmovs r1, r1, lsr #2\n"  /* R1 = nwords = nbytes >> 2 */
						 "\tcmp  r1, #0\n"          /* Check (nwords == 0) */
						 "\tbeq  2f\n"              /* (should not happen) */
						 "\tbic  r0, r0, #3\n"      /* R0 = Aligned stackptr */
						 "\tmovw r2, #0xbeef\n"     /* R2 = STACK_COLOR = 0xdeadbeef */
						 "\tmovt r2, #0xdead\n"

						 "1:\n"                     /* Top of the loop */
						 "\tsub  r1, r1, #1\n"      /* R1 nwords-- */
						 "\tcmp  r1, #0\n"          /* Check (nwords == 0) */
						 "\tstr  r2, [r0], #4\n"    /* Save stack color word, increment stackptr */
						 "\tbne  1b\n"              /* Bottom of the loop */

						 "2:\n" 
						 "\tmov  r14, #0\n"         /* LR = return address (none) */
						 "\tb    os_start\n"        /* Branch to os_start */
						);
}
#endif
