
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#define FC_INT16_SLOW_OUT_CH 11
#define FC_INT16_SLOW_IN_CH 7
#define FC_INT16_SLOW_INPUT_W 10
#define FC_INT16_SLOW_INPUT_H 8
#define FC_INT16_SLOW_DST_SIZE 33
#define FC_INT16_SLOW_INPUT_SIZE 560
#define FC_INT16_SLOW_OUT_ACTIVATION_MIN -32768
#define FC_INT16_SLOW_OUT_ACTIVATION_MAX 32767
#define FC_INT16_SLOW_INPUT_BATCHES 3
#define FC_INT16_SLOW_OUTPUT_MULTIPLIER 1978159902
#define FC_INT16_SLOW_OUTPUT_SHIFT -16
#define FC_INT16_SLOW_ACCUMULATION_DEPTH 560
#define FC_INT16_SLOW_INPUT_OFFSET 0
#define FC_INT16_SLOW_OUTPUT_OFFSET 0
