
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.8.0 as reference.
#pragma once
#define DEPTHWISE_NULL_BIAS_1_OUT_CH 16
#define DEPTHWISE_NULL_BIAS_1_IN_CH 2
#define DEPTHWISE_NULL_BIAS_1_INPUT_W 4
#define DEPTHWISE_NULL_BIAS_1_INPUT_H 5
#define DEPTHWISE_NULL_BIAS_1_DST_SIZE 320
#define DEPTHWISE_NULL_BIAS_1_INPUT_SIZE 40
#define DEPTHWISE_NULL_BIAS_1_OUT_ACTIVATION_MIN -128
#define DEPTHWISE_NULL_BIAS_1_OUT_ACTIVATION_MAX 127
#define DEPTHWISE_NULL_BIAS_1_INPUT_BATCHES 1
#define DEPTHWISE_NULL_BIAS_1_FILTER_X 2
#define DEPTHWISE_NULL_BIAS_1_FILTER_Y 2
#define DEPTHWISE_NULL_BIAS_1_STRIDE_X 1
#define DEPTHWISE_NULL_BIAS_1_STRIDE_Y 1
#define DEPTHWISE_NULL_BIAS_1_PAD_X 0
#define DEPTHWISE_NULL_BIAS_1_PAD_Y 0
#define DEPTHWISE_NULL_BIAS_1_OUTPUT_W 4
#define DEPTHWISE_NULL_BIAS_1_OUTPUT_H 5
#define DEPTHWISE_NULL_BIAS_1_CH_MULT 8
#define DEPTHWISE_NULL_BIAS_1_INPUT_OFFSET 128
#define DEPTHWISE_NULL_BIAS_1_OUTPUT_OFFSET 41
#define DEPTHWISE_NULL_BIAS_1_DILATION_X 1
#define DEPTHWISE_NULL_BIAS_1_DILATION_Y 1
