#ifndef _OIC_DEF_
#define _OIC_DEF_

/**
 * Defines used in more than 2 devices are defined here
 * All the other device specific values are defined
 * in the "oicXXdef.h"
 */

#define OIC_STACK_FIRMWARE_VERSION      "OIC_0.9.1.D.17.03.31_1_30dbca2"

#define MANUFACTURER_NAME               "Samsung Electronics"
#define MANUFACTURER_URL                "http://www.samsung.com"

/* Resource Types */
#define OIC_INTERFACE_BASELINE          "oic.if.baseline"
#define OIC_INTERFACE_LINKEDLIST        "oic.if.ll"
#define OIC_INTERFACE_LINKEDBATCH       "oic.if.lb"
#define OIC_INTERFACE_BATCH             "oic.if.b"
#define OIC_INTERFACE_ACTUATOR          "oic.if.a"
#define OIC_INTERFACE_SENSOR            "oic.if.s"

#define OIC_RTYPE_COLLECTION_WK         "oic.wk.col"
#define OIC_RTYPE_MAINTENANCE_WK        "oic.wk.mnt"
#define OIC_RTYPE_BINARY_SWITCH         "oic.r.switch.binary"
#define OIC_RTYPE_MODE                  "oic.r.mode"
#define OIC_RTYPE_TEMPERATURE           "oic.r.temperature"
#define OIC_RTYPE_DOOR                  "oic.r.door"
#define OIC_RTYPE_OPERATION_STATE       "oic.r.operational.state"
#define OIC_RTYPE_ENERGY_CONSUMPTION    "oic.r.energy.consumption"
#define OIC_RTYPE_ENERGY_BATTERY        "oic.r.energy.battery"
#define OIC_RTYPE_ENERGY_DRLC           "oic.r.energy.drlc"
#define OIC_RTYPE_LIGHT_DIMMING         "oic.r.light.dimming"
#define OIC_RTYPE_AIRFLOW               "oic.r.airflow"
#define OIC_RTYPE_HUMIDITY              "oic.r.humidity"
#define OIC_RTYPE_SENSOR_MOTION         "oic.r.sensor.motion"
#define OIC_RTYPE_REFRIGERATION         "oic.r.refrigeration"
#define OIC_RTYPE_ICEMAKER              "oic.r.icemaker"
#define OIC_RTYPE_FILETRANSFER          "oic.r.filetransfer"


#define SEC_RTYPE_COLLECTION            "x.com.samsung.da.collection"
#define SEC_RTYPE_ACTIONS               "x.com.samsung.da.actions"
#define SEC_RTYPE_ALARM                 "x.com.samsung.da.alarms"
#define SEC_RTYPE_CONFIGURATION         "x.com.samsung.da.configuration"
//#define SEC_RTYPE_THINGS_DEVICE             "x.com.samsung.da.device"
#define SEC_RTYPE_THINGS_DEVICE             "x.com.samsung.devcol"   // CONPRO-241
#define SEC_RTYPE_DIAGNOSIS             "x.com.samsung.da.diagnosis"
#define SEC_RTYPE_ENERGY_CONSUMPTION    "x.com.samsung.da.energyconsumption"
#define SEC_RTYPE_INFORMATION           "x.com.samsung.da.information"
#define SEC_RTYPE_MODE                  "x.com.samsung.da.mode"
#define SEC_RTYPE_NOTIFICATION          "x.com.samsung.da.notification"
#define SEC_RTYPE_OPERATION             "x.com.samsung.da.operation"
#define SEC_RTYPE_OPTION                "x.com.samsung.da.option"
#define SEC_RTYPE_SENSOR                "x.com.samsung.da.sensors"
#define SEC_RTYPE_STATUS                "x.com.samsung.da.status"
#define SEC_RTYPE_TEMPERATURE           "x.com.samsung.da.temperatures"
#define SEC_RTYPE_UPDATE                "x.com.samsung.da.update"
#define SEC_RTYPE_WASHER                "x.com.samsung.da.washer"
#define SEC_RTYPE_REFRIGERATION         "x.com.samsung.da.fridge"
#define SEC_RTYPE_WIND                  "x.com.samsung.da.wind"
#define SEC_RTYPE_OVEN                  "x.com.samsung.da.oven"
#define SEC_RTYPE_CUSTOM_RECIPE         "x.com.samsung.da.customrecipe"
#define SEC_RTYPE_DRLC                  "x.com.samsung.da.drlc"
#define SEC_RTYPE_DEFROST_RESERVATION   "x.com.samsung.da.defrost.reservation"
#define SEC_RTYPE_MOVEMENT              "x.com.samsung.da.movement"
#define SEC_RTYPE_DOORS                 "x.com.samsung.da.doors"
#define SEC_RTYPE_ACCESSPOINTS          "x.com.samsung.da.accesspoints"

#define SEC_RTYPE_BIXBY                 "x.com.samsung.bixby"
#define SEC_RTYPE_FILE_LIST             "x.com.samsung.file.list"
#define SEC_RTYPE_FILE_TRANSFER         "x.com.samsung.file.transfer"
#define SEC_RTYPE_CONTENTS_PROVIDER     "x.com.samsung.contents.provider"
#define SEC_RTYPE_CONTENTS_RENDERER     "x.com.samsung.contents.renderer"
#define SEC_RTYPE_DISHWASHER            "x.com.samsung.da.dishwasher"
#define SEC_RTYPE_PROV_INFO             "x.com.samsung.provisioninginfo"

/* Atrribute Keys */
#define OIC_ATTRIBUTE_N                          "n"
#define OIC_ATTRIBUTE_VALUE                      "value"
#define OIC_ATTRIBUTE_VALUES                     "values"

#define OIC_ATTRIBUTE_MODE_SUPMODES              "supportedModes"
#define OIC_ATTRIBUTE_MODE_MODES                 "modes"

#define OIC_ATTRIBUTE_TEMPERATURE                "temperature"
#define OIC_ATTRIBUTE_TEMPERATURE_UNITS          "units"
#define OIC_ATTRIBUTE_TEMPERATURE_RANGE          "range"
#define OIC_ATTRIBUTE_AIRFLOW_SPEED              "speed"
#define OIC_ATTRIBUTE_AIRFLOW_DIRECTION          "direction"
#define OIC_ATTRIBUTE_AIRFLOW_RANGE              "range"
#define OIC_ATTRIBUTE_HUMIDITY                   "humidity"
#define OIC_ATTRIBUTE_HUMIDITY_DESIRE            "desiredHumidity"
#define OIC_ATTRIBUTE_FILTER                     "filter"
#define OIC_ATTRIBUTE_DOOR_OPENSTATE             "openState"
#define OIC_ATTRIBUTE_DOOR_OPENDURATION          "openDuration"
#define OIC_ATTRIBUTE_DOOR_OPENALARM             "openAlarm"
#define OIC_ATTRIBUTE_LIGHT_DIMMING_SETTING      "dimmingSetting"
#define OIC_ATTRIBUTE_RAPID_FREEZE               "rapidFreeze"
#define OIC_ATTRIBUTE_RAPID_COOL                 "rapidCool"
#define OIC_ATTRIBUTE_DEFROST                    "defrost"
#define OIC_ATTRIBUTE_STATUS                     "status"
#define OIC_ATTRIBUTE_OPTIONS                    "options"
#define OIC_ATTRIBUTE_OPERATIONS                 "operations"
#define OIC_ATTRIBUTE_NOTIFICATION               "notification"
#define OIC_ATTRIBUTE_DRTYPE                     "DRType"
#define OIC_ATTRIBUTE_START                      "start"
#define OIC_ATTRIBUTE_DURATION                   "duration"
#define OIC_ATTRIBUTE_OVERRIDE                   "override"
#define OIC_ATTRIBUTE_OPSTATE_MACHINESTATES      "machineStates"
#define OIC_ATTRIBUTE_OPSTATE_CURRENT_MACHINESTATE "currentMachineState"
#define OIC_ATTRIBUTE_OPSTATE_JOBSTATES          "jobStates"
#define OIC_ATTRIBUTE_OPSTATE_CURRENT_JOBSTATE   "currentJobState"
#define OIC_ATTRIBUTE_OPSTATE_RUNNING_TIME       "runningTime"
#define OIC_ATTRIBUTE_OPSTATE_REMAINING_TIME     "remainingTime"
#define OIC_ATTRIBUTE_OPSTATE_PROGESS_PERCENTAGE "progressPercentage"
#define OIC_ATTRIBUTE_CHARGE                     "charge"
#define OIC_ATTRIBUTE_ENERGY                     "energy"
#define OIC_ATTRIBUTE_POWER                      "power"
#define OIC_ATTRIBUTE_RESET_FACTORY              "fr"


#define SEC_ATTRIBUTE_CUMULATIVE_CONSUMPTION      "x.com.samsung.da.cumulativeConsumption"
#define SEC_ATTRIBUTE_TEMPERATURE_CURRENT         "x.com.samsung.da.current"
#define SEC_ATTRIBUTE_TIME_CURRENT                "x.com.samsung.da.currentTime"
#define SEC_ATTRIBUTE_TEMPERATURE_DESIRED         "x.com.samsung.da.desired"
#define SEC_ATTRIBUTE_DIAGNOSIS_START             "x.com.samsung.da.diagnosisStart"
#define SEC_ATTRIBUTE_DIRECTION                   "x.com.samsung.da.direction"
#define SEC_ATTRIBUTE_INSTANTANEOUS_POWER         "x.com.samsung.da.instantaneousPower"
#define SEC_ATTRIBUTE_LENGTH                      "x.com.samsung.da.length"
#define SEC_ATTRIBUTE_OPTIONS                     "x.com.samsung.da.options"
#define SEC_ATTRIBUTE_SAVE_LOCATION               "x.com.samsung.da.saveLocation"
#define SEC_ATTRIBUTE_POWER                       "x.com.samsung.da.power"
#define SEC_ATTRIBUTE_SPEED_LEVEL                 "x.com.samsung.da.speedLevel"
#define SEC_ATTRIBUTE_THRESHOLD                   "x.com.samsung.da.usageThreshold"
#define SEC_ATTRIBUTE_TEMPERATURE_UNIT            "x.com.samsung.da.unit"
#define SEC_ATTRIBUTE_STATE                       "x.com.samsung.da.state"
#define SEC_ATTRIBUTE_RECIPE                      "x.com.samsung.da.recipe"
#define SEC_ATTRIBUTE_STEAM_LEVEL                 "x.com.samsung.da.steamLevel"
#define SEC_ATTRIBUTE_SUPPORTED_STEAM_LEVEL       "x.com.samsung.da.supportedSteamLevel"
#define SEC_ATTRIBUTE_REMOTE_CONTROL_ENABLED      "x.com.samsung.da.remoteControlEnabled"
#define SEC_ATTRIBUTE_CURRENT_TIME                "x.com.samsung.da.currentTime"
#define SEC_ATTRIBUTE_TEMPERATURE_UNITS           "x.com.samsung.da.unit"
#define SEC_ATTRIBUTE_CUSTOMERECIPE               "x.com.samsung.da.customRecipe"
#define SEC_ATTRIBUTE_REMAIN_TIME                 "x.com.samsung.da.remainingTime"
#define SEC_ATTRIBUTE_SUPPORTED_PROGRESS          "x.com.samsung.da.supportedProgress"
#define SEC_ATTRIBUTE_OPERATION_TIME              "x.com.samsung.da.operationTime"
#define SEC_ATTRIBUTE_SUPPORTED_MODES             "x.com.samsung.da.supportedModes"
#define SEC_ATTRIBUTE_MODES                       "x.com.samsung.da.modes"
#define SEC_ATTRIBUTE_TYPE                        "x.com.samsung.da.type"
#define SEC_ATTRIBUTE_TYPE_ALARM                  "x.com.samsung.da.alarmType"
#define SEC_ATTRIBUTE_CODE                        "x.com.samsung.da.code"
#define SEC_ATTRIBUTE_TRIGGERED_TIME              "x.com.samsung.da.triggeredTime"
#define SEC_ATTRIBUTE_ID                          "x.com.samsung.da.id"
#define SEC_ATTRIBUTE_DOORSTATE                   "x.com.samsung.da.openState"
#define SEC_ATTRIBUTE_NUMBER                      "x.com.samsung.da.number"
#define SEC_ATTRIBUTE_PROGRESS                    "x.com.samsung.da.progress"
#define SEC_ATTRIBUTE_PROGRESS_PERCENTAGE         "x.com.samsung.da.progressPercentage"
#define SEC_ATTRIBUTE_AUTO_DETERGENT_ENABLED      "x.com.samsung.da.autoDetergentEnabled"
#define SEC_ATTRIBUTE_AUTO_SOFTENER_ENABLED       "x.com.samsung.da.autoSoftenerEnabled"
#define SEC_ATTRIBUTE_DETERGENT_LEVEL             "x.com.samsung.da.detergentLevel"
#define SEC_ATTRIBUTE_SOFTENER_LEVEL              "x.com.samsung.da.softenerLevel"
#define SEC_ATTRIBUTE_WRINKLE_PREVENT             "x.com.samsung.da.wrinklePrevent"
#define SEC_ATTRIBUTE_WATER_TEMPERATURE           "x.com.samsung.da.waterTemperature"
#define SEC_ATTRIBUTE_SUPPORTED_WATER_TEMPERATURE "x.com.samsung.da.supportedWaterTemperature"
#define SEC_ATTRIBUTE_SPIN_LEVEL                  "x.com.samsung.da.spinLevel"
#define SEC_ATTRIBUTE_SUPPORTED_SPIN_LEVEL        "x.com.samsung.da.supportedSpinLevel"
#define SEC_ATTRIBUTE_DRY_LEVEL                   "x.com.samsung.da.dryLevel"
#define SEC_ATTRIBUTE_SUPPORTED_DRY_LEVEL         "x.com.samsung.da.supportedDryLevel"
#define SEC_ATTRIBUTE_SOIL_LEVEL                  "x.com.samsung.da.soilLevel"
#define SEC_ATTRIBUTE_SUPPORTED_SOIL_LEVEL        "x.com.samsung.da.supportedSoilLevel"
#define SEC_ATTRIBUTE_RINSE_CYCLES                "x.com.samsung.da.rinseCycles"
#define SEC_ATTRIBUTE_SUPPORTED_RINSE_CYCLES      "x.com.samsung.da.supportedRinseCycles"
#define SEC_ATTRIBUTE_DRY_TIME                    "x.com.samsung.da.dryTime"
#define SEC_ATTRIBUTE_SUPPORTED_DRYTIME           "x.com.samsung.da.supporteDryTime"
#define SEC_ATTRIBUTE_DRYER_TYPE                  "x.com.samsung.da.dryerType"
#define SEC_ATTRIBUTE_KIDSLOCK                    "x.com.samsung.da.kidsLock"
#define SEC_ATTRIBUTE_DESCRIPTION                 "x.com.samsung.da.description"
#define SEC_ATTRIBUTE_EANABLED                    "x.com.samsung.da.enabled"
#define SEC_ATTRIBUTE_MANUFACTURER                "x.com.samsung.da.manufacturer"
#define SEC_ATTRIBUTE_MODELID                     "x.com.samsung.da.modelID"

#define SEC_ATTRIBUTE_THINGS_NAME                     "x.com.samsung.da.name"
#define SEC_ATTRIBUTE_MODEL_NUM                   "x.com.samsung.da.modelNum"
#define SEC_ATTRIBUTE_DESCRIPTION                 "x.com.samsung.da.description"
#define SEC_ATTRIBUTE_SERIAL_NUM                  "x.com.samsung.da.serialNum"
#define SEC_ATTRIBUTE_VERSION_ID                  "x.com.samsung.da.versionId"
#define SEC_ATTRIBUTE_APPROVED_STATE              "x.com.samsung.da.approvedState"
#define SEC_ATTRIBUTE_VERSION_AVAILABLE           "x.com.samsung.da.newVersionAvailable"

#define SEC_ATTRIBUTE_DELAY_START_TIME                 "x.com.samsung.da.delayStartTime"
#define SEC_ATTRIBUTE_SUPPORTED_SELECTED_ZONE          "x.com.samsung.da.supportedSelectedZone"
#define SEC_ATTRIBUTE_SUPPORTED_ZONE_BOOSTER           "x.com.samsung.da.supportedZoneBooster"
#define SEC_ATTRIBUTE_SUPPORTED_SPEED_BOOSTER          "x.com.samsung.da.supportedSpeedBooster"
#define SEC_ATTRIBUTE_SUPPORTED_SANITIZE               "x.com.samsung.da.supportedSanitize"
#define SEC_ATTRIBUTE_SUPPORTED_HIGH_TEMPERATURE_DRY   "x.com.samsung.da.supportedHighTemperatureDry"
#define SEC_ATTRIBUTE_SELECTED_ZONE                    "x.com.samsung.da.selectedZone"
#define SEC_ATTRIBUTE_ZONE_BOOSTER                     "x.com.samsung.da.zoneBooster"
#define SEC_ATTRIBUTE_SPEED_BOOSTER                    "x.com.samsung.da.speedBooster"
#define SEC_ATTRIBUTE_SANITIZE                         "x.com.samsung.da.sanitize"
#define SEC_ATTRIBUTE_HIGH_TEMPERATURE_DRY             "x.com.samsung.da.highTemperatureDry"

#define SEC_ATTRIBUTE_ITEMS                     "x.com.samsung.da.items"
// #define SEC_ATTRIBUTE_USERAGREEMENT             "x.com.samsung.da.userAgreement"
// #define SEC_ATTRIBUTE_NEWVERSIONAVAILABLE       "x.com.samsung.da.newVersionAvailable"
#define SEC_ATTRIBUTE_SUPPORTED_OPTIONS         "x.com.samsung.da.supportedOptions"
#define SEC_ATTRIBUTE_RAPID_FREEZE              "x.com.samsung.da.rapidFreezing"
#define SEC_ATTRIBUTE_RAPID_FRIDGE              "x.com.samsung.da.rapidFridge"
#define SEC_ATTRIBUTE_RAPID_COOL                "x.com.samsung.da.rapidcool"
#define SEC_ATTRIBUTE_ICEMAKER                  "x.com.samsung.da.iceMaker"
#define SEC_ATTRIBUTE_DELAYDEFROST              "x.com.samsung.da.delayDefrost"
#define SEC_ATTRIBUTE_BATTERY_CHARGE            "x.com.samsung.da.batteryCharge"
#define SEC_ATTRIBUTE_MONTHLY_CONSUMPTION       "x.com.samsung.da.monthlyConsumption"

#define SEC_ATTRIBUTE_DRLC_LEVEL                "x.com.samsung.da.drlcLevel"
#define SEC_ATTRIBUTE_DRLC_DURATION             "x.com.samsung.da.duration"
#define SEC_ATTRIBUTE_DRLC_STARTTIME            "x.com.samsung.da.drlcStartTime"
#define SEC_ATTRIBUTE_DRLC_OVERRIDE             "x.com.samsung.da.override"

#define SEC_ATTRIBUTE_MOVEMENT_BEHAVIOR     "x.com.samsung.da.behavior"
#define SEC_ATTRIBUTE_MOVEMENT_DES_X        "x.com.samsung.da.destinationX"
#define SEC_ATTRIBUTE_MOVEMENT_DES_Y        "x.com.samsung.da.destinationY"
#define SEC_ATTRIBUTE_MOVEMENT_DES_ANGLE    "x.com.samsung.da.destinationAngle"
#define SEC_ATTRIBUTE_MOVEMENT_MAP          "x.com.samsung.da.map"
#define SEC_ATTRIBUTE_MOVEMENT_CUR_X        "x.com.samsung.da.currentX"
#define SEC_ATTRIBUTE_MOVEMENT_CUR_Y        "x.com.samsung.da.currentY"
#define SEC_ATTRIBUTE_MOVEMENT_CUR_ANGLE    "x.com.samsung.da.currentAngle"
#define SEC_ATTRIBUTE_MOVEMENT_HISTORY      "x.com.samsung.da.history"

#define SEC_ATTRIBUTE_START_TIME            "x.com.samsung.da.startTime"
#define SEC_ATTRIBUTE_END_TIME              "x.com.samsung.da.endTime"
#define SEC_ATTRIBUTE_PERIOD                "x.com.samsung.da.period"
#define SEC_ATTRIBUTE_REPEAT_PERIOD         "x.com.samsung.da.repeatPeriod"
#define SEC_ATTRIBUTE_DAYOFWEEK             "x.com.samsung.da.dayofWeek"
#define SEC_ATTRIBUTE_DISPOSABLE            "x.com.samsung.da.disposable"
#define SEC_ATTRIBUTE_DEVICEIDS             "x.com.samsung.da.deviceIDs"
#define SEC_ATTRIBUTE_ACTUATORS             "x.com.samsung.da.actuators"

#define SEC_ATTRIBUTE_HREF                  "x.com.samsung.da.href"
#define SEC_ATTRIBUTE_INTERFACE_TYPE        "x.com.samsung.da.if"
#define SEC_ATTRIBUTE_RESOURCE_TYPE         "x.com.samsung.da.rt"
#define SEC_ATTRIBUTE                       "x.com.samsung.da.attribute"
#define SEC_ATTRIBUTE_VALUE                 "x.com.samsung.da.value"

#define SEC_ATTRIBUTE_MAXIMUM               "x.com.samsung.da.maximum"
#define SEC_ATTRIBUTE_MINIMUM               "x.com.samsung.da.minimum"

// Will be removed/deprecated~!!!!
#define SEC_ATTRIBUTE_AP_CHANNAL_1          "x.com.samsung.da.channel"
#define SEC_ATTRIBUTE_AP_ENCTYPE_1          "x.com.samsung.da.encryptionType"
#define SEC_ATTRIBUTE_AP_MACADDR_1          "x.com.samsung.da.macAddress"
#define SEC_ATTRIBUTE_AP_MAXRATE_1          "x.com.samsung.da.maxRate"
#define SEC_ATTRIBUTE_AP_RSSI_1             "x.com.samsung.da.rssi"
#define SEC_ATTRIBUTE_AP_SECTYPE_1          "x.com.samsung.da.securityType"
#define SEC_ATTRIBUTE_AP_SSID_1             "x.com.samsung.da.ssid"
#define SEC_ATTRIBUTE_REGION                "x.com.samsung.da.region"


// Common Attribute Keys
#define SEC_ATTRIBUTE_COMMON_ITEMS          "x.com.samsung.items"
#define SEC_ATTRIBUTE_COMMON_ID             "x.com.samsung.id"
#define SEC_ATTRIBUTE_LOG_COLLECT           "x.com.samsung.collectlogs"
#define SEC_ATTRIBUTE_LOG_IDS               "x.com.samsung.logids"
#define SEC_ATTRIBUTE_FILE_BLOB             "x.com.samsung.blob"
#define SEC_ATTRIBUTE_NAME                  "x.com.samsung.name"
#define SEC_ATTRIBUTE_COMMON_TARGET         "x.com.samsung.target"
#define SEC_ATTRIBUTE_COMMON_VALUE          "x.com.samsung.value"

#define SEC_ATTRIBUTE_PROV_TARGETS          "x.com.samsung.provisioning.targets"
#define SEC_ATTRIBUTE_PROV_BLEADDR          "x.com.samsung.provisioning.bleaddr"
#define SEC_ATTRIBUTE_PROV_EZSETDI          "x.com.samsung.provisioning.easysetupdi"
#define SEC_ATTRIBUTE_PROV_RESET            "x.com.samsung.provisioning.reset"
#define SEC_ATTRIBUTE_PROV_TARGET_OWNED     "x.com.samsung.provisioning.owned"
#define SEC_ATTRIBUTE_PROV_TERMINATE_AP     "x.com.samsung.provisioning.stopAP"
#define SEC_ATTRIBUTE_PROV_ABORT            "x.com.samsung.provisioning.abort"
#define SEC_ATTRIBUTE_PROV_TARGET_ID        "x.com.samsung.targetDi"
#define SEC_ATTRIBUTE_PROV_TARGET_RT        "x.com.samsung.targetRt"
#define SEC_ATTRIBUTE_PROV_TARGET_PUBED     "x.com.samsung.published"

#define SEC_ATTRIBUTE_AP_ITEMS              "x.com.samsung.accesspoint.items"
#define SEC_ATTRIBUTE_AP_CHANNAL            "x.com.samsung.channel"
#define SEC_ATTRIBUTE_AP_ENCTYPE            "x.com.samsung.encryptionType"
#define SEC_ATTRIBUTE_AP_MACADDR            "x.com.samsung.macAddress"
#define SEC_ATTRIBUTE_AP_MAXRATE            "x.com.samsung.maxRate"
#define SEC_ATTRIBUTE_AP_RSSI               "x.com.samsung.rssi"
#define SEC_ATTRIBUTE_AP_SECTYPE            "x.com.samsung.securityType"
#define SEC_ATTRIBUTE_AP_SSID               "x.com.samsung.ssid"

#define SEC_ATTRIBUTE_CONTENTS              "x.com.samsung.contents"
#define SEC_ATTRIBUTE_CONTENTS_RT           "x.com.samsung.rt"
#define SEC_ATTRIBUTE_CONTENTS_PROVIDER     "x.com.samsung.provider"
#define SEC_ATTRIBUTE_CONTENTS_HOST         "x.com.samsung.host"
#define SEC_ATTRIBUTE_CONTENTS_PATH         "x.com.samsung.path"
#define SEC_ATTRIBUTE_CONTENTS_QUERY        "x.com.samsung.query"
#define SEC_ATTRIBUTE_CONTENTS_MIME_TYPE    "x.com.samsung.mimeType"
#define SEC_ATTRIBUTE_CONTENTS_TRANSPORT    "x.com.samsung.transport"
#define SEC_ATTRIBUTE_CONTENTS_ENCODING     "x.com.samsung.encoding"
#define SEC_ATTRIBUTE_CONTENTS_PAYLOAD      "x.com.samsung.payload"
#define SEC_ATTRIBUTE_CONTENTS_ACTION       "x.com.samsung.action"
#define SEC_ATTRIBUTE_CONTENTS_CAPA_TYPE    "x.com.samsung.capability.type"
#define SEC_ATTRIBUTE_CONTENTS_DATETIME     "x.com.samsung.datetime"

#define OIC_QUERY_KEY_OP                    "op"
#define OIC_QUERY_VALUE_ADD                 "add"
#define OIC_QUERY_VALUE_UPDATE              "update"
#define OIC_QUERY_VALUE_REMOVE              "remove"

#define VALUE_TRUE                          "true"
#define VALUE_FALSE                         "false"

#define VALUE_ON                            "On"
#define VALUE_OFF                           "Off"
#define VALUE_NOTSUPPORTED                  "Notsupported"
#define VALUE_UNKNOWN                       "Unknown"

/* Resource URI */
#define URI_OIC                         "/oic"
#define URI_SEC                         "/sec"
#define URI_WK_MAINTENANCE              "/mnt"
#define URI_OVEN                        "/oven"
#define URI_DEVICE_COL                  "/device"
#define URI_POWER                       "/power"
#define URI_TEMPERATURE                 "/temperature"
#define URI_TEMPERATURES                "/temperatures"
#define URI_DESIRED                     "/desired"
#define URI_CONFIGURATION               "/configuration"
#define URI_CURRENT                     "/current"
#define URI_FILETRANSFER                "/filetransfer"
#define URI_BIXBY                       "/bixby"

#define URI_ACTIONS                     "/actions"
#define URI_ALARMS                      "/alarms"
#define URI_AIRFLOW                     "/airflow"
#define URI_WIND                        "/wind"
#define URI_HUMIDITY                    "/humidity"
#define URI_BATTERY                     "/battery" //Need to understand WRTIE functionlity
#define URI_ENERGY_CONSUME              "/consumption"
#define URI_DIAGNOSIS                   "/diagnosis"
#define URI_KIDSLOCK                    "/kidslock"
#define URI_MOTION                      "/motion"
#define URI_DIMMING                     "/dimming"
#define URI_DRLC                        "/drlc"
#define URI_ENERGY                      "/energy"
#define URI_ICEMAKER                    "/icemaker"
#define URI_INFORMATION                 "/information"
#define URI_MODE                        "/mode"
#define URI_CSZONESTATE                 "/coolselectzonestate"
#define URI_MODELOPTION                 "/modeloption"
#define URI_WATERFILTER                 "/waterfilter"
#define URI_MOTION                      "/motion"
#define URI_OPERATION                   "/operation"
#define URI_OPERATIONAL                 "/operational"
#define URI_OPTIONS                     "/options"
#define URI_REMOTECTRL                  "/remotectrl"
#define URI_SENSOR                      "/sensors"
#define URI_STATE                       "/state"
#define URI_STATUS                      "/status"
#define URI_TIME                        "/time"
#define URI_DEFROST                     "/defrost"
#define URI_BLOCK                       "/block"
#define URI_DELAY                       "/delay"
#define URI_RESERVATION                 "/reservation"
#define URI_VENDER_SPECIFIC             "/vs"
#define URI_PROB                        "/prob"
#define URI_COOK                        "/cook"
#define URI_RECIPE                      "/recipe"
#define URI_COURSE                      "/course"
#define URI_DOOR                        "/door"
#define URI_DOORS                       "/doors"
#define URI_MOVEMENT                    "/movement"
#define URI_DB                          "/db"
#define URI_FILE                        "/file"
#define URI_LIST                        "/list"
#define URI_TRANSFER                    "/transfer"
#define URI_CONTENTS                    "/contents"
#define URI_PROVIDER                    "/provider"
#define URI_RENDERER                    "/renderer"
#define URI_PROVINFO                    "/provisioninginfo"

 /* Temperature Type Resources*/
#define URI_FRIDGE_COOLER               "/cooler"
#define URI_FRIDGE_FREEZER              "/freezer"
#define URI_FRIDGE_CVROOM               "/cvroom"
#define URI_FRIDGE_COMMON               "/common"

#define URI_OVEN_UPPER                  "/upper"
#define URI_OVEN_LOWER                  "/lower"
#define URI_OVEN_PROBE                  "/prob"

#define URI_ACCESSPOINTS                "/accesspoints"
#define URI_ACCESSPOINTLIST             "/accesspointlist"

/* Notification */
#define URI_NOTIFICATION                "/notification"
#define URI_PUSHSERVICE                 "/service/pushservice"
#define KEY_MESSAGE                     "message"
#define KEY_EXTRA                       "x.com.samsung.da.notification"
#define KEY_PUSH_CODE                   "x.com.samsung.code"
#define KEY_PUSH_DATA                   "x.com.samsung.data"
#define KEY_PUSH_DATA_ET                "et"

// It is used when you want to send notification in all value
#define ALLVALUE                        "ALLVALUE"

#define MAX_LEN_FILE_ID                  (10)
// Updated from 100 to 200 by DA's request
#define MAX_NUM_OICINFO                 (200)
#define MAX_NUM_OICFILE                  (10)
#define MAX_NUM_OICCONTENT              (100)
#define MAX_NUM_SCHEDULE                 (15)
#define MAX_NUM_AP                       (50)
#define MAX_NUM_OBJECT_ARRAY             (20)

#define MAX_NUM_AP                      50

#define MAX_NUM_OBJECT_ARRAY            20

//nikhil
#define MAX_ATTR_NUM                    32
#define TEMP_UNIT_CELSIUS               "Celsius"
#define TEMP_UNIT_FARENHITE             "Farenhite"
#define TEMP_UNIT_KELVIN                "Kelvin"
#define ATTRIBUTE_VALUE_LEN             20
#define URI_WASHER                      "/washer"
#define URI_CONNECTED                   "/connected"
#define SEC_ATTRIBUTE_CONNECTED         "x.com.samsung.da.connected"
#define MAX_URI_LENGTH                  256
#define SEC_RTYPE_ACCESSPOINTS_LIST     "x.com.samsung.accesspointlist"
#define SEC_ATTRIBUTE_SUMMER_TIME				"x.com.samsung.summertime"
#define SEC_ATTRIBUTE_TIME_OFFSET				"x.com.samsung.timeoffset"
#define SEC_ATTRIBUTE_SUPPRTED_TYPE			"x.com.samsung.supprtedtype"
#define URI_FILEINFORMATION							"/file/information"
#define SEC_RTYPE_FILE_INFORMATION      "x.com.samsung.file.information"
#define SEC_RTYPE_HASS_STATE						"x.com.samsung.da.hass.state"
#define SEC_RTYPE_HASS_COMMAND					"x.com.samsung.da.hass.command"
#define SEC_ATTRIBUTE_HASS_STATE				"x.com.samsung.da.hassState"
#define SEC_ATTRIBUTE_HASS_RESULT				"x.com.samsung.da.hassResult"
#define SEC_ATTRIBUTE_HASS_CLOSED				"x.com.samsung.da.hassClosed"
#define SEC_ATTRIBUTE_HASS_FILE_TRANS_RESULT      "x.com.samsung.da.fileTransResult"
#define SEC_ATTRIBUTE_HASS_COMMAND			"x.com.samsung.da.hassCommand"
#define SEC_ATTRIBUTE_HASS_LENGTH	      "x.com.samsung.da.hassLength"
#define URI_HASS												"/hass"
#define URI_CONSUMABLE                  "/consumable"
#define URI_CONSUMABLES                 "/consumables"
#define SEC_RTYPE_CONSUMABLE            "x.com.samsung.da.consumable"
#define SEC_RTYPE_HUMIDITY              "x.com.samsung.da.humidity"
#define SEC_ATTRIBUTE_POWER_LEVEL       "x.com.samsung.da.powerLevel"
#define SEC_ATTRIBUTE_HUMIDITY          "x.com.samsung.da.humidity"
#define SEC_ATTRIBUTE_DESIRED_HUMIDITY  "x.com.samsung.da.desiredHumidity"
#define SEC_RTYPE_MULTIDEVICE           "x.com.samsung.da.multidevice"
#define SEC_ATTRIBUTE_NUM_SUBDEVICE     "x.com.samsung.da.numofsubdevice"
#define URI_MULTIDEVICE                 "/multidevice"

#endif // _OIC_DEF_
