// Copyright 2022-2025 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This is a generated file, if you need to modify it, use the script to
// generate and modify all the struct.h, ll.h, reg.h, debug_dump.c files!

#pragma once


#ifdef __cplusplus
extern "C" {
#endif


#define IOMX_DEV_ID_ADDR (SOC_IOMX_REG_BASE + (0x0 << 2))

#define IOMX_DEV_ID_DEVICEID_POS (0)
#define IOMX_DEV_ID_DEVICEID_MASK (0xffffffff)

#define IOMX_VER_ID_ADDR (SOC_IOMX_REG_BASE + (0x1 << 2))

#define IOMX_VER_ID_VERSIONID_POS (0)
#define IOMX_VER_ID_VERSIONID_MASK (0xffffffff)

#define IOMX_CLKG_RESET_ADDR (SOC_IOMX_REG_BASE + (0x2 << 2))

#define IOMX_CLKG_RESET_SOFT_RESET_POS (0)
#define IOMX_CLKG_RESET_SOFT_RESET_MASK (0x1)

#define IOMX_CLKG_RESET_CLKG_BYPASS_POS (1)
#define IOMX_CLKG_RESET_CLKG_BYPASS_MASK (0x1)

#define IOMX_CLKG_RESET_GPIO_ATPG_RD_EN_POS (2)
#define IOMX_CLKG_RESET_GPIO_ATPG_RD_EN_MASK (0x1)

#define IOMX_CLKG_RESET_RESERVED_BIT_3_31_POS (3)
#define IOMX_CLKG_RESET_RESERVED_BIT_3_31_MASK (0x1fffffff)

#define IOMX_DEV_STATUS_ADDR (SOC_IOMX_REG_BASE + (0x3 << 2))

#define IOMX_DEV_STATUS_DEVSTATUS_POS (0)
#define IOMX_DEV_STATUS_DEVSTATUS_MASK (0xffffffff)


/* GPIO CONFIG
 */
#define IOMX_GPIO_CFG_ADDR (SOC_IOMX_REG_BASE + (0x40 << 2))

#define IOMX_GPIO_CFG_GPIO_INPUT_POS (0)
#define IOMX_GPIO_CFG_GPIO_INPUT_MASK (0x1)

#define IOMX_GPIO_CFG_GPIO_OUTPUT_POS (1)
#define IOMX_GPIO_CFG_GPIO_OUTPUT_MASK (0x1)

#define IOMX_GPIO_CFG_RESV4_POS (2)
#define IOMX_GPIO_CFG_RESV4_MASK (0x1)

#define IOMX_GPIO_CFG_RESV3_POS (3)
#define IOMX_GPIO_CFG_RESV3_MASK (0x1)

#define IOMX_GPIO_CFG_GPIO_PULL_MODE_POS (4)
#define IOMX_GPIO_CFG_GPIO_PULL_MODE_MASK (0x1)

#define IOMX_GPIO_CFG_GPIO_PULL_ENA_POS (5)
#define IOMX_GPIO_CFG_GPIO_PULL_ENA_MASK (0x1)

#define IOMX_GPIO_CFG_RESV2_POS (6)
#define IOMX_GPIO_CFG_RESV2_MASK (0x1)

#define IOMX_GPIO_CFG_INPUT_MONITOR_POS (7)
#define IOMX_GPIO_CFG_INPUT_MONITOR_MASK (0x1)

#define IOMX_GPIO_CFG_GPIO_CAPACITY_POS (8)
#define IOMX_GPIO_CFG_GPIO_CAPACITY_MASK (0x3)

#define IOMX_GPIO_CFG_GPIO_INT_TYPE_POS (10)
#define IOMX_GPIO_CFG_GPIO_INT_TYPE_MASK (0x3)

#define IOMX_GPIO_CFG_GPIO_INT_ENA_POS (12)
#define IOMX_GPIO_CFG_GPIO_INT_ENA_MASK (0x1)

#define IOMX_GPIO_CFG_GPIO_INT_CLEAR_POS (13)
#define IOMX_GPIO_CFG_GPIO_INT_CLEAR_MASK (0x1)

#define IOMX_GPIO_CFG_RESV1_POS (14)
#define IOMX_GPIO_CFG_RESV1_MASK (0x3)

#define IOMX_GPIO_CFG_GPIO_STATE_POS (16)
#define IOMX_GPIO_CFG_GPIO_STATE_MASK (0x1f)

#define IOMX_GPIO_CFG_RESV0_POS (21)
#define IOMX_GPIO_CFG_RESV0_MASK (0x7)

#define IOMX_GPIO_CFG_GPIO_FUNC_SEL_POS (24)
#define IOMX_GPIO_CFG_GPIO_FUNC_SEL_MASK (0xff)

#define IOMX_GPIO0_CFG_ADDR (SOC_IOMX_REG_BASE + (0x40 << 2))

#define IOMX_GPIO0_CFG_GPIO_INPUT_POS (0)
#define IOMX_GPIO0_CFG_GPIO_INPUT_MASK (0x1)

#define IOMX_GPIO0_CFG_GPIO_OUTPUT_POS (1)
#define IOMX_GPIO0_CFG_GPIO_OUTPUT_MASK (0x1)

#define IOMX_GPIO0_CFG_RESV4_POS (2)
#define IOMX_GPIO0_CFG_RESV4_MASK (0x1)

#define IOMX_GPIO0_CFG_RESV3_POS (3)
#define IOMX_GPIO0_CFG_RESV3_MASK (0x1)

#define IOMX_GPIO0_CFG_GPIO_PULL_MODE_POS (4)
#define IOMX_GPIO0_CFG_GPIO_PULL_MODE_MASK (0x1)

#define IOMX_GPIO0_CFG_GPIO_PULL_ENA_POS (5)
#define IOMX_GPIO0_CFG_GPIO_PULL_ENA_MASK (0x1)

#define IOMX_GPIO0_CFG_RESV2_POS (6)
#define IOMX_GPIO0_CFG_RESV2_MASK (0x1)

#define IOMX_GPIO0_CFG_INPUT_MONITOR_POS (7)
#define IOMX_GPIO0_CFG_INPUT_MONITOR_MASK (0x1)

#define IOMX_GPIO0_CFG_GPIO_CAPACITY_POS (8)
#define IOMX_GPIO0_CFG_GPIO_CAPACITY_MASK (0x3)

#define IOMX_GPIO0_CFG_GPIO_INT_TYPE_POS (10)
#define IOMX_GPIO0_CFG_GPIO_INT_TYPE_MASK (0x3)

#define IOMX_GPIO0_CFG_GPIO_INT_ENA_POS (12)
#define IOMX_GPIO0_CFG_GPIO_INT_ENA_MASK (0x1)

#define IOMX_GPIO0_CFG_GPIO_INT_CLEAR_POS (13)
#define IOMX_GPIO0_CFG_GPIO_INT_CLEAR_MASK (0x1)

#define IOMX_GPIO0_CFG_RESV1_POS (14)
#define IOMX_GPIO0_CFG_RESV1_MASK (0x3)

#define IOMX_GPIO0_CFG_GPIO_STATE_POS (16)
#define IOMX_GPIO0_CFG_GPIO_STATE_MASK (0x1f)

#define IOMX_GPIO0_CFG_RESV0_POS (21)
#define IOMX_GPIO0_CFG_RESV0_MASK (0x7)

#define IOMX_GPIO0_CFG_GPIO_FUNC_SEL_POS (24)
#define IOMX_GPIO0_CFG_GPIO_FUNC_SEL_MASK (0xff)

#define IOMX_GPIO1_CFG_ADDR (SOC_IOMX_REG_BASE + (0x41 << 2))

#define IOMX_GPIO1_CFG_GPIO1_CONFIG_POS (0)
#define IOMX_GPIO1_CFG_GPIO1_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO2_CFG_ADDR (SOC_IOMX_REG_BASE + (0x42 << 2))

#define IOMX_GPIO2_CFG_GPIO2_CONFIG_POS (0)
#define IOMX_GPIO2_CFG_GPIO2_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO3_CFG_ADDR (SOC_IOMX_REG_BASE + (0x43 << 2))

#define IOMX_GPIO3_CFG_GPIO3_CONFIG_POS (0)
#define IOMX_GPIO3_CFG_GPIO3_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO4_CFG_ADDR (SOC_IOMX_REG_BASE + (0x44 << 2))

#define IOMX_GPIO4_CFG_GPIO4_CONFIG_POS (0)
#define IOMX_GPIO4_CFG_GPIO4_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO5_CFG_ADDR (SOC_IOMX_REG_BASE + (0x45 << 2))

#define IOMX_GPIO5_CFG_GPIO5_CONFIG_POS (0)
#define IOMX_GPIO5_CFG_GPIO5_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO6_CFG_ADDR (SOC_IOMX_REG_BASE + (0x46 << 2))

#define IOMX_GPIO6_CFG_GPIO6_CONFIG_POS (0)
#define IOMX_GPIO6_CFG_GPIO6_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO7_CFG_ADDR (SOC_IOMX_REG_BASE + (0x47 << 2))

#define IOMX_GPIO7_CFG_GPIO7_CONFIG_POS (0)
#define IOMX_GPIO7_CFG_GPIO7_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO8_CFG_ADDR (SOC_IOMX_REG_BASE + (0x48 << 2))

#define IOMX_GPIO8_CFG_GPIO8_CONFIG_POS (0)
#define IOMX_GPIO8_CFG_GPIO8_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO9_CFG_ADDR (SOC_IOMX_REG_BASE + (0x49 << 2))

#define IOMX_GPIO9_CFG_GPIO9_CONFIG_POS (0)
#define IOMX_GPIO9_CFG_GPIO9_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO10_CFG_ADDR (SOC_IOMX_REG_BASE + (0x4A << 2))

#define IOMX_GPIO10_CFG_GPIO10_CONFIG_POS (0)
#define IOMX_GPIO10_CFG_GPIO10_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO11_CFG_ADDR (SOC_IOMX_REG_BASE + (0x4B << 2))

#define IOMX_GPIO11_CFG_GPIO11_CONFIG_POS (0)
#define IOMX_GPIO11_CFG_GPIO11_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO12_CFG_ADDR (SOC_IOMX_REG_BASE + (0x4C << 2))

#define IOMX_GPIO12_CFG_GPIO12_CONFIG_POS (0)
#define IOMX_GPIO12_CFG_GPIO12_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO13_CFG_ADDR (SOC_IOMX_REG_BASE + (0x4D << 2))

#define IOMX_GPIO13_CFG_GPIO13_CONFIG_POS (0)
#define IOMX_GPIO13_CFG_GPIO13_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO14_CFG_ADDR (SOC_IOMX_REG_BASE + (0x4E << 2))

#define IOMX_GPIO14_CFG_GPIO14_CONFIG_POS (0)
#define IOMX_GPIO14_CFG_GPIO14_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO15_CFG_ADDR (SOC_IOMX_REG_BASE + (0x4F << 2))

#define IOMX_GPIO15_CFG_GPIO15_CONFIG_POS (0)
#define IOMX_GPIO15_CFG_GPIO15_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO16_CFG_ADDR (SOC_IOMX_REG_BASE + (0x50 << 2))

#define IOMX_GPIO16_CFG_GPIO16_CONFIG_POS (0)
#define IOMX_GPIO16_CFG_GPIO16_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO17_CFG_ADDR (SOC_IOMX_REG_BASE + (0x51 << 2))

#define IOMX_GPIO17_CFG_GPIO17_CONFIG_POS (0)
#define IOMX_GPIO17_CFG_GPIO17_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO18_CFG_ADDR (SOC_IOMX_REG_BASE + (0x52 << 2))

#define IOMX_GPIO18_CFG_GPIO18_CONFIG_POS (0)
#define IOMX_GPIO18_CFG_GPIO18_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO19_CFG_ADDR (SOC_IOMX_REG_BASE + (0x53 << 2))

#define IOMX_GPIO19_CFG_GPIO19_CONFIG_POS (0)
#define IOMX_GPIO19_CFG_GPIO19_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO20_CFG_ADDR (SOC_IOMX_REG_BASE + (0x54 << 2))

#define IOMX_GPIO20_CFG_GPIO20_CONFIG_POS (0)
#define IOMX_GPIO20_CFG_GPIO20_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO21_CFG_ADDR (SOC_IOMX_REG_BASE + (0x55 << 2))

#define IOMX_GPIO21_CFG_GPIO21_CONFIG_POS (0)
#define IOMX_GPIO21_CFG_GPIO21_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO22_CFG_ADDR (SOC_IOMX_REG_BASE + (0x56 << 2))

#define IOMX_GPIO22_CFG_GPIO22_CONFIG_POS (0)
#define IOMX_GPIO22_CFG_GPIO22_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO23_CFG_ADDR (SOC_IOMX_REG_BASE + (0x57 << 2))

#define IOMX_GPIO23_CFG_GPIO23_CONFIG_POS (0)
#define IOMX_GPIO23_CFG_GPIO23_CONFIG_MASK (0xffffffff)

#define IOMX_GPIO_INTSTA_ADDR (SOC_IOMX_REG_BASE + (0xc0 << 2))

#define IOMX_GPIO_INTSTA_GPIO_INTSTA_POS (0)
#define IOMX_GPIO_INTSTA_GPIO_INTSTA_MASK (0xffffff)

#define IOMX_GPIO_INTSTA_RESERVED_24_31_POS (24)
#define IOMX_GPIO_INTSTA_RESERVED_24_31_MASK (0xff)

#define IOMX_GPIO_INPUT_ADDR (SOC_IOMX_REG_BASE + (0xc4 << 2))

#define IOMX_GPIO_INPUT_GPIO_INPUT_POS (0)
#define IOMX_GPIO_INPUT_GPIO_INPUT_MASK (0xffffff)

#define IOMX_GPIO_INPUT_RESERVED_24_31_POS (24)
#define IOMX_GPIO_INPUT_RESERVED_24_31_MASK (0xff)

#define IOMX_GPIO_OUTPUT_ADDR (SOC_IOMX_REG_BASE + (0xc8 << 2))

#define IOMX_GPIO_OUTPUT_GPIO_OUTPUT_POS (0)
#define IOMX_GPIO_OUTPUT_GPIO_OUTPUT_MASK (0xffffff)

#define IOMX_GPIO_OUTPUT_RESERVED_24_31_POS (24)
#define IOMX_GPIO_OUTPUT_RESERVED_24_31_MASK (0xff)

#define IOMX_GPIO_FUNC_O_ATPG_ADDR (SOC_IOMX_REG_BASE + (0xcc << 2))

#define IOMX_GPIO_FUNC_O_ATPG_GPIO_FUNC_O_ATPG_POS (0)
#define IOMX_GPIO_FUNC_O_ATPG_GPIO_FUNC_O_ATPG_MASK (0xffffff)

#define IOMX_GPIO_FUNC_O_ATPG_RESERVED_24_31_POS (24)
#define IOMX_GPIO_FUNC_O_ATPG_RESERVED_24_31_MASK (0xff)

#define IOMX_GPIO_FUNC_IE_ATPG_ADDR (SOC_IOMX_REG_BASE + (0xd0 << 2))

#define IOMX_GPIO_FUNC_IE_ATPG_GPIO_FUNC_IE_ATPG_POS (0)
#define IOMX_GPIO_FUNC_IE_ATPG_GPIO_FUNC_IE_ATPG_MASK (0xffffff)

#define IOMX_GPIO_FUNC_IE_ATPG_RESERVED_24_31_POS (24)
#define IOMX_GPIO_FUNC_IE_ATPG_RESERVED_24_31_MASK (0xff)

#define IOMX_GPIO_FUNC_OEN_ATPG_ADDR (SOC_IOMX_REG_BASE + (0xd4 << 2))

#define IOMX_GPIO_FUNC_OEN_ATPG_GPIO_FUNC_OEN_ATPG_POS (0)
#define IOMX_GPIO_FUNC_OEN_ATPG_GPIO_FUNC_OEN_ATPG_MASK (0xffffff)

#define IOMX_GPIO_FUNC_OEN_ATPG_RESERVED_24_31_POS (24)
#define IOMX_GPIO_FUNC_OEN_ATPG_RESERVED_24_31_MASK (0xff)

#ifdef __cplusplus
}
#endif
