// Copyright 2020-2025 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#define SDIO_HOST_R_BASE                    (SOC_SDIO_REG_BASE)

#define SDIO_HOST_R_DATA_CTRL               (SDIO_HOST_R_BASE + 4 * 0x7)

#define SDIO_HOST_F_DATA_BLOCK_SIZE         (BIT(4))
#define SDIO_HOST_F_DATA_BLOCK_SIZE_M       (0xfff)
#define SDIO_HOST_F_DATA_BLOCK_SIZE_V       (0xfff)
#define SDIO_HOST_F_DATA_BLOCK_SIZE_S       (4)

#define SDIO_HOST_R_CMD_RSP_INT_SEL         (SDIO_HOST_R_BASE + 4 * 0xd)

#define SDIO_HOST_F_CMD_NO_RSP_END_INT      (BIT(0))
#define SDIO_HOST_F_CMD_NO_RSP_END_INT_M    (0x1)
#define SDIO_HOST_F_CMD_NO_RSP_END_INT_V    (0x1)
#define SDIO_HOST_F_CMD_NO_RSP_END_INT_S    (0)

#define SDIO_HOST_F_CMD_RSP_END_INT         (BIT(1))
#define SDIO_HOST_F_CMD_RSP_END_INT_M       (0x1)
#define SDIO_HOST_F_CMD_RSP_END_INT_V       (0x1)
#define SDIO_HOST_F_CMD_RSP_END_INT_S       (1)

#define SDIO_HOST_F_CMD_RSP_TIMEOUT_INT     (BIT(2))
#define SDIO_HOST_F_CMD_RSP_TIMEOUT_INT_M   (0x1)
#define SDIO_HOST_F_CMD_RSP_TIMEOUT_INT_V   (0x1)
#define SDIO_HOST_F_CMD_RSP_TIMEOUT_INT_S   (2)

#define SDIO_HOST_F_DATA_RECV_END_INT       (BIT(3))
#define SDIO_HOST_F_DATA_RECV_END_INT_M     (0x1)
#define SDIO_HOST_F_DATA_RECV_END_INT_V     (0x1)
#define SDIO_HOST_F_DATA_RECV_END_INT_S     (3)

#define SDIO_HOST_F_DATA_WR_END_INT         (BIT(4))
#define SDIO_HOST_F_DATA_WR_END_INT_M       (0x1)
#define SDIO_HOST_F_DATA_WR_END_INT_V       (0x1)
#define SDIO_HOST_F_DATA_WR_END_INT_S       (4)

#define SDIO_HOST_F_DATA_TIMEOUT_INT        (BIT(5))
#define SDIO_HOST_F_DATA_TIMEOUT_INT_M      (0x1)
#define SDIO_HOST_F_DATA_TIMEOUT_INT_V      (0x1)
#define SDIO_HOST_F_DATA_TIMEOUT_INT_S      (5)

#define SDIO_HOST_F_RX_FIFO_NEED_READ       (BIT(6))
#define SDIO_HOST_F_RX_FIFO_NEED_READ_M     (0x1)
#define SDIO_HOST_F_RX_FIFO_NEED_READ_V     (0x1)
#define SDIO_HOST_F_RX_FIFO_NEED_READ_S     (6)

#define SDIO_HOST_F_TX_FIFO_NEED_WRITE      (BIT(7))
#define SDIO_HOST_F_TX_FIFO_NEED_WRITE_M    (0x1)
#define SDIO_HOST_F_TX_FIFO_NEED_WRITE_V    (0x1)
#define SDIO_HOST_F_TX_FIFO_NEED_WRITE_S    (7)

#define SDIO_HOST_F_FIFO_OVERFLOW_INT       (BIT(8))
#define SDIO_HOST_F_FIFO_OVERFLOW_INT_M     (0x1)
#define SDIO_HOST_F_FIFO_OVERFLOW_INT_V     (0x1)
#define SDIO_HOST_F_FIFO_OVERFLOW_INT_S     (8)

#define SDIO_HOST_F_FIFO_EMPTY_INT          (BIT(9))
#define SDIO_HOST_F_FIFO_EMPTY_INT_M        (0x1)
#define SDIO_HOST_F_FIFO_EMPTY_INT_V        (0x1)
#define SDIO_HOST_F_FIFO_EMPTY_INT_S        (9)

#define SDIO_HOST_F_CMD_RSP_CRC_OK          (BIT(10))
#define SDIO_HOST_F_CMD_RSP_CRC_OK_M        (0x1)
#define SDIO_HOST_F_CMD_RSP_CRC_OK_V        (0x1)
#define SDIO_HOST_F_CMD_RSP_CRC_OK_S        (10)

#define SDIO_HOST_F_CMD_RSP_CRC_FAIL        (BIT(11))
#define SDIO_HOST_F_CMD_RSP_CRC_FAIL_M      (0x1)
#define SDIO_HOST_F_CMD_RSP_CRC_FAIL_V      (0x1)
#define SDIO_HOST_F_CMD_RSP_CRC_FAIL_S      (11)

#define SDIO_HOST_F_DATA_CRC_OK             (BIT(12))
#define SDIO_HOST_F_DATA_CRC_OK_M           (0x1)
#define SDIO_HOST_F_DATA_CRC_OK_V           (0x1)
#define SDIO_HOST_F_DATA_CRC_OK_S           (13)

#define SDIO_HOST_F_DATA_CRC_FAIL           (BIT(13))
#define SDIO_HOST_F_DATA_CRC_FAIL_M         (0x1)
#define SDIO_HOST_F_DATA_CRC_FAIL_V         (0x1)
#define SDIO_HOST_F_DATA_CRC_FAIL_S         (13)

#define SDIO_HOST_F_CMD_RSP_INDEX           (BIT(14))
#define SDIO_HOST_F_CMD_RSP_INDEX_M         (0x3f)
#define SDIO_HOST_F_CMD_RSP_INDEX_V         (0x3f)
#define SDIO_HOST_F_CMD_RSP_INDEX_S         (14)

#define SDIO_HOST_R_CMD_RSP_INT_MASK        (SDIO_HOST_R_BASE + 4 * 0xe)

/* REG_0x00 */
#define SDIO_REG0X0_ADDR  (SOC_SDIO_REG_BASE  + 0x0*4) //REG ADDR :0x448b0000

/* REG_0x01 */
#define SDIO_REG0X1_ADDR  (SOC_SDIO_REG_BASE  + 0x1*4) //REG ADDR :0x448b0004

/* REG_0x02 */
#define SDIO_REG0X2_ADDR  (SOC_SDIO_REG_BASE  + 0x2*4) //REG ADDR :0x448b0008
#define SDIO_SD_SOFT_RESETN_POS (0)
#define SDIO_SD_SOFT_RESETN_MASK (0x1)


/* REG_0x03 */
#define SDIO_REG0X3_ADDR  (SOC_SDIO_REG_BASE  + 0x3*4) //REG ADDR :0x448b000c

/* REG_0x04 */
#define SDIO_REG0X4_ADDR  (SOC_SDIO_REG_BASE  + 0x4*4) //REG ADDR :0x458d0010
#define SDIO_SD_CMD_START_POS (0)
#define SDIO_SD_CMD_START_MASK (0x1)

#define SDIO_SD_CMD_RSP_POS (1)
#define SDIO_SD_CMD_RSP_MASK (0x1)

#define SDIO_SD_CMD_LONG_POS (2)
#define SDIO_SD_CMD_LONG_MASK (0x1)

#define SDIO_SD_CMD_CRC_CHECK_POS (3)
#define SDIO_SD_CMD_CRC_CHECK_MASK (0x1)

#define SDIO_CMD_INDEX_POS (4)
#define SDIO_CMD_INDEX_MASK (0x3F)

#define SDIO_REG0X4_RESERVED0_POS (10)
#define SDIO_REG0X4_RESERVED0_MASK (0x3FFFFF)

/* REG_0x05 */
#define SDIO_REG0X5_ADDR  (SOC_SDIO_REG_BASE  + 0x5*4) //REG ADDR :0x458d0014
#define SDIO_CMD_ARGUMENT_POS (0)
#define SDIO_CMD_ARGUMENT_MASK (0xFFFFFFFF)

/* REG_0x06 */
#define SDIO_REG0X6_ADDR  (SOC_SDIO_REG_BASE  + 0x6*4) //REG ADDR :0x458d0018
#define SDIO_SD_CMD_TIMER_POS (0)
#define SDIO_SD_CMD_TIMER_MASK (0xFFFFFFFF)

/* REG_0x07 */
#define SDIO_REG0X7_ADDR  (SOC_SDIO_REG_BASE  + 0x7*4) //REG ADDR :0x458d001c
#define SDIO_SD_DATA_EN_POS (0)
#define SDIO_SD_DATA_EN_MASK (0x1)

#define SDIO_SD_DATA_STOP_EN_POS (1)
#define SDIO_SD_DATA_STOP_EN_MASK (0x1)

#define SDIO_SD_DATA_BUS_POS (2)
#define SDIO_SD_DATA_BUS_MASK (0x1)

#define SDIO_SD_DATA_MUL_BLK_POS (3)
#define SDIO_SD_DATA_MUL_BLK_MASK (0x1)

#define SDIO_SD_DATA_BLK_SIZE_POS (4)
#define SDIO_SD_DATA_BLK_SIZE_MASK (0xFFF)

#define SDIO_SD_START_WR_EN_POS (16)
#define SDIO_SD_START_WR_EN_MASK (0x1)

#define SDIO_SD_BYTE_SEL_POS (17)
#define SDIO_SD_BYTE_SEL_MASK (0x1)

#define SDIO_SD_TX_BYTE_SEL_POS (18)
#define SDIO_SD_TX_BYTE_SEL_MASK (0x1)

#define SDIO_REG0X7_RESERVED0_POS (19)
#define SDIO_REG0X7_RESERVED0_MASK (0x1FFF)

/* REG_0x08 */
#define SDIO_REG0X8_ADDR  (SOC_SDIO_REG_BASE  + 0x8*4) //REG ADDR :0x458d0020
#define SDIO_SD_DATA_TIMER_POS (0)
#define SDIO_SD_DATA_TIMER_MASK (0xFFFFFFFF)

/* REG_0x09 */
#define SDIO_REG0X9_ADDR  (SOC_SDIO_REG_BASE  + 0x9*4) //REG ADDR :0x458d0024
#define SDIO_SD_RSP_AGUMENT_0_POS (0)
#define SDIO_SD_RSP_AGUMENT_0_MASK (0xFFFFFFFF)

/* REG_0x0A */
#define SDIO_REG0XA_ADDR  (SOC_SDIO_REG_BASE  + 0xa*4) //REG ADDR :0x458d0028
#define SDIO_SD_RSP_AGUMENT_1_POS (0)
#define SDIO_SD_RSP_AGUMENT_1_MASK (0xFFFFFFFF)

/* REG_0x0B */
#define SDIO_REG0XB_ADDR  (SOC_SDIO_REG_BASE  + 0xb*4) //REG ADDR :0x458d002c
#define SDIO_SD_RSP_AGUMENT_2_POS (0)
#define SDIO_SD_RSP_AGUMENT_2_MASK (0xFFFFFFFF)

/* REG_0x0c */
#define SDIO_REG0XC_ADDR  (SOC_SDIO_REG_BASE  + 0xc*4) //REG ADDR :0x458d0030
#define SDIO_SD_RSP_AGUMENT_3_POS (0)
#define SDIO_SD_RSP_AGUMENT_3_MASK (0xFFFFFFFF)


/* REG_0x0D */
#define SDIO_REG0XD_ADDR  (SOC_SDIO_REG_BASE  + 0xD*4) //REG ADDR :0x458d0034
#define SDIO_SD_CMD_SEND_NORSP_END_INT_POS (0)
#define SDIO_SD_CMD_SEND_NORSP_END_INT_MASK (0x1)

#define SDIO_SD_CMD_SEND_RSP_END_INT_POS (1)
#define SDIO_SD_CMD_SEND_RSP_END_INT_MASK (0x1)

#define SDIO_SD_CMD_SEND_RSP_TIMEOUT_INT_POS (2)
#define SDIO_SD_CMD_SEND_RSP_TIMEOUT_INT_MASK (0x1)

#define SDIO_SD_DATA_REC_END_INT_POS (3)
#define SDIO_SD_DATA_REC_END_INT_MASK (0x1)

#define SDIO_SD_DATA_WR_END_INT_POS (4)
#define SDIO_SD_DATA_WR_END_INT_MASK (0x1)

#define SDIO_SD_DATA_TIME_OUT_INT_POS (5)
#define SDIO_SD_DATA_TIME_OUT_INT_MASK (0x1)

#define SDIO_RX_FIFO_NEED_READ_POS (6)
#define SDIO_RX_FIFO_NEED_READ_MASK (0x1)

#define SDIO_TX_FIFO_NEED_WRITE_POS (7)
#define SDIO_TX_FIFO_NEED_WRITE_MASK (0x1)

#define SDIO_RX_OV_POS (8)
#define SDIO_RX_OV_MASK (0x1)

#define SDIO_TX_FIFO_EMPT_POS (9)
#define SDIO_TX_FIFO_EMPT_MASK (0x1)

#define SDIO_SD_RSP_CMD_CRC_OK_POS (10)
#define SDIO_SD_RSP_CMD_CRC_OK_MASK (0x1)

#define SDIO_SD_RSP_CMD_CRC_FAIL_POS (11)
#define SDIO_SD_RSP_CMD_CRC_FAIL_MASK (0x1)

#define SDIO_SD_DATA_CRC_OK_POS (12)
#define SDIO_SD_DATA_CRC_OK_MASK (0x1)

#define SDIO_SD_DATA_CRC_FAIL_POS (13)
#define SDIO_SD_DATA_CRC_FAIL_MASK (0x1)

#define SDIO_SD_RSP_INDEX_POS (14)
#define SDIO_SD_RSP_INDEX_MASK (0x3F)

#define SDIO_WR_STATUS_POS (20)
#define SDIO_WR_STATUS_MASK (0x7)

#define SDIO_DATA_BUSY_POS (23)
#define SDIO_DATA_BUSY_MASK (0x1)

#define SDIO_CMD_S_RES_END_INT_POS (24)
#define SDIO_CMD_S_RES_END_INT_MASK (0x1)

#define SDIO_DAT_S_WR_WAI_INT_POS (25)
#define SDIO_DAT_S_WR_WAI_INT_MASK (0x1)

#define SDIO_DAT_S_RD_BUS_INT_POS (26)
#define SDIO_DAT_S_RD_BUS_INT_MASK (0x1)

#define SDIO_DAT_WRSTS_ERR_INT_POS (27)
#define SDIO_DAT_WRSTS_ERR_INT_MASK (0x1)

#define SDIO_DAT_CRC_FAIL_INT_POS (28)
#define SDIO_DAT_CRC_FAIL_INT_MASK (0x1)

#define SDIO_DAT_S_WR_BLK_INT_POS (29)
#define SDIO_DAT_S_WR_BLK_INT_MASK (0x1)

#define SDIO_REG0XD_RESERVED0_POS (30)
#define SDIO_REG0XD_RESERVED0_MASK (0x3)


/* REG_0x0E */
#define SDIO_REG0XE_ADDR  (SOC_SDIO_REG_BASE + 0xE*4) //REG ADDR :0x458d0038
#define SDIO_SD_CMD_SEND_NORSP_END_MASK_POS (0)
#define SDIO_SD_CMD_SEND_NORSP_END_MASK_MASK (0x1)

#define SDIO_SD_CMD_SEND_RSP_END_MASK_POS (1)
#define SDIO_SD_CMD_SEND_RSP_END_MASK_MASK (0x1)

#define SDIO_SD_CMD_SEND_RSP_TIMEOUT_MASK_POS (2)
#define SDIO_SD_CMD_SEND_RSP_TIMEOUT_MASK_MASK (0x1)

#define SDIO_SD_DATA_REC_END_MASK_POS (3)
#define SDIO_SD_DATA_REC_END_MASK_MASK (0x1)

#define SDIO_SD_DATA_WR_END_MASK_POS (4)
#define SDIO_SD_DATA_WR_END_MASK_MASK (0x1)

#define SDIO_SD_DATA_TIME_OUT_MASK_POS (5)
#define SDIO_SD_DATA_TIME_OUT_MASK_MASK (0x1)

#define SDIO_RX_FIFO_NEED_READ_MASK_POS (6)
#define SDIO_RX_FIFO_NEED_READ_MASK_MASK (0x1)

#define SDIO_TX_FIFO_NEED_WRITE_MASK_POS (7)
#define SDIO_TX_FIFO_NEED_WRITE_MASK_MASK (0x1)

#define SDIO_RX_OV_MASK_POS (8)
#define SDIO_RX_OV_MASK_MASK (0x1)

#define SDIO_TX_FIFO_EMPT_MASK_POS (9)
#define SDIO_TX_FIFO_EMPT_MASK_MASK (0x1)

#define SDIO_CMD_S_RES_END_INT_MASK_POS (10)
#define SDIO_CMD_S_RES_END_INT_MASK_MASK (0x1)

#define SDIO_DAT_S_WR_WAI_INT_MASK_POS (11)
#define SDIO_DAT_S_WR_WAI_INT_MASK_MASK (0x1)

#define SDIO_DAT_S_RD_BUS_INT_MASK_POS (12)
#define SDIO_DAT_S_RD_BUS_INT_MASK_MASK (0x1)

#define SDIO_TX_FIFO_NEED_WRITE_MASK_CG_POS (13)
#define SDIO_TX_FIFO_NEED_WRITE_MASK_CG_MASK (0x1)

#define SDIO_WRITE_WAIT_JUMP_SEL_POS (14)
#define SDIO_WRITE_WAIT_JUMP_SEL_MASK (0x1)

#define SDIO_IDLE_STOP_JUMP_SEL_POS (15)
#define SDIO_IDLE_STOP_JUMP_SEL_MASK (0x1)

#define SDIO_WRSTS_ERR_INT_MASK_POS (16)
#define SDIO_WRSTS_ERR_INT_MASK_MASK (0x1)

#define SDIO_CRC_FAIL_INT_MASK_POS (17)
#define SDIO_CRC_FAIL_INT_MASK_MASK (0x1)

#define SDIO_SLAVE_WRITE_BLOCK_INT_MASK_POS (18)
#define SDIO_SLAVE_WRITE_BLOCK_INT_MASK_MASK (0x1)

#define SDIO_SLAVE_READ_MUL_SEL_POS (19)
#define SDIO_SLAVE_READ_MUL_SEL_MASK (0x1)

#define SDIO_SLAVE_WRITE_MUL_SEL_POS (20)
#define SDIO_SLAVE_WRITE_MUL_SEL_MASK (0x1)

#define SDIO_REG0XE_RESERVED0_POS (21)
#define SDIO_REG0XE_RESERVED0_MASK (0x3FF)

/* REG_0x0f */
#define SDIO_REG0XF_ADDR  (SOC_SDIO_REG_BASE + 0xF*4) //REG ADDR :0x458d003c
#define SDIO_TX_FIFO_DIN_POS (0)
#define SDIO_TX_FIFO_DIN_MASK (0xFFFFFFFF)

/* REG_0x010 */
#define SDIO_REG0X10_ADDR  (SOC_SDIO_REG_BASE + 0x10*4) //REG ADDR :0x458d0040
#define SDIO_RX_FIFO_DOUT_POS (0)
#define SDIO_RX_FIFO_DOUT_MASK (0xFFFFFFFF)

/* REG_0x011 */
#define SDIO_REG0X11_ADDR  (SOC_SDIO_REG_BASE + 0x11*4) //REG ADDR :0x458d0044
#define SDIO_RX_FIFO_THRESHOLD_POS (0)
#define SDIO_RX_FIFO_THRESHOLD_MASK (0xFF)

#define SDIO_TX_FIFO_THRESHOLD_POS (8)
#define SDIO_TX_FIFO_THRESHOLD_MASK (0xFF)

#define SDIO_RX_FIFO_RST_POS (16)
#define SDIO_RX_FIFO_RST_MASK (0x1)

#define SDIO_TX_FIFO_RST_POS (17)
#define SDIO_TX_FIFO_RST_MASK (0x1)

#define SDIO_RXFIFO_RD_READY_POS (18)
#define SDIO_RXFIFO_RD_READY_MASK (0x1)

#define SDIO_TXFIFO_WR_READY_POS (19)
#define SDIO_TXFIFO_WR_READY_MASK (0x1)

#define SDIO_SD_STA_RST_POS (20)
#define SDIO_SD_STA_RST_MASK (0x1)

#define SDIO_SD_CLK_SEL_POS (21)
#define SDIO_SD_CLK_SEL_MASK (0x3)

#define SDIO_SD_RD_WAIT_SEL_POS (23)
#define SDIO_SD_RD_WAIT_SEL_MASK (0x1)

#define SDIO_SD_WR_WAIT_SEL_POS (24)
#define SDIO_SD_WR_WAIT_SEL_MASK (0x1)

#define SDIO_CLK_REC_SEL_POS (25)
#define SDIO_CLK_REC_SEL_MASK (0x1)

#define SDIO_SAMP_SEL_POS (26)
#define SDIO_SAMP_SEL_MASK (0x1)

#define SDIO_CLK_GATE_ON_POS (27)
#define SDIO_CLK_GATE_ON_MASK (0x1)

#define SDIO_HOST_WR_BLK_EN_POS (28)
#define SDIO_HOST_WR_BLK_EN_MASK (0x1)

#define SDIO_HOST_RD_BLK_EN_POS (29)
#define SDIO_HOST_RD_BLK_EN_MASK (0x1)

#define SDIO_REG0X11_RESERVED0_POS (30)
#define SDIO_REG0X11_RESERVED0_MASK (0x3)

/* REG_0x12 */
#define SDIO_REG0X12_ADDR  (SOC_SDIO_REG_BASE + 0x12*4) //REG ADDR :0x458d0048
#define SDIO_SD_SLAVE_POS (0)
#define SDIO_SD_SLAVE_MASK (0x1)

#define SDIO_DAT_S_RD_MUL_BLK_POS (1)
#define SDIO_DAT_S_RD_MUL_BLK_MASK (0x1)

#define SDIO_IO_CUR_STA_REG_POS (2)
#define SDIO_IO_CUR_STA_REG_MASK (0x3)

#define SDIO_CMD_52_STOP_CLR_POS (4)
#define SDIO_CMD_52_STOP_CLR_MASK (0x1)

#define SDIO_CMD_KEEP_DET_POS (5)
#define SDIO_CMD_KEEP_DET_MASK (0x1)

#define SDIO_REG0X12_RESERVED0_POS (6)
#define SDIO_REG0X12_RESERVED0_MASK (0x3)

#define SDIO_FIFO_SEND_CNT_POS (8)
#define SDIO_FIFO_SEND_CNT_MASK (0xFF)

#define SDIO_REG0X12_RESERVED1_POS (16)
#define SDIO_REG0X12_RESERVED1_MASK (0xFFFF)

/* REG_0x13 */
#define SDIO_REG0X13_ADDR  (SOC_SDIO_REG_BASE + 0x13*4) //REG ADDR :0x458d004c
#define SDIO_SD_SLAVE_RDAT_0_POS (0)
#define SDIO_SD_SLAVE_RDAT_0_MASK (0xFFFFFFFF)

	/* REG_0x14 */
#define SDIO_REG0X14_ADDR  (SOC_SDIO_REG_BASE + 0x14*4) //REG ADDR :0x458d0050
#define SDIO_SD_SLAVE_RDAT_1_POS (0)
#define SDIO_SD_SLAVE_RDAT_1_MASK (0xFFFFFFFF)

	/* REG_0x15 */
#define SDIO_REG0X15_ADDR  (SOC_SDIO_REG_BASE + 0x15*4) //REG ADDR :0x458d0054
#define SDIO_SD_SLAVE_WDAT_0_POS (0)
#define SDIO_SD_SLAVE_WDAT_0_MASK (0xFFFFFFFF)

	/* REG_0x16 */
#define SDIO_REG0X16_ADDR  (SOC_SDIO_REG_BASE + 0x16*4) //REG ADDR :0x458d0058
#define SDIO_SD_SLAVE_WDAT_1_POS (0)
#define SDIO_SD_SLAVE_WDAT_1_MASK (0xFFFFFFFF)

	/* REG_0x17 */
#define SDIO_REG0X17_ADDR  (SOC_SDIO_REG_BASE + 0x17*4) //REG ADDR :0x458d005c
#define SDIO_SD_SLAVE_STATUS_ADDR  (SOC_SDIO_REG_BASE + 0x17*4) //REG ADDR :0x458d005c
#define SDIO_SD_SLAVE_STATUS_CMD_S_RES_DAT_RD_POS (0)
#define SDIO_SD_SLAVE_STATUS_CMD_S_RES_DAT_RD_MASK (0x1)

#define SDIO_SD_SLAVE_STATUS_CMD_S_RES_DAT_WR_POS (1)
#define SDIO_SD_SLAVE_STATUS_CMD_S_RES_DAT_WR_MASK (0x1)

#define SDIO_SD_SLAVE_STATUS_CMD_S_REC_BB_CNT_POS (2)
#define SDIO_SD_SLAVE_STATUS_CMD_S_REC_BB_CNT_MASK (0x1FF)

#define SDIO_SD_SLAVE_STATUS_CMD_S_REC_OP_CODE_POS (11)
#define SDIO_SD_SLAVE_STATUS_CMD_S_REC_OP_CODE_MASK (0x1)

#define SDIO_SD_SLAVE_STATUS_CMD_S_REC_BLK_MOD_POS (12)
#define SDIO_SD_SLAVE_STATUS_CMD_S_REC_BLK_MOD_MASK (0x1)

#define SDIO_SD_SLAVE_STATUS_SD_START_WR_EN_R3_POS (13)
#define SDIO_SD_SLAVE_STATUS_SD_START_WR_EN_R3_MASK (0x1)

#define SDIO_SD_SLAVE_STATUS_DAT_S_RD_BUS_4RD_POS (14)
#define SDIO_SD_SLAVE_STATUS_DAT_S_RD_BUS_4RD_MASK (0x1)

#define SDIO_SD_SLAVE_STATUS_CMD_S_RES_END_4RD_POS (15)
#define SDIO_SD_SLAVE_STATUS_CMD_S_RES_END_4RD_MASK (0x1)

#define SDIO_SD_SLAVE_STATUS_DAT_S_WR_WAI_4RD_POS (16)
#define SDIO_SD_SLAVE_STATUS_DAT_S_WR_WAI_4RD_MASK (0x1)

#define SDIO_SD_SLAVE_STATUS_RESERVED0_POS (17)
#define SDIO_SD_SLAVE_STATUS_RESERVED0_MASK (0x7FFF)

		/* REG_0x1a */
#define SDIO_REG0X1A_ADDR  (SOC_SDIO_REG_BASE + 0x1a*4) //REG ADDR :0x458d0068
#define SDIO_SD_CMD_IRQ_EX_OP_ADDR  (SOC_SDIO_REG_BASE + 0x1a*4) //REG ADDR :0x458d0068
#define SDIO_SD_CMD_IRQ_EX_OP_CMD_SST_SEL_POS (19)
#define SDIO_SD_CMD_IRQ_EX_OP_CMD_SST_SEL_MASK (0x1)

#define SDIO_SD_CMD_IRQ_EX_OP_DAT_S_DAT1_INT_EN_POS (20)
#define SDIO_SD_CMD_IRQ_EX_OP_DAT_S_DAT1_INT_EN_MASK (0x1)
		/* REG_0x1e */
#define SDIO_REG0X1E_ADDR  (SOC_SDIO_REG_BASE + 0x1e*4) //REG ADDR :0x458d0078
#define SDIO_SD_CCCR_2_ADDR  (SOC_SDIO_REG_BASE + 0x1e*4) //REG ADDR :0x458d0078
#define SDIO_SD_CCCR_2_INTX_POS (9)
#define SDIO_SD_CCCR_2_INTX_MASK (0x7f)
		/* REG_0x1f */
#define SDIO_REG0X1F_ADDR  (SOC_SDIO_REG_BASE + 0x1f*4) //REG ADDR :0x458d007c
#define SDIO_SD_CCCR_3_ADDR  (SOC_SDIO_REG_BASE + 0x1f*4) //REG ADDR :0x458d007c
#define SDIO_SD_CCCR_3_S4MI_POS (4)
#define SDIO_SD_CCCR_3_S4MI_MASK (0x1)

#define SDIO_LL_REG_END      (SDIO_SD_CCCR_3_ADDR) //REG_BASE:0x458d007c

#ifdef __cplusplus
}
#endif

