// Copyright 2022-2025 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This is a generated file, if you need to modify it, use the script to
// generate and modify all the struct.h, ll.h, reg.h, debug_dump.c files!

#pragma once

#include "sdkconfig.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SYS_DEVICE_ID_ADDR (SOC_SYSTEM_REG_BASE + (0x0 << 2))

#define SYS_DEVICE_ID_DEVICEID_POS (0)
#define SYS_DEVICE_ID_DEVICEID_MASK (0xffffffff)

#define SYS_VERSION_ID_ADDR (SOC_SYSTEM_REG_BASE + (0x1 << 2))

#define SYS_VERSION_ID_VERSIONID_POS (0)
#define SYS_VERSION_ID_VERSIONID_MASK (0xffffffff)

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_ADDR (SOC_SYSTEM_REG_BASE + (0x2 << 2))

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_BOOT_MODE_POS (0)
#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_BOOT_MODE_MASK (0x1)

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RESERVED_BIT_1_1_POS (1)
#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RESERVED_BIT_1_1_MASK (0x1)

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RESERVED0_POS (2)
#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RESERVED0_MASK (0x3)

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RF_SWITCH_MANUAL_EN_POS (4)
#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RF_SWITCH_MANUAL_EN_MASK (0x1)

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RF_SOURCE_POS (5)
#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RF_SOURCE_MASK (0x3)

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RESERVED1_POS (7)
#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RESERVED1_MASK (0x1)

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RESERVED_BIT_8_8_POS (8)
#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RESERVED_BIT_8_8_MASK (0x1)

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_FLASH_SEL_POS (9)
#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_FLASH_SEL_MASK (0x1)

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_FEM_BPS_TXEN_POS (10)
#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_FEM_BPS_TXEN_MASK (0x1)

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RESERVED2_POS (11)
#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RESERVED2_MASK (0x1fffff)

#define SYS_CPU_CURRENT_RUN_STATUS_ADDR (SOC_SYSTEM_REG_BASE + (0x3 << 2))

#define SYS_CPU_CURRENT_RUN_STATUS_CORE0_HALTED_POS (0)
#define SYS_CPU_CURRENT_RUN_STATUS_CORE0_HALTED_MASK (0x1)

#define SYS_CPU_CURRENT_RUN_STATUS_RESERVED_BIT_1_1_POS (1)
#define SYS_CPU_CURRENT_RUN_STATUS_RESERVED_BIT_1_1_MASK (0x1)

#define SYS_CPU_CURRENT_RUN_STATUS_RESERVED0_POS (2)
#define SYS_CPU_CURRENT_RUN_STATUS_RESERVED0_MASK (0x3)

#define SYS_CPU_CURRENT_RUN_STATUS_CPU0_SW_RESET_POS (4)
#define SYS_CPU_CURRENT_RUN_STATUS_CPU0_SW_RESET_MASK (0x1)

#define SYS_CPU_CURRENT_RUN_STATUS_RESERVED1_POS (5)
#define SYS_CPU_CURRENT_RUN_STATUS_RESERVED1_MASK (0x7)

#define SYS_CPU_CURRENT_RUN_STATUS_CPU0_PWR_DW_STATE_POS (8)
#define SYS_CPU_CURRENT_RUN_STATUS_CPU0_PWR_DW_STATE_MASK (0x1)

#define SYS_CPU_CURRENT_RUN_STATUS_RESERVED2_POS (9)
#define SYS_CPU_CURRENT_RUN_STATUS_RESERVED2_MASK (0x7fffff)

#define SYS_CPU0_INT_HALT_CLK_OP_ADDR (SOC_SYSTEM_REG_BASE + (0x4 << 2))

#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_SW_RST_POS (0)
#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_SW_RST_MASK (0x1)

#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_PWR_DW_POS (1)
#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_PWR_DW_MASK (0x1)

#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_INT_MASK_POS (2)
#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_INT_MASK_MASK (0x1)

#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_HALT_POS (3)
#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_HALT_MASK (0x1)

#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_SPEED_POS (4)
#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_SPEED_MASK (0x1)

#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_RXEVT_SEL_POS (5)
#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_RXEVT_SEL_MASK (0x1)

#define SYS_CPU0_INT_HALT_CLK_OP_RESERVED_6_7_POS (6)
#define SYS_CPU0_INT_HALT_CLK_OP_RESERVED_6_7_MASK (0x3)

#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_OFFSET_POS (8)
#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_OFFSET_MASK (0xffffff)

#define SYS_CPU_CLK_DIV_MODE1_ADDR (SOC_SYSTEM_REG_BASE + (0x8 << 2))

#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_CORE_POS (0)
#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_CORE_MASK (0xf)

#define SYS_CPU_CLK_DIV_MODE1_CKSEL_CORE_POS (4)
#define SYS_CPU_CLK_DIV_MODE1_CKSEL_CORE_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_RSV_POS (5)
#define SYS_CPU_CLK_DIV_MODE1_RSV_MASK (0x7ffffff)

#define SYS_CPU_CLK_DIV_MODE2_ADDR (SOC_SYSTEM_REG_BASE + (0x9 << 2))

#define SYS_CPU_CLK_DIV_MODE2_RESERVED_0_3_POS (0)
#define SYS_CPU_CLK_DIV_MODE2_RESERVED_0_3_MASK (0xf)

#define SYS_CPU_CLK_DIV_MODE2_CKDIV_PSRAM_POS (4)
#define SYS_CPU_CLK_DIV_MODE2_CKDIV_PSRAM_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE2_CKSEL_PSRAM_POS (5)
#define SYS_CPU_CLK_DIV_MODE2_CKSEL_PSRAM_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE2_RESERVED_BIT_6_13_POS (6)
#define SYS_CPU_CLK_DIV_MODE2_RESERVED_BIT_6_13_MASK (0xff)

#define SYS_CPU_CLK_DIV_MODE2_CKDIV_SDIO_POS (14)
#define SYS_CPU_CLK_DIV_MODE2_CKDIV_SDIO_MASK (0x3)

#define SYS_CPU_CLK_DIV_MODE2_CKSEL_SDIO_POS (16)
#define SYS_CPU_CLK_DIV_MODE2_CKSEL_SDIO_MASK (0x3)

#define SYS_CPU_CLK_DIV_MODE2_CKDIV_AUXS_POS (18)
#define SYS_CPU_CLK_DIV_MODE2_CKDIV_AUXS_MASK (0xf)

#define SYS_CPU_CLK_DIV_MODE2_CKSEL_AUXS_POS (22)
#define SYS_CPU_CLK_DIV_MODE2_CKSEL_AUXS_MASK (0x3)

#define SYS_CPU_CLK_DIV_MODE2_CKSEL_FLASH_POS (24)
#define SYS_CPU_CLK_DIV_MODE2_CKSEL_FLASH_MASK (0x3)

#define SYS_CPU_CLK_DIV_MODE2_CKDIV_FLASH_POS (26)
#define SYS_CPU_CLK_DIV_MODE2_CKDIV_FLASH_MASK (0x3)

#define SYS_CPU_CLK_DIV_MODE2_CKDIV_I2S0_POS (28)
#define SYS_CPU_CLK_DIV_MODE2_CKDIV_I2S0_MASK (0x7)

#define SYS_CPU_CLK_DIV_MODE2_CLKDIV_AUXS_POS (31)
#define SYS_CPU_CLK_DIV_MODE2_CLKDIV_AUXS_MASK (0x1)

#define SYS_CPU_26M_WDT_CLK_DIV_ADDR (SOC_SYSTEM_REG_BASE + (0xa << 2))

#define SYS_CPU_26M_WDT_CLK_DIV_CKDIV_26M_POS (0)
#define SYS_CPU_26M_WDT_CLK_DIV_CKDIV_26M_MASK (0x3)

#define SYS_CPU_26M_WDT_CLK_DIV_CKDIV_WDT_POS (2)
#define SYS_CPU_26M_WDT_CLK_DIV_CKDIV_WDT_MASK (0x3)

#define SYS_CPU_26M_WDT_CLK_DIV_CLKSEL_SPI0_POS (4)
#define SYS_CPU_26M_WDT_CLK_DIV_CLKSEL_SPI0_MASK (0x3)

#define SYS_CPU_26M_WDT_CLK_DIV_CLKSEL_SPI1_POS (6)
#define SYS_CPU_26M_WDT_CLK_DIV_CLKSEL_SPI1_MASK (0x3)

#define SYS_CPU_26M_WDT_CLK_DIV_CKSEL_QSPI1_POS (8)
#define SYS_CPU_26M_WDT_CLK_DIV_CKSEL_QSPI1_MASK (0x3)

#define SYS_CPU_26M_WDT_CLK_DIV_RESERVED_10_31_POS (10)
#define SYS_CPU_26M_WDT_CLK_DIV_RESERVED_10_31_MASK (0x3fffff)

#define SYS_CPU_ANASPI_FREQ_ADDR (SOC_SYSTEM_REG_BASE + (0xb << 2))

#define SYS_CPU_ANASPI_FREQ_ANASPI_FREQ_POS (0)
#define SYS_CPU_ANASPI_FREQ_ANASPI_FREQ_MASK (0x3f)

#define SYS_CPU_ANASPI_FREQ_RESERVED_6_31_POS (6)
#define SYS_CPU_ANASPI_FREQ_RESERVED_6_31_MASK (0x3ffffff)

#define SYS_CPU_DEVICE_CLK_ENABLE_ADDR (SOC_SYSTEM_REG_BASE + (0xc << 2))

#define SYS_CPU_DEVICE_CLK_ENABLE_I2C0_CKEN_POS (0)
#define SYS_CPU_DEVICE_CLK_ENABLE_I2C0_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_SPI0_CKEN_POS (1)
#define SYS_CPU_DEVICE_CLK_ENABLE_SPI0_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_UART0_CKEN_POS (2)
#define SYS_CPU_DEVICE_CLK_ENABLE_UART0_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_PWM0_CKEN_POS (3)
#define SYS_CPU_DEVICE_CLK_ENABLE_PWM0_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_TIM0_CKEN_POS (4)
#define SYS_CPU_DEVICE_CLK_ENABLE_TIM0_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_SADC_CKEN_POS (5)
#define SYS_CPU_DEVICE_CLK_ENABLE_SADC_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_UART3_CKEN_POS (6)
#define SYS_CPU_DEVICE_CLK_ENABLE_UART3_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_GPIO_CKEN_POS (7)
#define SYS_CPU_DEVICE_CLK_ENABLE_GPIO_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_I2C1_CKEN_POS (8)
#define SYS_CPU_DEVICE_CLK_ENABLE_I2C1_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_SPI1_CKEN_POS (9)
#define SYS_CPU_DEVICE_CLK_ENABLE_SPI1_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_UART1_CKEN_POS (10)
#define SYS_CPU_DEVICE_CLK_ENABLE_UART1_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_UART2_CKEN_POS (11)
#define SYS_CPU_DEVICE_CLK_ENABLE_UART2_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_RESERVED_BIT_12_12_POS (12)
#define SYS_CPU_DEVICE_CLK_ENABLE_RESERVED_BIT_12_12_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_TIM1_CKEN_POS (13)
#define SYS_CPU_DEVICE_CLK_ENABLE_TIM1_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_RESERVED_BIT_14_14_POS (14)
#define SYS_CPU_DEVICE_CLK_ENABLE_RESERVED_BIT_14_14_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_OTP_CKEN_POS (15)
#define SYS_CPU_DEVICE_CLK_ENABLE_OTP_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_I2S_CKEN_POS (16)
#define SYS_CPU_DEVICE_CLK_ENABLE_I2S_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_LED_CKEN_POS (17)
#define SYS_CPU_DEVICE_CLK_ENABLE_LED_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_RESERVED_BIT_18_19_POS (18)
#define SYS_CPU_DEVICE_CLK_ENABLE_RESERVED_BIT_18_19_MASK (0x3)

#define SYS_CPU_DEVICE_CLK_ENABLE_DPLLDIV_CKEN_POS (20)
#define SYS_CPU_DEVICE_CLK_ENABLE_DPLLDIV_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_QSPI1_CKEN_POS (21)
#define SYS_CPU_DEVICE_CLK_ENABLE_QSPI1_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_SDIO_CKEN_POS (22)
#define SYS_CPU_DEVICE_CLK_ENABLE_SDIO_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_AUXS_CKEN_POS (23)
#define SYS_CPU_DEVICE_CLK_ENABLE_AUXS_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_BTDM_CKEN_POS (24)
#define SYS_CPU_DEVICE_CLK_ENABLE_BTDM_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_XVR_CKEN_POS (25)
#define SYS_CPU_DEVICE_CLK_ENABLE_XVR_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_MAC_CKEN_POS (26)
#define SYS_CPU_DEVICE_CLK_ENABLE_MAC_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_PHY_CKEN_POS (27)
#define SYS_CPU_DEVICE_CLK_ENABLE_PHY_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_THREAD_CKEN_POS (28)
#define SYS_CPU_DEVICE_CLK_ENABLE_THREAD_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_RF_CKEN_POS (29)
#define SYS_CPU_DEVICE_CLK_ENABLE_RF_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_RESERVED_BIT_30_30_POS (30)
#define SYS_CPU_DEVICE_CLK_ENABLE_RESERVED_BIT_30_30_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_WDT_CKEN_POS (31)
#define SYS_CPU_DEVICE_CLK_ENABLE_WDT_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_ADDR (SOC_SYSTEM_REG_BASE + (0xf << 2))

#define SYS_CPU_DEVICE_MEM_CTRL2_UART1_DS_POS (0)
#define SYS_CPU_DEVICE_MEM_CTRL2_UART1_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_UART2_DS_POS (1)
#define SYS_CPU_DEVICE_MEM_CTRL2_UART2_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_SPI1_DS_POS (2)
#define SYS_CPU_DEVICE_MEM_CTRL2_SPI1_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_SDIO_DS_POS (3)
#define SYS_CPU_DEVICE_MEM_CTRL2_SDIO_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_UART3_DS_POS (4)
#define SYS_CPU_DEVICE_MEM_CTRL2_UART3_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_LED_DS_POS (5)
#define SYS_CPU_DEVICE_MEM_CTRL2_LED_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_RESERVED_6_6_POS (6)
#define SYS_CPU_DEVICE_MEM_CTRL2_RESERVED_6_6_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_QSPI1_DS_POS (7)
#define SYS_CPU_DEVICE_MEM_CTRL2_QSPI1_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_PRAM_DS_POS (8)
#define SYS_CPU_DEVICE_MEM_CTRL2_PRAM_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_RESERVED0_POS (9)
#define SYS_CPU_DEVICE_MEM_CTRL2_RESERVED0_MASK (0x7)

#define SYS_CPU_DEVICE_MEM_CTRL2_I2S0_DS_POS (12)
#define SYS_CPU_DEVICE_MEM_CTRL2_I2S0_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_RESERVED_13_20_POS (13)
#define SYS_CPU_DEVICE_MEM_CTRL2_RESERVED_13_20_MASK (0xff)

#define SYS_CPU_DEVICE_MEM_CTRL2_MAC_DS_POS (21)
#define SYS_CPU_DEVICE_MEM_CTRL2_MAC_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_PHY_DS_POS (22)
#define SYS_CPU_DEVICE_MEM_CTRL2_PHY_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_XVR_DS_POS (23)
#define SYS_CPU_DEVICE_MEM_CTRL2_XVR_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_RESERVED_BIT_24_24_POS (24)
#define SYS_CPU_DEVICE_MEM_CTRL2_RESERVED_BIT_24_24_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_LA_DS_POS (25)
#define SYS_CPU_DEVICE_MEM_CTRL2_LA_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_FLSH_DS_POS (26)
#define SYS_CPU_DEVICE_MEM_CTRL2_FLSH_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_UART_DS_POS (27)
#define SYS_CPU_DEVICE_MEM_CTRL2_UART_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_SPI0_DS_POS (28)
#define SYS_CPU_DEVICE_MEM_CTRL2_SPI0_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_ENC_DS_POS (29)
#define SYS_CPU_DEVICE_MEM_CTRL2_ENC_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_DMA0_DS_POS (30)
#define SYS_CPU_DEVICE_MEM_CTRL2_DMA0_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_RESERVED1_POS (31)
#define SYS_CPU_DEVICE_MEM_CTRL2_RESERVED1_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_ADDR (SOC_SYSTEM_REG_BASE + (0x10 << 2))

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM1_POS (0)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM1_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM2_POS (1)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM2_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM3_POS (2)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM3_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_ENCP_POS (3)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_ENCP_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_BAKP_POS (4)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_BAKP_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_RESERVED_BIT_5_7_POS (5)
#define SYS_CPU_POWER_SLEEP_WAKEUP_RESERVED_BIT_5_7_MASK (0x7)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_BTSP_POS (8)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_BTSP_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_WIFP_MAC_POS (9)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_WIFP_MAC_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_WIFP_PHY_POS (10)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_WIFP_PHY_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM0_POS (11)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM0_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM4_POS (12)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM4_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_OFDM_POS (13)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_OFDM_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_THREAD_POS (14)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_THREAD_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_ROM_PGEN_POS (15)
#define SYS_CPU_POWER_SLEEP_WAKEUP_ROM_PGEN_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_EN_NEED_FLASH_IDLE_POS (16)
#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_EN_NEED_FLASH_IDLE_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_RESERVED_BIT_17_17_POS (17)
#define SYS_CPU_POWER_SLEEP_WAKEUP_RESERVED_BIT_17_17_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_EN_NEED_CPU0_WFI_POS (18)
#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_EN_NEED_CPU0_WFI_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_EN_GLOBAL_POS (19)
#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_EN_GLOBAL_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_BUS_IDLE_BYPASS_POS (20)
#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_BUS_IDLE_BYPASS_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_RESERVED_BIT_21_21_POS (21)
#define SYS_CPU_POWER_SLEEP_WAKEUP_RESERVED_BIT_21_21_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_BTS_SOFT_WAKEUP_REQ_POS (22)
#define SYS_CPU_POWER_SLEEP_WAKEUP_BTS_SOFT_WAKEUP_REQ_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_ROM_RD_DISABLE_POS (23)
#define SYS_CPU_POWER_SLEEP_WAKEUP_ROM_RD_DISABLE_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_OTP_RD_DISABLE_POS (24)
#define SYS_CPU_POWER_SLEEP_WAKEUP_OTP_RD_DISABLE_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_TCM0_PGEN_POS (25)
#define SYS_CPU_POWER_SLEEP_WAKEUP_TCM0_PGEN_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_CPU0_SUBPWDM_EN_POS (26)
#define SYS_CPU_POWER_SLEEP_WAKEUP_CPU0_SUBPWDM_EN_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_TE200_CLKGAT_BPS_POS (27)
#define SYS_CPU_POWER_SLEEP_WAKEUP_TE200_CLKGAT_BPS_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_SHARE_MEM_CLKGATING_DISABLE_POS (28)
#define SYS_CPU_POWER_SLEEP_WAKEUP_SHARE_MEM_CLKGATING_DISABLE_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_CPU0_TICKTIMER_32K_ENABLE_POS (29)
#define SYS_CPU_POWER_SLEEP_WAKEUP_CPU0_TICKTIMER_32K_ENABLE_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_RESERVED_30_30_POS (30)
#define SYS_CPU_POWER_SLEEP_WAKEUP_RESERVED_30_30_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_BUSMATRIX_BUSY_POS (31)
#define SYS_CPU_POWER_SLEEP_WAKEUP_BUSMATRIX_BUSY_MASK (0x1)

#define SYS_CPU0_LV_SLEEP_CFG_ADDR (SOC_SYSTEM_REG_BASE + (0x11 << 2))

#define SYS_CPU0_LV_SLEEP_CFG_CPU0_CACHE_RET_EN_POS (0)
#define SYS_CPU0_LV_SLEEP_CFG_CPU0_CACHE_RET_EN_MASK (0x1)

#define SYS_CPU0_LV_SLEEP_CFG_CPU0_CACHE_SLEEPPWD_EN_POS (1)
#define SYS_CPU0_LV_SLEEP_CFG_CPU0_CACHE_SLEEPPWD_EN_MASK (0x1)

#define SYS_CPU0_LV_SLEEP_CFG_RESERVED_2_31_POS (2)
#define SYS_CPU0_LV_SLEEP_CFG_RESERVED_2_31_MASK (0x3fffffff)

#define SYS_CPU_DEVICE_MEM_CTRL3_ADDR (SOC_SYSTEM_REG_BASE + (0x12 << 2))

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM0_DS_POS (0)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM0_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM1_DS_POS (1)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM1_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM2_DS_POS (2)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM2_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM3_DS_POS (3)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM3_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM4_DS_POS (4)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM4_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RESERVED0_POS (5)
#define SYS_CPU_DEVICE_MEM_CTRL3_RESERVED0_MASK (0x7ff)

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM_CONFIG_POS (16)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM_CONFIG_MASK (0x3ff)

#define SYS_CPU_DEVICE_MEM_CTRL3_RESERVED1_POS (26)
#define SYS_CPU_DEVICE_MEM_CTRL3_RESERVED1_MASK (0x3f)

#define SYS_CPU0_INT_0_31_EN_ADDR (SOC_SYSTEM_REG_BASE + (0x20 << 2))

#define SYS_CPU0_INT_0_31_EN_CPU0_DMA_NSEC_INTR_EN_POS (0)
#define SYS_CPU0_INT_0_31_EN_CPU0_DMA_NSEC_INTR_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_ENCP_SEC_INTR_EN_POS (1)
#define SYS_CPU0_INT_0_31_EN_CPU0_ENCP_SEC_INTR_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_ENCP_NSEC_INTR_EN_POS (2)
#define SYS_CPU0_INT_0_31_EN_CPU0_ENCP_NSEC_INTR_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_TIMER_INT_EN_POS (3)
#define SYS_CPU0_INT_0_31_EN_CPU0_TIMER_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_RESERVED_BIT_4_4_POS (4)
#define SYS_CPU0_INT_0_31_EN_RESERVED_BIT_4_4_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_PWM0_INT_EN_POS (5)
#define SYS_CPU0_INT_0_31_EN_CPU0_PWM0_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_I2C0_INT_EN_POS (6)
#define SYS_CPU0_INT_0_31_EN_CPU0_I2C0_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_SPI0_INT_EN_POS (7)
#define SYS_CPU0_INT_0_31_EN_CPU0_SPI0_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_RESERVED_BIT_8_8_POS (8)
#define SYS_CPU0_INT_0_31_EN_RESERVED_BIT_8_8_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_UART3_INT_EN_POS (9)
#define SYS_CPU0_INT_0_31_EN_CPU0_UART3_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_SDIO_INT_EN_POS (10)
#define SYS_CPU0_INT_0_31_EN_CPU0_SDIO_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_GDMA_INT_EN_POS (11)
#define SYS_CPU0_INT_0_31_EN_CPU0_GDMA_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_LA_INT_EN_POS (12)
#define SYS_CPU0_INT_0_31_EN_CPU0_LA_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_TIMER1_INT_EN_POS (13)
#define SYS_CPU0_INT_0_31_EN_CPU0_TIMER1_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_I2C1_INT_EN_POS (14)
#define SYS_CPU0_INT_0_31_EN_CPU0_I2C1_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_UART1_INT_EN_POS (15)
#define SYS_CPU0_INT_0_31_EN_CPU0_UART1_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_UART2_INT_EN_POS (16)
#define SYS_CPU0_INT_0_31_EN_CPU0_UART2_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_SPI1_INT_EN_POS (17)
#define SYS_CPU0_INT_0_31_EN_CPU0_SPI1_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_LED_INT_EN_POS (18)
#define SYS_CPU0_INT_0_31_EN_CPU0_LED_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_TAMPER_INT_EN_POS (19)
#define SYS_CPU0_INT_0_31_EN_CPU0_TAMPER_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_RESV1_INT_EN_POS (20)
#define SYS_CPU0_INT_0_31_EN_CPU0_RESV1_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_CKMN_INT_EN_POS (21)
#define SYS_CPU0_INT_0_31_EN_CPU0_CKMN_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_RESV2_INT_EN_POS (22)
#define SYS_CPU0_INT_0_31_EN_CPU0_RESV2_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_RESV3_INT_EN_POS (23)
#define SYS_CPU0_INT_0_31_EN_CPU0_RESV3_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_I2S0_INT_EN_POS (24)
#define SYS_CPU0_INT_0_31_EN_CPU0_I2S0_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_RESV4_INT_EN_POS (25)
#define SYS_CPU0_INT_0_31_EN_CPU0_RESV4_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_RESV5_INT_EN_POS (26)
#define SYS_CPU0_INT_0_31_EN_CPU0_RESV5_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_RESV6_INT_EN_POS (27)
#define SYS_CPU0_INT_0_31_EN_CPU0_RESV6_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_RESV7_INT_EN_POS (28)
#define SYS_CPU0_INT_0_31_EN_CPU0_RESV7_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_INT_MAC_WAKEUP_INT_EN_POS (29)
#define SYS_CPU0_INT_0_31_EN_CPU0_INT_MAC_WAKEUP_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_HSU_IRQ_INT_EN_POS (30)
#define SYS_CPU0_INT_0_31_EN_CPU0_HSU_IRQ_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_MAC_INT_GEN_INT_EN_POS (31)
#define SYS_CPU0_INT_0_31_EN_CPU0_MAC_INT_GEN_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_ADDR (SOC_SYSTEM_REG_BASE + (0x21 << 2))

#define SYS_CPU0_INT_32_63_EN_CPU0_MAC_INT_PORT_TRIGGER_INT_EN_POS (0)
#define SYS_CPU0_INT_32_63_EN_CPU0_MAC_INT_PORT_TRIGGER_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_MAC_INT_TX_TRIGGER_INT_EN_POS (1)
#define SYS_CPU0_INT_32_63_EN_CPU0_MAC_INT_TX_TRIGGER_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_MAC_INT_RX_TRIGGER_INT_EN_POS (2)
#define SYS_CPU0_INT_32_63_EN_CPU0_MAC_INT_RX_TRIGGER_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_MAC_INT_TX_RX_MISC_INT_EN_POS (3)
#define SYS_CPU0_INT_32_63_EN_CPU0_MAC_INT_TX_RX_MISC_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_MAC_INT_TX_RX_TIMER_INT_EN_POS (4)
#define SYS_CPU0_INT_32_63_EN_CPU0_MAC_INT_TX_RX_TIMER_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_PHY_RIU_INT_INT_EN_POS (5)
#define SYS_CPU0_INT_32_63_EN_CPU0_PHY_RIU_INT_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_PHY_MBP_INT_INT_EN_POS (6)
#define SYS_CPU0_INT_32_63_EN_CPU0_PHY_MBP_INT_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_BT_IRQ_INT_EN_POS (7)
#define SYS_CPU0_INT_32_63_EN_CPU0_BT_IRQ_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_BLE_IRQ_INT_EN_POS (8)
#define SYS_CPU0_INT_32_63_EN_CPU0_BLE_IRQ_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_DM_IRQ_INT_EN_POS (9)
#define SYS_CPU0_INT_32_63_EN_CPU0_DM_IRQ_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_QSPI1_INT_EN_POS (10)
#define SYS_CPU0_INT_32_63_EN_CPU0_QSPI1_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_RESV8_INT_EN_POS (11)
#define SYS_CPU0_INT_32_63_EN_CPU0_RESV8_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_RESV9_INT_EN_POS (12)
#define SYS_CPU0_INT_32_63_EN_CPU0_RESV9_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_RESV10_INT_EN_POS (13)
#define SYS_CPU0_INT_32_63_EN_CPU0_RESV10_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_RESV11_INT_EN_POS (14)
#define SYS_CPU0_INT_32_63_EN_CPU0_RESV11_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_RESV12_INT_EN_POS (15)
#define SYS_CPU0_INT_32_63_EN_CPU0_RESV12_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_THREAD_INT_EN_POS (16)
#define SYS_CPU0_INT_32_63_EN_CPU0_THREAD_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_RESV13_INT_EN_POS (17)
#define SYS_CPU0_INT_32_63_EN_CPU0_RESV13_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_OTP_INT_EN_POS (18)
#define SYS_CPU0_INT_32_63_EN_CPU0_OTP_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_DPLLUNLOCK_INT_EN_POS (19)
#define SYS_CPU0_INT_32_63_EN_CPU0_DPLLUNLOCK_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_RESV14_INT_EN_POS (20)
#define SYS_CPU0_INT_32_63_EN_CPU0_RESV14_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_RESV15_INT_EN_POS (21)
#define SYS_CPU0_INT_32_63_EN_CPU0_RESV15_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_RESV16_INT_EN_POS (22)
#define SYS_CPU0_INT_32_63_EN_CPU0_RESV16_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_GPIO_S_INT_EN_POS (23)
#define SYS_CPU0_INT_32_63_EN_CPU0_GPIO_S_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_GPIO_NS_INT_EN_POS (24)
#define SYS_CPU0_INT_32_63_EN_CPU0_GPIO_NS_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_RESV25_POS (25)
#define SYS_CPU0_INT_32_63_EN_RESV25_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_ANA_GPIO_POS (26)
#define SYS_CPU0_INT_32_63_EN_ANA_GPIO_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_ANA_RTC_POS (27)
#define SYS_CPU0_INT_32_63_EN_ANA_RTC_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_ABNORMAL_GPIO_POS (28)
#define SYS_CPU0_INT_32_63_EN_ABNORMAL_GPIO_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_ABNORMAL_RTC_POS (29)
#define SYS_CPU0_INT_32_63_EN_ABNORMAL_RTC_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_RESV30_POS (30)
#define SYS_CPU0_INT_32_63_EN_RESV30_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_RESV31_POS (31)
#define SYS_CPU0_INT_32_63_EN_RESV31_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_ADDR (SOC_SYSTEM_REG_BASE + (0x28 << 2))

#define SYS_CPU0_INT_0_31_STATUS_CPU0_DMA_NSEC_INTR_ST_POS (0)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_DMA_NSEC_INTR_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_ENCP_SEC_INTR_ST_POS (1)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_ENCP_SEC_INTR_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_ENCP_NSEC_INTR_ST_POS (2)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_ENCP_NSEC_INTR_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_TIMER_INT_ST_POS (3)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_TIMER_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_RESERVED_BIT_4_4_POS (4)
#define SYS_CPU0_INT_0_31_STATUS_RESERVED_BIT_4_4_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_PWM0_INT_ST_POS (5)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_PWM0_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_I2C0_INT_ST_POS (6)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_I2C0_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_SPI0_INT_ST_POS (7)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_SPI0_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_RESERVED_BIT_8_8_POS (8)
#define SYS_CPU0_INT_0_31_STATUS_RESERVED_BIT_8_8_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_UART3_INT_ST_POS (9)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_UART3_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_SDIO_INT_ST_POS (10)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_SDIO_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_GDMA_INT_ST_POS (11)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_GDMA_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_LA_INT_ST_POS (12)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_LA_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_TIMER1_INT_ST_POS (13)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_TIMER1_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_I2C1_INT_ST_POS (14)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_I2C1_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_UART1_INT_ST_POS (15)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_UART1_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_UART2_INT_ST_POS (16)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_UART2_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_SPI1_INT_ST_POS (17)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_SPI1_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_LED_INT_ST_POS (18)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_LED_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV0_INT_ST_POS (19)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV0_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV1_INT_ST_POS (20)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV1_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_CKMN_INT_ST_POS (21)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_CKMN_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV2_INT_ST_POS (22)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV2_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV3_INT_ST_POS (23)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV3_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_I2S0_INT_ST_POS (24)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_I2S0_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV4_INT_ST_POS (25)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV4_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV5_INT_ST_POS (26)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV5_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV6_INT_ST_POS (27)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV6_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV7_INT_ST_POS (28)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_RESV7_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_INT_MAC_WAKEUP_INT_ST_POS (29)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_INT_MAC_WAKEUP_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_HSU_IRQ_INT_ST_POS (30)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_HSU_IRQ_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_MAC_INT_GEN_INT_ST_POS (31)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_MAC_INT_GEN_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_ADDR (SOC_SYSTEM_REG_BASE + (0x29 << 2))

#define SYS_CPU0_INT_32_63_STATUS_CPU0_MAC_INT_PORT_TRIGGER_INT_ST_POS (0)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_MAC_INT_PORT_TRIGGER_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_MAC_INT_TX_TRIGGER_INT_ST_POS (1)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_MAC_INT_TX_TRIGGER_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_MAC_INT_RX_TRIGGER_INT_ST_POS (2)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_MAC_INT_RX_TRIGGER_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_MAC_INT_TX_RX_MISC_INT_ST_POS (3)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_MAC_INT_TX_RX_MISC_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_MAC_INT_TX_RX_TIMER_INT_ST_POS (4)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_MAC_INT_TX_RX_TIMER_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_PHY_RIU_INT_INT_ST_POS (5)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_PHY_RIU_INT_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_PHY_MBP_INT_INT_ST_POS (6)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_PHY_MBP_INT_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_BT_IRQ_INT_ST_POS (7)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_BT_IRQ_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_BLE_IRQ_INT_ST_POS (8)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_BLE_IRQ_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_DM_IRQ_INT_ST_POS (9)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_DM_IRQ_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_QSPI1_INT_ST_POS (10)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_QSPI1_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV8_INT_ST_POS (11)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV8_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV9_INT_ST_POS (12)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV9_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV10_INT_ST_POS (13)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV10_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV11_INT_ST_POS (14)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV11_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV12_INT_ST_POS (15)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV12_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_THREAD_INT_ST_POS (16)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_THREAD_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV13_INT_ST_POS (17)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV13_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_OTP_INT_ST_POS (18)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_OTP_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_DPLLUNLOCK_INT_ST_POS (19)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_DPLLUNLOCK_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV14_INT_ST_POS (20)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV14_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV15_INT_ST_POS (21)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV15_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV16_INT_ST_POS (22)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_RESV16_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_GPIO_S_INT_ST_POS (23)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_GPIO_S_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_GPIO_NS_INT_ST_POS (24)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_GPIO_NS_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_ANA3V_WAKEUP_INT_ST_POS (25)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_ANA3V_WAKEUP_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_RESV26_POS (26)
#define SYS_CPU0_INT_32_63_STATUS_RESV26_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_RESV27_POS (27)
#define SYS_CPU0_INT_32_63_STATUS_RESV27_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_RESV28_POS (28)
#define SYS_CPU0_INT_32_63_STATUS_RESV28_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_RESV29_POS (29)
#define SYS_CPU0_INT_32_63_STATUS_RESV29_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_RESV30_POS (30)
#define SYS_CPU0_INT_32_63_STATUS_RESV30_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_RESV31_POS (31)
#define SYS_CPU0_INT_32_63_STATUS_RESV31_MASK (0x1)

#define SYS_GPIO_CONFIG0_ADDR (SOC_SYSTEM_REG_BASE + (0x30 << 2))

#define SYS_GPIO_CONFIG0_GPIO_CONFIG0_POS (0)
#define SYS_GPIO_CONFIG0_GPIO_CONFIG0_MASK (0xffffffff)

#define SYS_GPIO_CONFIG1_ADDR (SOC_SYSTEM_REG_BASE + (0x31 << 2))

#define SYS_GPIO_CONFIG1_GPIO_CONFIG1_POS (0)
#define SYS_GPIO_CONFIG1_GPIO_CONFIG1_MASK (0xffffffff)

#define SYS_GPIO_CONFIG2_ADDR (SOC_SYSTEM_REG_BASE + (0x32 << 2))

#define SYS_GPIO_CONFIG2_GPIO_CONFIG2_POS (0)
#define SYS_GPIO_CONFIG2_GPIO_CONFIG2_MASK (0xffffffff)

//TODO 
#define SYS_SYS_DEBUG_CONFIG1_ADDR (0)
#define SYS_SYS_DEBUG_CONFIG0_ADDR (SOC_SYSTEM_REG_BASE + (0x38 << 2))

#define SYS_DBUG_CONFIG0_ADDR (SOC_SYSTEM_REG_BASE + (0x38 << 2))

#define SYS_DBUG_CONFIG0_DBUG_MSG_POS (0)
#define SYS_DBUG_CONFIG0_DBUG_MSG_MASK (0xffff)

#define SYS_DBUG_CONFIG0_DBUG_MUX_POS (16)
#define SYS_DBUG_CONFIG0_DBUG_MUX_MASK (0xf)

#define SYS_DBUG_CONFIG0_RESERVED_20_31_POS (20)
#define SYS_DBUG_CONFIG0_RESERVED_20_31_MASK (0xfff)

#define SYS_ANAREG_STAT_ADDR (SOC_SYSTEM_REG_BASE + (0x3a << 2))

#define SYS_ANAREG_STAT_ANAREG_STAT_POS (0)
#define SYS_ANAREG_STAT_ANAREG_STAT_MASK (0xffffffff)

#ifdef __cplusplus
}
#endif
