
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t svdf_2_input_sequence[42] = {29,   81,   -38, 17,  -116, 43,  119,  -127, 74,  115, 9,    118,  7,    -56,
                                        -53,  -14,  -98, 60,  -128, 10,  28,   -18,  12,  -28, -126, 87,   -115, -44,
                                        -123, -109, -59, -87, -69,  121, -128, -95,  -70, 2,   81,   -119, 84,   -122};
