
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t svdf_2_weights_feature[70] = {27,   82,  -108, -127, 85,  3,   -51, 32,  110, -6,  -14, -16,  31,  101,
                                         -122, 19,  76,   74,   -80, 12,  -22, -17, 10,  -28, 55,  109,  2,   -107,
                                         -4,   72,  -65,  -59,  36,  -69, 105, -97, 25,  38,  110, -121, -88, -126,
                                         -14,  16,  -88,  -66,  3,   -93, 69,  -64, 44,  103, 95,  -95,  68,  -46,
                                         106,  -31, -63,  23,   -38, 36,  -95, -43, 93,  77,  91,  -26,  33,  59};
