
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#define DEPTHWISE_NULL_BIAS_0_OUT_CH 2
#define DEPTHWISE_NULL_BIAS_0_IN_CH 2
#define DEPTHWISE_NULL_BIAS_0_INPUT_W 4
#define DEPTHWISE_NULL_BIAS_0_INPUT_H 5
#define DEPTHWISE_NULL_BIAS_0_DST_SIZE 40
#define DEPTHWISE_NULL_BIAS_0_INPUT_SIZE 40
#define DEPTHWISE_NULL_BIAS_0_OUT_ACTIVATION_MIN -128
#define DEPTHWISE_NULL_BIAS_0_OUT_ACTIVATION_MAX 127
#define DEPTHWISE_NULL_BIAS_0_INPUT_BATCHES 1
#define DEPTHWISE_NULL_BIAS_0_FILTER_X 2
#define DEPTHWISE_NULL_BIAS_0_FILTER_Y 2
#define DEPTHWISE_NULL_BIAS_0_STRIDE_X 1
#define DEPTHWISE_NULL_BIAS_0_STRIDE_Y 1
#define DEPTHWISE_NULL_BIAS_0_PAD_X 0
#define DEPTHWISE_NULL_BIAS_0_PAD_Y 0
#define DEPTHWISE_NULL_BIAS_0_OUTPUT_W 4
#define DEPTHWISE_NULL_BIAS_0_OUTPUT_H 5
#define DEPTHWISE_NULL_BIAS_0_CH_MULT 1
#define DEPTHWISE_NULL_BIAS_0_INPUT_OFFSET 128
#define DEPTHWISE_NULL_BIAS_0_OUTPUT_OFFSET -15
#define DEPTHWISE_NULL_BIAS_0_DILATION_X 1
#define DEPTHWISE_NULL_BIAS_0_DILATION_Y 1
