
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_null_bias_0_input[40] = {
    -97,  -113, 118, 69, 39,   -32, -1,   -79, -30, -8, 46,   -13, 82,  -19, 15, 105, 94,  -56, 35, 55,
    -122, -105, 70,  33, -128, -87, -109, 50,  2,   78, -113, 113, -50, -33, 19, -6,  -38, 122, 18, -121};
