
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_null_bias_0_output_ref[40] = {1,  -91, 52, -57,  65,  -99, 62, 59,   55, -110, 97,  -2,  -15, -128,
                                                   85, 36,  38, -128, -13, -56, 49, -107, 29, 62,   -26, -96, 29,  -128,
                                                   3,  -16, 41, -13,  14,  -54, 22, -96,  17, -17,  13,  -15};
