WT_MEMBER_POOL(WM_TEST_START, _wt_start, _wt_parse_none, "start")
WT_MEMBER_POOL(WM_TEST_STOP, _wt_stop, _wt_parse_none, "stop")
WT_MEMBER_POOL(WM_TEST_SOFTAP, _wt_softap_start, _wt_parse_softap, "softap")
WT_MEMBER_POOL(WM_TEST_STA, _wt_sta_start, _wt_parse_none, "sta")
WT_MEMBER_POOL(WM_TEST_JOIN, _wt_connect, _wt_parse_join, "join")
WT_MEMBER_POOL(WM_TEST_LEAVE, _wt_disconnect, _wt_parse_none, "leave")
// stop reconnecting to wifi AP. it doesn't expect to receive a signal because AP is already disconnected */
WT_MEMBER_POOL(WM_TEST_CANCEL, _wt_cancel, _wt_parse_none, "cancel")
WT_MEMBER_POOL(WM_TEST_SET, _wt_set_info, _wt_parse_set, "set")
WT_MEMBER_POOL(WM_TEST_GET, _wt_get_info, _wt_parse_none, "get")
WT_MEMBER_POOL(WM_TEST_RESET, _wt_reset_info, _wt_parse_none, "reset")
WT_MEMBER_POOL(WM_TEST_SCAN, _wt_scan, _wt_parse_scan, "scan")
WT_MEMBER_POOL(WM_TEST_MODE, _wt_display_state, _wt_parse_none, "mode")
WT_MEMBER_POOL(WM_TEST_STATS, _wt_get_stats, _wt_parse_none, "stats")
WT_MEMBER_POOL(WM_TEST_INFO, _wt_get_conn_info, _wt_parse_none, "info")
WT_MEMBER_POOL(WM_TEST_AUTO, _wt_auto_test, _wt_parse_auto, "auto")
WT_MEMBER_POOL(WM_TEST_ONOFF, _wt_onoff_test, _wt_parse_join, "on_off")
WT_MEMBER_POOL(WM_TEST_STRESS, _wt_stress_test, _wt_parse_stress, "stress")
