WT_MEMBER_POOL(WM_TEST_START, wm_start, _wm_test_parse_none, "start")
WT_MEMBER_POOL(WM_TEST_STOP, wm_stop, _wm_test_parse_none, "stop")
WT_MEMBER_POOL(WM_TEST_SOFTAP, wm_softap_start, _wm_test_softap, "softap")
WT_MEMBER_POOL(WM_TEST_STA, wm_sta_start, _wm_test_parse_none, "sta")
WT_MEMBER_POOL(WM_TEST_JOIN, wm_connect, _wm_test_join, "join")
WT_MEMBER_POOL(WM_TEST_LEAVE, wm_disconnect, _wm_test_parse_none, "leave")
// stop reconnecting to wifi AP. it doesn't expect to receive a signal because AP is already disconnected */
WT_MEMBER_POOL(WM_TEST_CANCEL, wm_cancel, _wm_test_parse_none, "cancel")
WT_MEMBER_POOL(WM_TEST_SET, wm_set_info, _wm_test_set, "set")
WT_MEMBER_POOL(WM_TEST_GET, wm_get_info, _wm_test_parse_none, "get")
WT_MEMBER_POOL(WM_TEST_RESET, wm_reset_info, _wm_test_parse_none, "reset")
WT_MEMBER_POOL(WM_TEST_SCAN, wm_scan, _wm_test_scan, "scan")
WT_MEMBER_POOL(WM_TEST_MODE, wm_display_state, _wm_test_parse_none, "mode")
WT_MEMBER_POOL(WM_TEST_STATS, wm_get_stats, _wm_test_parse_none, "stats")
WT_MEMBER_POOL(WM_TEST_INFO, wm_get_conn_info, _wm_test_parse_none, "info")
WT_MEMBER_POOL(WM_TEST_AUTO, wm_auto_test, _wm_test_auto, "auto")
WT_MEMBER_POOL(WM_TEST_ONOFF, wm_onoff_test, _wm_test_join, "on_off")
WT_MEMBER_POOL(WM_TEST_STRESS, wm_stress_test, _wm_test_stress, "stress")
