
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t svdf_weights_feature[72] = {43,  34,  -69, 80,   -11,  -78, -73, -60, 3,   -98, -111, -40, -102, 15, -99,
                                       -96, 64,  1,   -120, 117,  94,  -6,  -43, 80,  101, 25,   41,  71,   19, -76,
                                       55,  -49, -92, 98,   -58,  4,   126, 65,  112, -22, 65,   -86, 38,   64, -86,
                                       -39, 65,  6,   -97,  -116, 15,  -84, 122, 40,  18,  40,   -78, 84,   63, -35,
                                       -6,  11,  69,  -45,  51,   80,  -9,  17,  102, 63,  4,    11};
