
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_dilation_input[90] = {
    72,  28,  -30, -110, 13,  -96, 34,   -95, 94,   95,   -98,  -91,  21,  10, -109, -69, 24,   105,
    -17, 59,  -30, -114, -81, 0,   104,  -8,  -30,  -58,  -40,  -71,  -63, 95, 53,   -9,  102,  -53,
    47,  59,  -79, -85,  124, -79, 44,   38,  -125, 59,   -29,  -104, -44, 25, -8,   -95, -121, 16,
    117, 13,  47,  -15,  -38, 47,  -112, 92,  68,   -23,  19,   22,   104, -5, -117, 82,  13,   -69,
    9,   -99, -85, 38,   -36, -8,  54,   88,  34,   -120, -123, 17,   21,  55, -115, 104, 66,   -11};
