
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_dilation_output_ref[81] = {
    -19, 8,  18,  0,   2,   14,  -38, 2,   -41, 3,   7,  -7,  -19, 44,  8,   -43, -3, -33, 30,  -6,  11,
    -31, 23, 24,  -46, 14,  -46, 11,  2,   -9,  -21, 4,  29,  -70, 10,  -25, 11,  -6, 18,  -36, -16, 0,
    -70, 27, -45, 9,   13,  -22, -4,  -13, 38,  -54, 18, -41, 16,  2,   2,   -31, 5,  29,  -46, -10, -33,
    80,  -2, -13, -42, -24, 31,  -70, 6,   -66, 54,  11, -26, -33, -15, 21,  -23, 4,  -65};
