
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.8.0 as reference.
#pragma once
#define AVGPOOLING_INT16_3_OUT_CH 21
#define AVGPOOLING_INT16_3_IN_CH 21
#define AVGPOOLING_INT16_3_INPUT_W 1
#define AVGPOOLING_INT16_3_INPUT_H 20
#define AVGPOOLING_INT16_3_DST_SIZE 147
#define AVGPOOLING_INT16_3_INPUT_SIZE 420
#define AVGPOOLING_INT16_3_OUT_ACTIVATION_MIN -32768
#define AVGPOOLING_INT16_3_OUT_ACTIVATION_MAX 32767
#define AVGPOOLING_INT16_3_INPUT_BATCHES 1
#define AVGPOOLING_INT16_3_FILTER_X 1
#define AVGPOOLING_INT16_3_FILTER_Y 3
#define AVGPOOLING_INT16_3_STRIDE_X 1
#define AVGPOOLING_INT16_3_STRIDE_Y 3
#define AVGPOOLING_INT16_3_PAD_X 0
#define AVGPOOLING_INT16_3_PAD_Y 0
#define AVGPOOLING_INT16_3_OUTPUT_W 1
#define AVGPOOLING_INT16_3_OUTPUT_H 7
