
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t conv_dilation_golden_input[48] = {91,  10,   63,  -51, -30, 96,  22,  125,  -87, -100, -86, 62,
                                             -78, -108, -84, -20, -51, 40,  123, 116,  114, 27,   -79, 6,
                                             -98, 11,   115, 104, -41, 104, -97, 100,  -18, -48,  70,  -29,
                                             -49, -90,  -48, 109, 81,  24,  -8,  -116, 23,  117,  80,  -4};
