/*  This file is for build security API in Linux */
#ifndef __TINYARA_CONFIG_H__
#define __TINYARA_CONFIG_H__

#define CONFIG_SECURITY_UTC_CRYPTO 1
#define CONFIG_EXAMPLES_TESTCASE_SECURITY_FRAMEWORK_UTC_AUTH 1
#define CONFIG_EXAMPLES_TESTCASE_SECURITY_FRAMEWORK_UTC_CRYPTO 1
#define CONFIG_EXAMPLES_TESTCASE_SECURITY_FRAMEWORK_UTC_KEYMGR 1
#define CONFIG_EXAMPLES_TESTCASE_SECURITY_FRAMEWORK_UTC_SS 1

#define FAR
#define ERROR -1
#define OK 0
#endif // __TINYARA_CONFIG_H__
