
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t mul_output_ref[160] = {
    -44,  -71,  -126, -21,  -94,  -29,  31,   -18,  -53,  -99,  -68,  -117, -113, -108, -118, -115, -41,  -27,
    -126, -128, 59,   -112, 64,   70,   -102, -106, 21,   -79,  -10,  -116, -117, -97,  -47,  -77,  -115, 64,
    -106, -119, -109, -43,  26,   -44,  -101, -92,  60,   -30,  -93,  -122, -63,  -46,  -58,  -104, -41,  -72,
    -71,  -124, -91,  -4,   -122, -92,  -51,  -106, 15,   -84,  -112, -108, -51,  -118, -57,  -71,  -73,  73,
    4,    -97,  -92,  -117, -125, -68,  -112, -63,  -109, -110, -121, -110, -88,  -101, 34,   -54,  -62,  -85,
    -109, -44,  -119, -5,   25,   -126, -102, -71,  -123, -104, -97,  -124, -106, -73,  -126, -21,  52,   -83,
    -116, -125, 1,    -123, -115, -82,  -104, -81,  -33,  -46,  69,   -84,  -105, -58,  -89,  -108, -74,  -17,
    -61,  -88,  84,   18,   -9,   -110, -93,  -24,  51,   -122, 12,   -23,  -117, -78,  -5,   -116, -90,  -103,
    -102, -116, -86,  -118, 12,   -37,  -17,  21,   -98,  -75,  -59,  -74,  -7,   -108, -86,  -71};
