/**
  ******************************************************************************
  * @file    inic_def.h
  * @author
  * @version
  * @date
  * @brief
  ******************************************************************************
  * @attention
  *
  * This module is a confidential and proprietary property of RealTek and
  * possession or use of this module requires written permission of RealTek.
  *
  * Copyright(c) 2024, Realtek Semiconductor Corporation. All rights reserved.
  ******************************************************************************
  */

#ifndef __WHC_DEF_H_
#define __WHC_DEF_H_

#define BASIC_API_BASE						0x0000
#define EXT_API_BASE						0x1000
#define INTER_API_BASE						0x2000
#define MISC_API_BASE						0x3000
#define NAN_API_BASE						0x4000
#define P2P_API_BASE						0x5000
#define PROXY_API_BASE						0x6000
#define WTN_API_BASE						0x8000

#define WHC_API_PROCESS_DONE				0

#define WHC_MP_MSG_BUF_SIZE				4096

enum WHC_WIFI_C2H_API_ID {
	/* 0x0001~0x1000 reserved for basic API */
	WHC_API_SCAN_USER_CALLBACK					= BASIC_API_BASE + 1,
	WHC_API_SCAN_EACH_REPORT_USER_CALLBACK		= BASIC_API_BASE + 2,

	WHC_API_AP_CH_SWITCH						= BASIC_API_BASE + 5,
	WHC_API_WIFI_EVENT							= BASIC_API_BASE + 6,
	WHC_API_PROMISC_CALLBACK					= BASIC_API_BASE + 7,
	WHC_API_GET_LWIP_INFO						= BASIC_API_BASE + 8,
	WHC_API_SET_NETIF_INFO						= BASIC_API_BASE + 9,
	WHC_API_CFG80211_SCAN_REPORT				= BASIC_API_BASE + 10,
	WHC_API_IP_TABLE_CHK						= BASIC_API_BASE + 11,
	WHC_API_IP_ACS								= BASIC_API_BASE + 12,
	WHC_API_UPDATE_REGD_EVENT					= BASIC_API_BASE + 13,

	/* 0x2001~0x3000 reserved for inter API */

	/* 0x4001~0x5000 reserved for nan API */
	WHC_API_CFG80211_NAN_REPORT_MATCH_EVENT		= NAN_API_BASE + 1,
	WHC_API_CFG80211_NAN_DEL_FUNC					= NAN_API_BASE + 2,
	WHC_API_CFG80211_NAN_CFGVENDOR_EVENT			= NAN_API_BASE + 3,
	WHC_API_CFG80211_NAN_CFGVENDOR_CMD_REPLY		= NAN_API_BASE + 4,

	/* 0x5001~0x6000 reserved for p2p API */

	/* 0x8001~0x9000 reserved for wifi tunnel API */
	WHC_API_WTN_SOCKET_INIT						= WTN_API_BASE + 1,
	WHC_API_WTN_SOCKET_SEND						= WTN_API_BASE + 2,
	WHC_API_WTN_RNAT_AP_INIT						= WTN_API_BASE + 3,
	WHC_API_WTN_OTA_CALLBACK					= WTN_API_BASE + 4,
};

enum WHC_WIFI_H2C_API_ID {
	/* 0x0001~0x1000 reserved for basic API */
	WHC_API_WIFI_CONNECT						= BASIC_API_BASE + 1,
	WHC_API_WIFI_DISCONNECT					= BASIC_API_BASE + 2,
	WHC_API_WIFI_IS_CONNECTED_TO_AP			= BASIC_API_BASE + 3,
	WHC_API_WIFI_IS_RUNNING					= BASIC_API_BASE + 4,
	WHC_API_WIFI_SET_CHANNEL					= BASIC_API_BASE + 5,
	WHC_API_WIFI_GET_CHANNEL					= BASIC_API_BASE + 6,
	WHC_API_WIFI_SET_USR_CFG					= BASIC_API_BASE + 7,
	WHC_API_WIFI_SET_HOST_RTOS					= BASIC_API_BASE + 8,

	WHC_API_WIFI_ON							= BASIC_API_BASE + 9,
	WHC_API_WIFI_INIT_AP						= BASIC_API_BASE + 10,
	WHC_API_WIFI_DEINIT_AP						= BASIC_API_BASE + 11,
	WHC_API_WIFI_START_AP 						= BASIC_API_BASE + 12,
	WHC_API_WIFI_STOP_AP						= BASIC_API_BASE + 13,
	WHC_API_WIFI_SCAN_NETWROKS					= BASIC_API_BASE + 14,
	WHC_API_WIFI_GET_SCANNED_AP_INFO			= BASIC_API_BASE + 15,
	WHC_API_WIFI_SCAN_ABORT					= BASIC_API_BASE + 16,

	WHC_API_WIFI_SME_AUTH							= BASIC_API_BASE + 17,
	WHC_API_WIFI_SME_SET_ASSOCREQ_IE				= BASIC_API_BASE + 18,

	/* 0x1001~0x2000 reserved for ext API */
	WHC_API_WIFI_SET_MAC_ADDR					= EXT_API_BASE + 1,
	WHC_API_WIFI_GET_MAC_ADDR					= EXT_API_BASE + 2,
	WHC_API_WIFI_DRIVE_IS_MP					= EXT_API_BASE + 3,
	WHC_API_WIFI_AP_GET_CONNECTED_CLIENTS	= EXT_API_BASE + 4,
	WHC_API_WIFI_GET_SETTING					= EXT_API_BASE + 5,
	WHC_API_WIFI_SET_IPS_EN					= EXT_API_BASE + 6,
	WHC_API_WIFI_SET_LPS_EN					= EXT_API_BASE + 7,
	WHC_API_WIFI_SET_LPS_LISTEN_INTERVAL		= EXT_API_BASE + 8,
	WHC_API_WIFI_SET_MFP_SUPPORT				= EXT_API_BASE + 9,
	WHC_API_WIFI_SET_GROUP_ID					= EXT_API_BASE + 10,
	WHC_API_WIFI_SET_PMK_CACHE_EN				= EXT_API_BASE + 11,
	WHC_API_WIFI_SAE_STATUS					= EXT_API_BASE + 12,
	WHC_API_WIFI_FT_STATUS						= EXT_API_BASE + 13,
	WHC_API_WIFI_GET_TRAFFIC_STATS				= EXT_API_BASE + 14,
	WHC_API_WIFI_GET_PHY_STATS				= EXT_API_BASE + 15,
	WHC_API_WIFI_SET_WIRELESS_MODE				= EXT_API_BASE + 16,
	WHC_API_WIFI_SET_WPS_PHASE					= EXT_API_BASE + 17,
	WHC_API_WIFI_SET_GEN_IE					= EXT_API_BASE + 18,
	WHC_API_WIFI_SET_EAP_PHASE					= EXT_API_BASE + 19,
	WHC_API_WIFI_GET_EAP_PHASE					= EXT_API_BASE + 20,
	WHC_API_WIFI_SET_EAP_METHOD				= EXT_API_BASE + 21,
	WHC_API_WIFI_SEND_EAPOL					= EXT_API_BASE + 22,
	WHC_API_WIFI_START_JOIN_CMD					= BASIC_API_BASE + 23,

	WHC_API_WIFI_CUS_IE						= EXT_API_BASE + 25,
	WHC_API_WIFI_SEND_MGNT						= EXT_API_BASE + 27,
	WHC_API_WIFI_SET_TXRATE_BY_TOS				= EXT_API_BASE + 28,
	WHC_API_WIFI_SET_EDCA_PARAM				= EXT_API_BASE + 29,
	WHC_API_WIFI_SET_TX_CCA_EN				= EXT_API_BASE + 30,
	WHC_API_WIFI_SET_CTS2SEFL_DUR_AND_SEND		= EXT_API_BASE + 31,
	WHC_API_WIFI_GET_ANTENNA_INFO				= EXT_API_BASE + 32,
	WHC_API_WIFI_GET_BAND_TYPE					= EXT_API_BASE + 33,
	WHC_API_WIFI_AP_DEL_CLIENT						= EXT_API_BASE + 34,
	WHC_API_WIFI_AP_CH_SWITCH					= EXT_API_BASE + 35,
	WHC_API_WIFI_CONFIG_CSI					= EXT_API_BASE + 36,
	WHC_API_WIFI_GET_CCMP_KEY					= EXT_API_BASE + 38,
	WHC_API_WIFI_SET_TX_POWER					= EXT_API_BASE + 39,
	WHC_API_WIFI_GET_TX_POWER					= EXT_API_BASE + 40,
	WHC_API_WIFI_SET_CONN_STEP_TRY_LIMIT		= EXT_API_BASE + 41,
	WHC_API_WIFI_AP_TOGGLE_VISIBLE				= EXT_API_BASE + 42,
	WHC_API_WIFI_WAKE_PLL_RDY_IN_PS				= EXT_API_BASE + 43,
	WHC_API_WIFI_GET_CHANNEL_LIST				= EXT_API_BASE + 44,
	WHC_API_WIFI_SET_BROADCAST_WHITE_LIST		= EXT_API_BASE + 45,
	WHC_API_WIFI_PS_EN_BY_BT_ON					= EXT_API_BASE + 46,
	WHC_API_WIFI_SET_WOWLAN_RX_BROADCAST        = EXT_API_BASE + 47,
	WHC_API_WIFI_SET_LPS_BCN_WINDOW_MANUAL_CONFIG	= EXT_API_BASE + 48,

	/* 0x2001~0x3000 reserved for inter API */
	WHC_API_WIFI_SET_WPA_MODE					= INTER_API_BASE + 2,
	WHC_API_WIFI_SET_PMF_MODE					= INTER_API_BASE + 3,
	WHC_API_WIFI_ADD_KEY						= INTER_API_BASE + 7,
	WHC_API_WPA_4WAY_REPORT					= INTER_API_BASE + 9,
	WHC_API_WPA_PMKSA_OPS						= INTER_API_BASE + 10,
	WHC_API_WIFI_SET_OWE_PARAM					= INTER_API_BASE + 11,
	WHC_API_WIFI_PROMISC_INIT					= INTER_API_BASE + 12,
	WHC_API_WIFI_DHCP_SUCCESS_IND					= INTER_API_BASE + 13,

	/* 0x3001~0x4000 reserved for misc API */
	WHC_API_WIFI_IP_UPDATE						= MISC_API_BASE + 1,
	WHC_API_WIFI_IWPRIV_INFO					= MISC_API_BASE + 2,
	WHC_API_WIFI_MP_CMD						= MISC_API_BASE + 3,
	WHC_API_WIFI_GET_WIRELESS_MODE				= MISC_API_BASE + 4,
	WHC_API_WIFI_MSG_TO						= MISC_API_BASE + 5,
	WHC_API_WIFI_SPEAKER						= MISC_API_BASE + 6,
	WHC_API_WIFI_SET_CHPLAN					= MISC_API_BASE + 7,
	WHC_API_WIFI_SET_EDCCA_PARAM				= MISC_API_BASE + 8,
	WHC_API_WIFI_GET_EDCCA_MODE				= MISC_API_BASE + 9,
	WHC_API_WIFI_SET_COUNTRY_CODE				= MISC_API_BASE + 10,
	WHC_API_WIFI_GET_COUNTRY_CODE				= MISC_API_BASE + 11,
	WHC_API_WIFI_SET_TX_ADVANCED_CFG			= MISC_API_BASE + 12,

	/* 0x4001~0x5000 reserved for nan API */
	WHC_API_NAN_INIT							= NAN_API_BASE + 1,
	WHC_API_NAN_DEINIT							= NAN_API_BASE + 2,
	WHC_API_NAN_START							= NAN_API_BASE + 3,
	WHC_API_NAN_STOP							= NAN_API_BASE + 4,
	WHC_API_NAN_ADD_FUNC						= NAN_API_BASE + 5,
	WHC_API_NAN_DEL_FUNC						= NAN_API_BASE + 6,
	WHC_API_NAN_CFGVENFOR						= NAN_API_BASE + 7,

	/* 0x5001~0x6000 reserved for p2p API */
	WHC_API_P2P_ROLE							= P2P_API_BASE + 1,
	WHC_API_P2P_REMAIN_ON_CH					= P2P_API_BASE + 2,

	/* 0x6001~0x7000 reserved for proxy API */
	WHC_API_WAR_OFFLOAD_CTRL					= PROXY_API_BASE + 1,
	WHC_API_WAR_SET_MDNS_PARA					= PROXY_API_BASE + 2,

	/* 0x8001~0x9000 reserved for wifi tunnel API */
	WHC_API_WTN_IDENTITY_KEY_SET				= WTN_API_BASE + 1,
	WHC_API_WTN_OTA_CALLBACK_REGISTER			= WTN_API_BASE + 2,
	WHC_API_WTN_GET_NODE_INFO					= WTN_API_BASE + 3,
	WHC_API_WTN_GET_CHILD_NUM					= WTN_API_BASE + 4,
	WHC_API_WTN_GET_CHILD_MAC_LIST				= WTN_API_BASE + 5,
	WHC_API_WTN_CHECK_OTA_VER					= WTN_API_BASE + 6,
	WHC_API_WTN_UPDATE_OTA_VER					= WTN_API_BASE + 7,
	WHC_API_WTN_FIX_FATHER						= WTN_API_BASE + 8,

};

enum IPC_LWIP_INFO_TYPE {
	WHC_WLAN_GET_IP = 0,
	WHC_WLAN_GET_GW = 1,
	WHC_WLAN_GET_GWMSK = 2,
	WHC_WLAN_GET_HW_ADDR = 3,
	WHC_WLAN_IS_VALID_IP = 4
};

#endif

