
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const q15_t dw_int16xint8_fast_null_bias_output_ref[72] = {
    -866,   -9369,  18025,  14936, 8948,  18291,  1225, -12887, 17485,  11598, -1880,  2217,   24936, 25780, 5322,
    4380,   -17000, 23903,  -2885, 13396, 11649,  6528, -9735,  9763,   -599,  2135,   3433,   1923,  25943, -8111,
    -7396,  27277,  -17000, -3610, -2397, -17000, -161, -7144,  9838,   14752, -12791, -2353,  11865, -1897, -17000,
    -8240,  22236,  2458,   -774,  15668, -17000, 1488, -3932,  -17000, 14050, -159,   -17000, 2347,  -8647, 5208,
    -17000, -12409, -17000, -1805, -3957, -17000, 5042, 12495,  4144,   -2766, -10838, 25524};
