
/*
 * < CONFIG BOOT OPTION
 */
#if defined(CONFIG_PLATFORM_TIZENRT_OS)
#define  CONFIG_XIP_FLASH 1
#else
#undef  CONFIG_XIP_FLASH
#endif
/*
 * < CONFIG SOC PS
 */
#define CONFIG_SOC_PS_EN 1
#define CONFIG_SOC_PS_MODULE 1

/*
 * < CONFIG BT
 */
#define CONFIG_BT_MENU 1
#define CONFIG_BT_CA32_SINGLE_CORE 1
#undef  CONFIG_BT_KM4_SINGLE_CORE
#define CONFIG_BT 1
#define CONFIG_BT_SINGLE_CORE 1
#define CONFIG_BT_ADVANCED_FEATURE_MENU 1
#define CONFIG_BT_EXCLUDE_MP_FUNCTION 1 
#define CONFIG_BT_EXAMPLE_DEMO_MENU 1
#define CONFIG_BT_PERIPHERAL 1
#define CONFIG_BT_CENTRAL 1
#define CONFIG_BT_SCATTERNET 1
#undef  CONFIG_BT_MESH_PROVISIONER_MENU
#undef  CONFIG_BT_MESH_DEVICE_MENU
#undef  CONFIG_BT_MESH_PROVISIONER_SCATTERNET_MENU
#undef  CONFIG_BT_MESH_DEVICE_SCATTERNET_MENU
#undef  CONFIG_BT_A2DP_MENU


/*
 * < CONFIG WIFI
 */
#define CONFIG_WLAN_MENU 1
#define CONFIG_AS_INIC_KM4_NP_CA32_AP 1
#undef  CONFIG_SINGLE_CORE_WIFI_KM4
#define CONFIG_WLAN 1
#define CONFIG_AS_INIC_AP 1
#define CONFIG_LWIP_LAYER 1
#if defined(CONFIG_PLATFORM_TIZENRT_OS)
#define  CONFIG_HIGH_TP_TEST 1
#else
#undef CONFIG_HIGH_TP_TEST
#endif


/*
 * < MENUCONFIG FOR AP CONFIG
 */

/*
 * < CONFIG CHIP
 */
#define CONFIG_AMEBAD2 1
#define ARM_CORE_CA32 1
#define CONFIG_FPGA 1
#define CONFIG_RL6678_A_CUT 1

/*
 * < CONFIG TEST MODE
 */
#undef  CONFIG_MP
#undef  CONFIG_CP
#undef  CONFIG_FT
#undef  CONFIG_EQC
#undef  CONFIG_OLT

/*
 * < CONFIG OS
 */
#define CONFIG_KERNEL 1
#define PLATFORM_FREERTOS 1
#define TASK_SCHEDULER_DISABLED (0)

/*
 * < CONFIG USB
 */
#undef  CONFIG_USB_OTG_EN

/*
 * < MBED_API
 */
#define CONFIG_MBED_API_EN 1

/*
 * < CONFIG FUNCTION TEST
 */
#undef  CONFIG_PER_TEST

/*
 * < CONFIG 802154
 */
#undef  CONFIG_802154_PHY_EN
#undef  CONFIG_802154_RADIO_COEX_PTA_EN

/*
 * < SSL Config
 */
#define CONFIG_MBED_TLS_ENABLED 1

/*
 * < Audio Config
 */
#undef  CONFIG_AUDIO_FWK
#undef  CONFIG_MEDIA_PLAYER
#undef  CONFIG_MEDIA_LITE_PLAYER

/*
 * < IPC Message Queue Config
 */
#undef  CONFIG_IMQ

/*
 * < CLINTWOOD Config
 */
#undef  CONFIG_CLINTWOOD

/*
 * < GUI Config
 */
#undef  CONFIG_GUI_EN

/*
 * To set debug msg flag
 */
#define CONFIG_DEBUG_LOG 1

/*
 * < Build Option
 */
#define CONFIG_TOOLCHAIN_ASDK 1
#undef  CONFIG_TOOLCHAIN_ARM_GCC
#define CONFIG_LINK_ROM_LIB 1
#undef  CONFIG_LINK_ROM_SYMB

/*
 * < CONFIG IAR PROJECT
 */
#if defined(CONFIG_INIC_IPC_DISABLE) && (CONFIG_INIC_IPC_DISABLE == 1)
#ifdef CONFIG_WLAN
#undef CONFIG_WLAN
#endif
#ifdef CONFIG_HIGH_TP_TEST
#undef CONFIG_HIGH_TP_TEST
#endif
#ifdef CONFIG_AS_INIC_AP
#undef CONFIG_AS_INIC_AP
#endif
#ifdef CONFIG_LWIP_LAYER
#undef CONFIG_LWIP_LAYER
#endif
#endif
#undef  CONFIG_AUDIO_MIXER
#undef  CONFIG_AUDIO_PASSTHROUGH
#undef  CONFIG_MEDIA_PLAYER
#undef  CONFIG_MEDIA_DEMUX_WAV
#undef  CONFIG_MEDIA_DEMUX_MP3
#undef  CONFIG_MEDIA_DEMUX_AAC
#undef  CONFIG_MEDIA_DEMUX_MP4
#undef  CONFIG_MEDIA_DEMUX_FLAC
#undef  CONFIG_MEDIA_DEMUX_OGG
#undef  CONFIG_MEDIA_CODEC_PCM
#undef  CONFIG_MEDIA_CODEC_MP3
#undef  CONFIG_MEDIA_CODEC_HAAC
#undef  CONFIG_MEDIA_CODEC_VORBIS
#undef  CONFIG_MEDIA_CODEC_OPUS

/* New SDK macros */
#define CONFIG_AMEBA_RLS 1
#define CONFIG_AMEBASMART 1
#define CONFIG_SUPPORT_NAND_FLASH 1
#define CONFIG_SUPPORT_FATFS_USB 1
#define CONFIG_SUPPORT_SD_CARD 1
#define CONFIG_SUPPORT_USB 1
#define CONFIG_SUPPORT_USB_SHARED_DFIFO 1
#define CONFIG_SUPPORT_USBD_UAC 1
#define CONFIG_SUPPORT_USBD_MSC_SECOND_FLASH 1
#define CONFIG_SUPPORT_USBH_UAC 1
#define CONFIG_SUPPORT_USBH_ECM 1
#define CONFIG_SUPPORT_USBH_ECM_BRIDGE 1
#define CONFIG_SUPPORT_SDIOH 1
#define CONFIG_SUPPORT_SMP 1
#define CONFIG_SUPPORT_AUDIO_DEVICE 1
#define CONFIG_SUPPORT_AUDIO_CMD_ARECORD 1
#define CONFIG_SUPPORT_AUDIO_CMD_APLAY 1
#define CONFIG_SUPPORT_AUDIO_CMD_PLAYER 1
#define CONFIG_SUPPORT_AUDIO_CMD_PCRECORD 1
#define CONFIG_IMG1_SRAM 1
#define CONFIG_IMG2_FLASH 1
#define CONFIG_SHELL 1
#define CONFIG_SUPPORT_ATCMD 1
#define CONFIG_ATCMD_MANUAL_TEST 1
#define CONFIG_ATCMD_NETWORK 1
#define CONFIG_SHELL_TASK_STACK_BASIC_SIZE 2440
#define CONFIG_ASSERTION_ENABLE 1
#define CONFIG_VFS_LITTLEFS_INCLUDED 1
#define CONFIG_KERNEL 1
#define CONFIG_PLATFORM_FREERTOS 1
#define CONFIG_CA32_FREERTOS_V10_2_1_SMP 1
#define CONFIG_BACK_TRACE_DEPTH_LIMIT 8
#define CONFIG_WHC_HOST 1
#define CONFIG_WHC_WIFI_API_PATH 1
#define CONFIG_WIFI_CSI_ENABLE 1
#define CONFIG_HIGH_TP_TEST 1
#define CONFIG_WLAN_CRITICAL_CODE_IN_RAM 1
#define CONFIG_WLAN 1
#define CONFIG_WHC_INTF_IPC 1
#define CONFIG_AS_INIC_AP 1
#define CONFIG_LWIP_LAYER 1
#define CONFIG_VFS_ENABLED 1
#define CONFIG_BT_HAS_BREDR 1
#define CONFIG_BT_HAS_MESH 1
#define CONFIG_BT_HAS_LEAUDIO 1
#define CONFIG_BT_DUAL_MODE 1
#define CONFIG_BT 1
#define CONFIG_FTL_ENABLED 1
#define CONFIG_BT_PERIPHERAL 1
#define CONFIG_BT_CENTRAL 1
#define CONFIG_BT_SCATTERNET 1
#define CONFIG_PBUF_POOL_BUFSIZE 508
#define CONFIG_MBEDTLS_ENABLED 1
#define CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN 16384
#define CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN 4096
#define CONFIG_BT_COEXIST 1
#define CONFIG_COEXIST_HOST 1
#define CONFIG_LINK_ROM_SYMB 1
#define CONFIG_ARM_CORE_CA32 1
#define CONFIG_NEON 1
#define CONFIG_SMP_DUAL_CORE 1
#define CONFIG_CORE_NUM 2
#define CONFIG_SMP 1
// #define CONFIG_ENABLE_WPS 1
// #define CONFIG_ENABLE_WPS_DISCOVERY 1