// crypto_type, crypto_string, crypto_description
CT_CRYPTO_TABLE(WIFI_MANAGER_CRYPTO_NONE,             "none",     "none encryption")
CT_CRYPTO_TABLE(WIFI_MANAGER_CRYPTO_WEP_64,           "64",       "WEP encryption wep-40")
CT_CRYPTO_TABLE(WIFI_MANAGER_CRYPTO_WEP_128,          "128",      "WEP encryption wep-104")
CT_CRYPTO_TABLE(WIFI_MANAGER_CRYPTO_AES,              "aes",      "AES encryption")
CT_CRYPTO_TABLE(WIFI_MANAGER_CRYPTO_TKIP,             "tkip",     "TKIP encryption")
CT_CRYPTO_TABLE(WIFI_MANAGER_CRYPTO_TKIP_AND_AES,     "mixed",    "TKIP and AES mixed encryption")
CT_CRYPTO_TABLE(WIFI_MANAGER_CRYPTO_AES_ENT,          "aes_ent",  "Enterprise AES encryption")
CT_CRYPTO_TABLE(WIFI_MANAGER_CRYPTO_TKIP_ENT,         "tkip_ent", "Enterprise TKIP encryption")
CT_CRYPTO_TABLE(WIFI_MANAGER_CRYPTO_TKIP_AND_AES_ENT, "mixed_ent","Enterprise TKIP and AES mixed encryption")
CT_CRYPTO_TABLE(WIFI_MANAGER_CRYPTO_UNKNOWN,          "unknown",  "unknown encryption")
