// auth_type, auth string, description
CT_AUTH_TABLE(WIFI_MANAGER_AUTH_OPEN,                 "open",        "open mode")
CT_AUTH_TABLE(WIFI_MANAGER_AUTH_WEP_SHARED,           "wep_shared",  "use shared key (wep key)")
CT_AUTH_TABLE(WIFI_MANAGER_AUTH_WPA_PSK,              "wpa",         "WPA_PSK mode")
CT_AUTH_TABLE(WIFI_MANAGER_AUTH_WPA2_PSK,             "wpa2",        "WPA2_PSK mode")
CT_AUTH_TABLE(WIFI_MANAGER_AUTH_WPA3_PSK,             "wpa3",        "WPA3_PSK mode")
CT_AUTH_TABLE(WIFI_MANAGER_AUTH_WPA_AND_WPA2_PSK,     "wpa12",       "WPA_PSK and WPA_PSK mixed mode")
CT_AUTH_TABLE(WIFI_MANAGER_AUTH_WPA2_AND_WPA3_PSK,    "wpa23",       "WPA2_PSK and WPA3_PSK mixed mode")
CT_AUTH_TABLE(WIFI_MANAGER_AUTH_WPA_PSK_ENT,          "wpa",         "Enterprise WPA_PSK mode")
CT_AUTH_TABLE(WIFI_MANAGER_AUTH_WPA2_PSK_ENT,         "wpa2",        "Enterprise WPA2_PSK mode")
CT_AUTH_TABLE(WIFI_MANAGER_AUTH_WPA_AND_WPA2_PSK_ENT, "wpa12",       "Enterprise WPA_PSK and WPA_PSK mixed mode")
CT_AUTH_TABLE(WIFI_MANAGER_AUTH_IBSS_OPEN,            "ibss_open",   "IBSS ad-hoc mode")
CT_AUTH_TABLE(WIFI_MANAGER_AUTH_WPS,                  "wps",         "WPS mode")
CT_AUTH_TABLE(WIFI_MANAGER_AUTH_UNKNOWN,              "none",        "unknown type")
