// Copyright 2020-2025 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <common/bk_err.h>

#ifdef __cplusplus
extern "C" {
#endif

enum io_matrix_code{
#ifdef CONFIG_IO_MATRIX_VER1_0
	FUNC_CODE_GPIO = 0,
	FUNC_CODE_SPI0_MISO,
	FUNC_CODE_SPI0_MOSI,
	FUNC_CODE_SPI0_NSS,
	FUNC_CODE_SPI0_SCK,
	FUNC_CODE_SPI1_MISO,
	FUNC_CODE_SPI1_MOSI,
	FUNC_CODE_SPI1_NSS,
	FUNC_CODE_SPI1_SCK,
	FUNC_CODE_SPI2_MISO,
	FUNC_CODE_SPI2_MOSI,
	FUNC_CODE_SPI2_NSS,
	FUNC_CODE_SPI2_SCK,
	FUNC_CODE_I3C_SCL,
	FUNC_CODE_I3C_SDA,
	FUNC_CODE_I3C_SDA_PURN,
	FUNC_CODE_NULL,           /* 16 */
	FUNC_CODE_CAN0_RX,
	FUNC_CODE_CAN0_STANDBY,
	FUNC_CODE_CAN0_TX,
	FUNC_CODE_CAN1_RX,
	FUNC_CODE_CAN1_STANDBY,
	FUNC_CODE_CAN1_TX,
	FUNC_CODE_DMIC1_CLK,
	FUNC_CODE_DMIC1_DAT,
	FUNC_CODE_DMIC2_CLK,
	FUNC_CODE_RESV,
	FUNC_CODE_DMIC_CLK,
	FUNC_CODE_DMIC_DAT,
	FUNC_CODE_HDMI_CEC,       /* 29 */
	FUNC_CODE_I2C0_SCL,
	FUNC_CODE_I2C0_SDA,
	FUNC_CODE_I2C1_SCL,
	FUNC_CODE_I2C1_SDA,
	FUNC_CODE_I2C2_SCL,
	FUNC_CODE_I2C2_SDA,
	FUNC_CODE_I2C3_SCL,
	FUNC_CODE_I2C3_SDA,
	FUNC_CODE_I2S0_DIN,
	FUNC_CODE_I2S0_DOUT,
	FUNC_CODE_I2S0_SCK,
	FUNC_CODE_I2S0_SYNC,
	FUNC_CODE_I2S1_DIN,
	FUNC_CODE_I2S1_DOUT,
	FUNC_CODE_I2S1_SCK,
	FUNC_CODE_I2S1_SYNC,
	FUNC_CODE_I2S2_DIN,
	FUNC_CODE_I2S2_DOUT,
	FUNC_CODE_I2S2_SCK,
	FUNC_CODE_I2S2_SYNC,
	FUNC_CODE_I2S3_DIN,
	FUNC_CODE_I2S3_DOUT,
	FUNC_CODE_I2S3_SCK,
	FUNC_CODE_I2S3_SYNC,
	FUNC_CODE_I2S_MCLK,
	FUNC_CODE_IRDA0,          /* 55 */
	FUNC_CODE_IRDA1,
	FUNC_CODE_JTAG_TCK,
	FUNC_CODE_JTAG_TMS,
	FUNC_CODE_LIN0_RXD,
	FUNC_CODE_LIN0_SLEEP,
	FUNC_CODE_LIN0_TXD,
	FUNC_CODE_LIN1_RXD,
	FUNC_CODE_LIN1_SLEEP,
	FUNC_CODE_LIN1_TXD,
	FUNC_CODE_PWM0_0,          /* 65 */
	FUNC_CODE_PWM0_1,
	FUNC_CODE_PWM0_2,
	FUNC_CODE_PWM0_3,
	FUNC_CODE_PWM0_4,
	FUNC_CODE_PWM0_5,
	FUNC_CODE_PWM0_6,
	FUNC_CODE_PWM0_7,
	FUNC_CODE_PWM0_8,
	FUNC_CODE_PWM0_9,
	FUNC_CODE_PWM0_10,
	FUNC_CODE_PWM0_11,
	FUNC_CODE_SC0_CLK,        /* 77 */
	FUNC_CODE_SC0_IO,
	FUNC_CODE_SC0_RSTN,
	FUNC_CODE_SC0_VCC,
	FUNC_CODE_SC1_CLK,
	FUNC_CODE_SC1_IO,
	FUNC_CODE_SC1_RSTN,
	FUNC_CODE_SC1_VCC,
	FUNC_CODE_SPDIF0_RX,
	FUNC_CODE_SPDIF0_TX,
	FUNC_CODE_SPDIF1_RX,
	FUNC_CODE_SPDIF1_TX,
	FUNC_CODE_UART0_CTS,
	FUNC_CODE_UART0_RTS,
	FUNC_CODE_UART0_RXD,
	FUNC_CODE_UART0_TXD,
	FUNC_CODE_UART1_RXD,
	FUNC_CODE_UART1_TXD,
	FUNC_CODE_UART2_RXD,
	FUNC_CODE_UART2_TXD,
	FUNC_CODE_UART3_RXD,
	FUNC_CODE_UART3_TXD,
	FUNC_CODE_HIGH_Z,         /* 99 */
	FUNC_CODE_126 = 126,
	FUNC_CODE_127 = 127,
	FUNC_CODE_128 = 128,
	FUNC_CODE_129 = 129,
	FUNC_CODE_130 = 130,
	FUNC_CODE_131 = 131,
	FUNC_CODE_132 = 132,
	FUNC_CODE_133 = 133,
	FUNC_CODE_134 = 134,
	FUNC_CODE_INVALID = 0xff,
#elif defined(CONFIG_IO_MATRIX_VER2_0)
	FUNC_CODE_HIGH_Z,
	FUNC_CODE_INPUT,
	FUNC_CODE_OUTPUT,
	FUNC_CODE_INPUT_OUTPUT,
	FUNC_CODE_BT_ACTIVE,
	FUNC_CODE_BT_ANT_0,
	FUNC_CODE_BT_ANT_1,
	FUNC_CODE_BT_ANT_2,
	FUNC_CODE_BT_ANT_3,
	FUNC_CODE_BT_PRIORITY,
	FUNC_CODE_CLK_AUXS,
	FUNC_CODE_CLK_XTAL,
	FUNC_CODE_CLK_XTAL_DIV,
	FUNC_CODE_DEBUG_0,
	FUNC_CODE_DEBUG_1,
	FUNC_CODE_DEBUG_2,
	FUNC_CODE_DEBUG_3,
	FUNC_CODE_DEBUG_4,
	FUNC_CODE_DEBUG_5,
	FUNC_CODE_DEBUG_6,
	FUNC_CODE_DEBUG_7,
	FUNC_CODE_DEBUG_8,
	FUNC_CODE_DEBUG_9,
	FUNC_CODE_DEBUG_10,
	FUNC_CODE_DEBUG_11,
	FUNC_CODE_DEBUG_12,
	FUNC_CODE_DEBUG_13,
	FUNC_CODE_DEBUG_14,
	FUNC_CODE_DEBUG_15,
	FUNC_CODE_DEM_LNA_EN,
	FUNC_CODE_I2C0_SCL,
	FUNC_CODE_I2C0_SDA,
	FUNC_CODE_I2C1_SCL,
	FUNC_CODE_I2C1_SDA,
	FUNC_CODE_I2S_MCLK,
	FUNC_CODE_I2S0_DIN,
	FUNC_CODE_I2S0_DOUT,
	FUNC_CODE_I2S0_SCK,
	FUNC_CODE_I2S0_SYNC,
	FUNC_CODE_LEDC,
	FUNC_CODE_LPO_CLK,
	FUNC_CODE_OTP_FRE_EN,
	FUNC_CODE_OTP_FRE_OUT,
	FUNC_CODE_OTP_FRE_SEL,
	FUNC_CODE_PWM0_0,
	FUNC_CODE_PWM0_1,
	FUNC_CODE_PWM0_2,
	FUNC_CODE_PWM0_3,
	FUNC_CODE_PWM0_4,
	FUNC_CODE_PWM0_5,
	FUNC_CODE_PWM0_6,
	FUNC_CODE_PWM0_7,
	FUNC_CODE_PWM0_8,
	FUNC_CODE_PWM0_9,
	FUNC_CODE_PWM0_10,
	FUNC_CODE_PWM0_11,
	FUNC_CODE_QSPI0_CS,
	FUNC_CODE_QSPI0_DAT_0,
	FUNC_CODE_QSPI0_DAT_1,
	FUNC_CODE_QSPI0_DAT_2,
	FUNC_CODE_QSPI0_DAT_3,
	FUNC_CODE_QSPI0_SCK,
	FUNC_CODE_SDIO_CLK,
	FUNC_CODE_SDIO_CMD,
	FUNC_CODE_SDIO_DATA_0,
	FUNC_CODE_SDIO_DATA_1,
	FUNC_CODE_SDIO_DATA_2,
	FUNC_CODE_SDIO_DATA_3,
	FUNC_CODE_SPI0_MISO,
	FUNC_CODE_SPI0_MOSI,
	FUNC_CODE_SPI0_NSS,
	FUNC_CODE_SPI0_SCK,
	FUNC_CODE_SPI1_MISO,
	FUNC_CODE_SPI1_MOSI,
	FUNC_CODE_SPI1_NSS,
	FUNC_CODE_SPI1_SCK,
	FUNC_CODE_SWCLK,
	FUNC_CODE_SWDIO,
	FUNC_CODE_TAMP_RX,
	FUNC_CODE_TAMP_TX,
	FUNC_CODE_UART0_CTS,
	FUNC_CODE_UART0_RTS,
	FUNC_CODE_UART0_RXD,
	FUNC_CODE_UART0_TXD,
	FUNC_CODE_UART1_RXD,
	FUNC_CODE_UART1_TXD,
	FUNC_CODE_UART2_RXD,
	FUNC_CODE_UART2_TXD,
	FUNC_CODE_UART3_CTS,
	FUNC_CODE_UART3_RTS,
	FUNC_CODE_UART3_RXD,
	FUNC_CODE_UART3_TXD,
	FUNC_CODE_WIFI_ACTIVE,
	FUNC_CODE_WIFI_RX_EN,
	FUNC_CODE_WIFI_TX_EN,
	FUNC_CODE_INVALID = 0x5f,
#endif
};

typedef enum io_matrix_code IOMX_CODE_T;

/**
 * @brief IO MUX defines
 * @addtogroup bk_api_iomux_defs WDT API group
 * @{
 */

typedef uint8_t iomx_unit_t; /**< wdt uint id */

/**
 * @}
 */

#ifdef __cplusplus
}
#endif

