
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q15_t dw_int16xint8_output_ref[72] = {
    -12590, -21111, 403,   -15091, 15704,  6791,   15782, 5124,   13868,  -10195, -17592, -7150, -11747, -21111, -12457,
    5852,   17333,  5061,  -21111, 5956,   6110,   1181,  -7691,  14996,  -21111, -12003, 11163, -21111, -18704, -10357,
    22395,  -18556, -7600, 4244,   -21111, 23562,  -2820, 14575,  -21111, 31088,  -14324, -8578, -16985, 32734,  12942,
    13438,  -117,   -130,  29034,  2148,   2462,   5599,  -4725,  -12125, -11525, 7517,   1607,  -5720,  -13112, -1061,
    8747,   -18178, 19050, 10784,  28408,  -13156, -5073, -10973, 8473,   9277,   4904,   570};
