
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const q7_t dw_int16xint8_weights[96] = {
    -101, 18,  -66,  28,  -125, -9,  -127, -63,  118, 16,   81,   79,  101,  -99, 112, -79, 10,   26,  63, -118,
    -14,  -31, 116,  31,  -21,  94,  58,   -40,  -51, -127, -12,  74,  117,  -30, -19, -92, -35,  -28, 87, -92,
    -66,  7,   -3,   -70, 91,   -71, -66,  127,  125, 37,   -108, -60, -127, -53, -26, -74, -127, 0,   41, 127,
    -77,  17,  -106, 81,  10,   -89, 117,  -105, -88, 94,   -102, -49, -90,  14,  -98, 47,  53,   -78, 24, -51,
    105,  127, 95,   96,  -44,  -21, 60,   -41,  -62, -85,  -127, 50,  74,   127, -70, 58};
