
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.9.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_kernel_3x3_null_bias_input[100] = {
    -65,  -29,  53, 37,  103, 61,  110, -46,  57,  18,  -110, 16,  -121, -12, -110, -22, 34,  -115, -20, -48,
    -109, 61,   21, 89,  64,  120, 103, -69,  -5,  -18, 43,   -68, -19,  -49, -37,  -90, -89, 122,  31,  37,
    -121, 16,   70, -97, 34,  120, -50, 94,   39,  -59, 88,   44,  -102, 95,  103,  73,  75,  75,   -16, 67,
    -101, -105, 71, 45,  -75, 60,  122, -113, 50,  -20, 38,   -78, 85,   63,  -102, 118, -55, -91,  110, -96,
    -120, 54,   31, 60,  18,  36,  -79, 34,   -28, 14,  43,   -80, -69,  -44, 98,   19,  -20, 91,   -90, -67};
