
/*
 * Copyright (C) 2010-2020 Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by generate_test_data.py using TFL version 2.9.0 as reference.
#pragma once
#include <stdint.h>

const q7_t depthwise_kernel_3x3_null_bias_weights[45] = {
    -117, -86,  -127, -127, -88, -103, -6,   -38, 83,  -80,  -127, -104, 118, 89,   29,
    29,   -94,  -38,  0,    113, -40,  -102, -91, -11, 59,   -33,  19,   10,  -114, -24,
    -5,   -127, 102,  46,   -2,  -36,  52,   44,  62,  -127, -50,  36,   -94, -51,  -8};
